### ISSUE TITLE
Missing tag for version v1.21.5 ?

### ISSUE THREAD

**Issue by hostep** [symfony/flex#1008]
Hi

I just noticed by accident that version v1.21.5 is known on packagist: https://packagist.org/packages/symfony/flex#v1.21.5
But is not available here on github in the tags: https://github.com/symfony/flex/releases/tag/v1.21.5

Which is kind of confusing. Any idea what's going on?

Thanks!

**Comment by xabbuh** [comment]
My guess is that 1.21.5 was created by mistake. It should have been 2.4.3 which created later. Both tags according to Packagist reference the [same commit](https://github.com/symfony/flex/commit/6b44ac75c7f07f48159ec36c2d21ef8cf48a21b1) on the `2.x` branch.

**Comment by fabpot** [comment]
My mistake indeed. Fixed now.

**Comment by hostep** [comment]
Thanks and no worries. I can confirm that v1.21.5 can no longer be found by `composer update` now.
