### ISSUE TITLE
Remove version tag in compose file as marked as obsolete by lastest docker compose version

### ISSUE THREAD

**Issue by sabruss** [symfony/flex#1023]
With the latest version of Docker Compose,

When specifying a version tag in any `compose*.yaml`, 
When running any docker compose command a warning appears stating that the `version` tag is obsolete.

Referring to the Compose documentation [here](https://docs.docker.com/compose/compose-file/04-version-and-name/), it appears that this tag has been purely informational for a long time. Some research suggests that it has been obsolete since the release of Docker Compose v1.27.x on 2020-09-10.

Do you think it can be removed safely ?

**Comment by dunglas** [comment]
Yes. It has already been removed from Symfony Docker and API Platform. You can remove it safely, it's supported by Flex.

**Comment by fabpot** [comment]
@dunglas Does it mean we should remove this line? https://github.com/symfony/flex/blob/2.x/src/Configurator/DockerComposeConfigurator.php#L239

**Comment by dunglas** [comment]
Indeed, good catch.
