### ISSUE TITLE
[Bug] Plugin not triggering when "composer install"

### ISSUE THREAD

**Issue by gander** [symfony/flex#104]
https://getcomposer.org/doc/03-cli.md#create-project

`composer create-project` is like `git clone` and `composer install`. 

Plugin do not work when try install `symfony/skeleton` this way.

**Comment by xabbuh** [comment]
Do you mean that it's not working when using `create-project` or when cloning first and then running `install`?

**Comment by Pierstoval** [comment]
What is the output of your `composer create-project` execution?

**Comment by gander** [comment]
~xabbuh

**Comment by gander** [comment]
This is related to #103. I'm trying to solve the problem and I would first download the repository, then install. There must be two stages.

**Comment by xabbuh** [comment]
Looks like the same issue that was reported in https://github.com/symfony/flex/issues/88#issuecomment-302371716.

**Comment by fabpot** [comment]
Fixed in #107
