### ISSUE TITLE
[Bug] Invalid bundle class from auto-generated recipe

### ISSUE THREAD

**Issue by hason** [symfony/flex#108]
The problematic bundles:
- `easycorp/easy-security-bundle`
- `symfony-cmf/routing-bundle`

Auto generated `etc/bundles.php` contains the invalid bundle classes:
- `EasyCorp\Bundle\EasySecurityBundle\EasyCorpEasySecurityBundle`
- `Symfony\Cmf\Bundle\RoutingBundle\RoutingBundle`

Correct should be:
- `EasyCorp\Bundle\EasySecurityBundle\EasySecurityBundle`
- `Symfony\Cmf\Bundle\RoutingBundle\CmfRoutingBundle`

**Comment by stof** [comment]
Where they configured through an explicit recipe or through the auto-detected recipe generated for the bundle by flex ?
Flex gives this info in the output when running composer in verbose mode.

**Comment by hason** [comment]
```
Symfony operations: 1 recipe
  - Configuring easycorp/easy-security-bundle (v1.0.3): From auto-generated recipe
    Enabling the package as a Symfony bundle
```

**Comment by Fedott** [comment]
I have the same problem with eightpoints/guzzle-bundle

**Comment by fabpot** [comment]
see #135
