### ISSUE TITLE
[Bug] Flex doesn't respect custom bin directory

### ISSUE THREAD

**Issue by hason** [symfony/flex#109]
composer.json:
```json
    "config": {
        "bin-dir": "bin"
    }
```

Error:
```
Executing script vendor/bin/security-checker security:check [KO]
 [KO]
Script vendor/bin/security-checker security:check returned with error code 1
!!  Could not open input file: vendor/bin/security-checker
!!  
!!  
```

**Comment by iammichiel** [comment]
Looks more like an error of the SecurityCheck recipe. As you can see [here](https://github.com/symfony/recipes/blob/master/sensiolabs/security-checker/4.0/manifest.json), it is configured to call `vendor/bin/security-checker`.

**Comment by stof** [comment]
I'm on it

**Comment by stof** [comment]
@hason can you try https://github.com/symfony/recipes/pull/103 ?
