### ISSUE TITLE
Resolve directory paths when displaying messages

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/flex#116]
As you can see here, some messages in Flex output say `%BIN_DIR%` and `%WEB_DIR%` instead of showing the real path to those dirs. Is this on purpose? I find it a bit confusing:

![unresolved-dir-paths](https://user-images.githubusercontent.com/73419/27518410-d3a9a2a4-59df-11e7-851c-e8366a969fe4.png)

**Comment by fabpot** [comment]
That's on purpose, but expanding those directories is also possible. I don't have a strong opinion on this. Maybe expanding is a bit better. PR welcome.

**Comment by fabpot** [comment]
Anyone willing to work on this one?

**Comment by ricardocino** [comment]
If nobody else before that, willing to have a look after work today / tomorrow
