### ISSUE TITLE
Extra blank line added to each .env section

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/flex#119]
This didn't happen with previous Flex versions (I'm using 1.0.10 now):

![symfony-flex-env](https://user-images.githubusercontent.com/73419/27578855-b212de0c-5b25-11e7-83d4-445bf6483ba5.png)

**Comment by iammichiel** [comment]
This was introduced by a refactoring made to the Configurators. The markers are generated using the following function :

```php
protected function markData(Recipe $recipe, $data)
{
    return PHP_EOL.sprintf('###> %s ###%s%s%s###< %s ###%s', $recipe->getName(), PHP_EOL, $data, PHP_EOL, $recipe->getName(), PHP_EOL);
}
```

There is an EOL right before closing marking. This happens because the `$data` already ends with an EOL. A `rtrim` might correct that. Could you test again?
