### ISSUE TITLE
Class App\Kerne_ may not inherit from final class (App\Kernel)

### ISSUE THREAD

**Issue by iammichiel** [symfony/flex#121]
Hi, 

I have the following exception when running a `cache:clear` command on a freshly installed project.

> Class App\Kerne_ may not inherit from final class (App\Kernel)

Steps to reproduce it : 

```
composer create-project symfony/skeleton:^3.3 test
composer req cli
bin/console cache:clear
```

When trying the same command with framework-standard-edition, it runs just fine.

As @dunglas suggested [here](https://gist.github.com/tarlepp/dcb2263957f11ae9711b745dcba623d5), running a `rm -rf` on `var/cache` did not fix it.

**Comment by chalasr** [comment]
CacheClearCommmand doesn't work for custom kernels, that's a symfony/symfony big that won't be fixed. 
You need to use cache:clear --no-warmup and cache:warmup.

**Comment by stof** [comment]
Yeah, if you want to have cache:clear working with warmup enabled, you cannot make your kernel class private (note that cache:clear with warmup enabled is deprecated though)

**Comment by fabpot** [comment]
see symfony/symfony#2332

**Comment by chalasr** [comment]
https://github.com/symfony/symfony/pull/23328 actually :)
