### ISSUE TITLE
[BUG] web to public  make serve Error

### ISSUE THREAD

**Issue by skynetdev** [symfony/flex#124]
Hi, after renaming of directory from web to public I have now error

make serve
make[1]: Entering directory ‘/var/www/mytest/demo’
[ERROR] The document root directory “/var/www/mytest/demo/web” does not exist.
 — — — — —

**Comment by xabbuh** [comment]
should be fixed by symfony/recipes#109

**Comment by skynetdev** [comment]
it still represent after installation of webserver  by this command 

> composer req webserver

:(  still waiting a fix

**Comment by iammichiel** [comment]
Have you performed a `composer update` to have the new structure? (etc -> config, web -> public)

Can you post your makefile please?

**Comment by skynetdev** [comment]
Ok now  fixed.
