### ISSUE TITLE
Issues when using a SQLite database with Flex?

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/flex#129]
Note: I don't know if this caused by Doctrine DBAL, DoctrineBundle, Symfony or Flex, but I can use SQLite with Doctrine + Symfony 3.3, but I can't with Doctrine + Symfony 3.3 + Flex. That's why I open this issue here.

-----

Create a project:

```
$ composer create symfony/skeleton my-project
$ cd my-project/
$ composer require doctrine
```

Configure a SQLite database using the same syntax suggested by Flex:

```ini
# .env
###> doctrine/doctrine-bundle ###
DATABASE_URL="sqlite:///%kernel.project_dir%/var/data.db"
###< doctrine/doctrine-bundle ###
```

Try to create the database:

```
$ ./bin/console doctrine:database:create
```

Then you see this error:

```
Could not create database %kernel.project_dir%/var/data.db for connection named default
An exception occured in driver: SQLSTATE[HY000] [14] unable to open database file
```

The same error happened to me in other projects using Flex (maybe it's caused by .env + DotEnv?) because I use SQLite databases in functional tests (and they work in Symfony 3.3 without Flex).

**Comment by yceruto** [comment]
Probably a typo, should be `sqlite://%kernel.project_dir%/var/data.db` wrong extra `/` in this part: `sqlite///` 

See https://github.com/symfony/recipes/pull/114

**Comment by yceruto** [comment]
However, I think it isn't related to Flex, but Symfony itself, it doesn't parse the `%kernel.project_dir%` correctly, so it's an invalid path on create the database file.

**Comment by fabpot** [comment]
@yceruto is right. Anybody willing to propose a fix on symfony/symfony? /cc @nicolas-grekas

**Comment by javiereguiluz** [comment]
Closing this in favor of https://github.com/symfony/symfony/issues/23527. Thanks!

**Comment by suvambasak** [comment]
sgfghhgf
