### ISSUE TITLE
Issue with the "session" service

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/flex#130]
When upgrading a Symfony app to 3.3.4 + Flex and using HWIOAuthBundle, I saw this error message:

```
!!  Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException:
!! The service "hwi_oauth.resource_owner.twitter" has a dependency on a non-existent
!! service "session". in
!! <my-project>/vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:31
!!
!!  Stack trace:
!!  #0 <my-project>/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php(57): Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->processValue(Object(Symfony\Component\DependencyInjection\Reference), false)
!!  #1 <my-project>/vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php(35): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue(Array, false)
!!  #2 <my-project>/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php(64): Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInval in <my-project>/vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php on line 31
!!
```

The error message is correct, because the `session` service doesn't exist:

```
$ ./bin/console debug:container session

 Select one of the following services to display its information:
  [0] argument_resolver.session
  [1] security.authentication.session_strategy
  [2] security.logout.handler.session
```

The HttpFoundation 3.3.4 component is installed in the app, but the `session` service doesn't exist.

---

For comparison, the Symfony Demo app, which uses the exact same 3.3.4 version, but doesn't use Flex, has the `session` service defined:

```
$ ./bin/console debug:container session

Information for Service "session"
=================================

 ---------------- --------------------------------------------------
  Option           Value
 ---------------- --------------------------------------------------
  Service ID       session
  Class            Symfony\Component\HttpFoundation\Session\Session
  Tags             -
  Public           yes
  Synthetic        no
  Lazy             no
  Shared           yes
  Abstract         no
  Autowired        no
  Autoconfigured   no
 ---------------- --------------------------------------------------
 ```

**Comment by Pierstoval** [comment]
Doesn't the `framework.session` extension configuration has to be specified at least with `null` to be enabled?

**Comment by xabbuh** [comment]
Yes, by default it is disabled (the Standard Edition enabled is explicitly: https://github.com/symfony/symfony-standard/blob/3.3/app/config/config.yml#L26-L29).

**Comment by xabbuh** [comment]
and the same is true for the Symfony Demo: https://github.com/symfony/symfony-demo/blob/master/app/config/config.yml#L45-L47

**Comment by javiereguiluz** [comment]
Thanks for the info. I'm closing this as "no need to fix it". But in https://github.com/symfony/symfony-docs/issues/7809 I've added a note explaining that in 4.0, some important things (such as `session`) don't exist by default, so we must take care of that in the docs. Thanks!

**Comment by fabpot** [comment]
If HWIOAuthBundle needs a session, then we should have a recipe that enables sessions automatically (the same goes for other important bundles that need a session).

**Comment by enlego** [comment]
The same happens while installing FOSUser in Symfony Flex (it requires an inexistent session service)

**Comment by slootjes** [comment]
@fabpot What would be the correct method to create a recipe which enables sessions? I could create a meta package for it which adds a config file to set the framework.session option but I guess this could easily conflict if it was already set up.
