### ISSUE TITLE
Make location of App/Kernel configurable

### ISSUE THREAD

**Issue by gjuric** [symfony/flex#138]
If you move Kernel.php into a separate namespace (ie. src/Vendor/Infrastructure/Symfony/Kernel.php instead of src/Kernel.php) it brakes some packages like `cli` because the bin/console expects the Kernel.php in the App namespace.

Would it be possible for packages to read variables from composer.json to resolve this use cases?

**Comment by chapterjason** [comment]
I got something similar, I changed the namespace from `App` to `Application` in the `composer.json`, after that I have to change the namespace in the `bin\console` and in the `Kernel.php` to get everyting back to work.

**Comment by Pierstoval** [comment]
That's obvious: the kernel is a PHP class, so if you change its namespace, the PHP class reference also has to change.

Doesn't seem like an issue to me, it's already mandatory. It's like saying _"Making location of `src/Controller/DefaultController.php` configurable"_: it obviously needs an update of all references to the class.

**Comment by fabpot** [comment]
Closing as there is nothing to fix on our side.
