### ISSUE TITLE
Add a way to list available flex aliases / recommended packages

### ISSUE THREAD

**Issue by weaverryan** [symfony/flex#140]
Unless I've missed something, we don't have a way (yet) to see a list of the official Flex aliases. Or more broadly, there is no way to see what the official packages are that we recommend installing.

Is there a plan for this already? Is it possible for a Composer plugin to add a new command - e.g. `flex:suggest`?

EDIT: There is https://symfony.sh/ - is this just a nice temporary thing? Or would we improve this page to be a useful way to find packages?

**Comment by Pierstoval** [comment]
> EDIT: There is https://symfony.sh/ - is this just a nice temporary thing? Or would we improve this page to be a useful way to find packages?

We already have a nice HTML output. Maybe we could have `https://symfony.sh/packages.json` and retrieve it list from the composer plugin?

**Comment by weaverryan** [comment]
Yea... my concern with `symfony.sh` is that I don't think the output is nice (yet)... and I also don't think this part is open sourced, so we can't help improve it as a community. But yea, if it exposed a JSON endpoint, we could read it from the plugin. But I also don't know if a plugin has the ability to *add* new commands :)

**Comment by Pierstoval** [comment]
It is: https://getcomposer.org/doc/articles/plugins.md#command-provider

**Comment by weaverryan** [comment]
Apparently there is: http://flexrecipes.org/ - but I'm not sure who is behind it. Anyone know?

**Comment by fabpot** [comment]
symfony.sh has been updated. Should be a bit better now. Not finished yet though.

**Comment by stof** [comment]
@fabpot the page title on symfony.sh is `#`. this does not look nice.

**Comment by stof** [comment]
Btw, it would be great if this page had links to Packagist for each package to see more details about them.

**Comment by fabpot** [comment]
@weaverryan If you want to see something else on this page, please share.

**Comment by fabpot** [comment]
I've just updated the page with the following improvements:

* Now it lists all recipes, both from the contrib and the official repository (the green/orange icon let you see which package belongs to which repository)
* I've fixed the title
* Each package now has a link to Packagist

**Comment by fabpot** [comment]
I'm closing this one as we have improve symfony.sh a lot since then. If there is anything missing, let me know.
