### ISSUE TITLE
Issue about the location of some config files

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/flex#141]
After a discussion about https://github.com/symfony/recipes/pull/162 with @nicolas-grekas, I'm opening this issue to report a potential inconsistency in the config directory. Let's start with this layout:

```
config/
    services.yaml
    packages/
        doctrine.yaml
        dev/
            doctrine.yaml
        test/
            doctrine.yaml
        prod/
            doctrine.yaml
```

**Problem:** how do you define services only for some environments? For example, only for `test` environment? In the old Symfony, you created `services_test.yaml` and that's it. But in the new Symfony we don't have the concept of suffixed config files because we need to simplify things. So, you have to do this:

```
config/
    services.yaml
    packages/
        doctrine.yaml
        dev/
            doctrine.yaml
        test/
            services.yaml    # <------ add this
            doctrine.yaml
        prod/
            doctrine.yaml
```

It looks a bit weird to have `services.yaml` inside `packages/`. In fact, in the past we had `app.yaml` inside `packages/` and we removed it because some of us thought it looked out of place.

-----

One possible solution is to move `dev/`, `test/`, `prod/` out of the `packages/` dir and put them right below the `config/` dir:

```
config/
    services.yaml
    packages/
        doctrine.yaml
    dev/
        packages/
            doctrine.yaml
    test/
        packages/
            doctrine.yaml
        services.yaml
    prod/
        packages/
            doctrine.yaml
```

-----

But we could also think out-of-the-box and see if we can solve this in other ways. For example, a crazy (stupid!) idea would be to add a config option to services so they can define the environments in which they are defined:

```yaml
services:
    App\Service\MyServiceForTest:
        # ...
        enviroments: ['test']
```

Thoughts? Ideas to solve this? Thanks!

**Comment by nicolas-grekas** [comment]
I have one: symfony/recipes#162 :)

**Comment by Pierstoval** [comment]
Just a copy/paste of my proposal in [symfony/recipes#162 (comment)](https://github.com/symfony/recipes/pull/162#issuecomment-325624152)

> I was also thinking about proposing the removal of `packages/`, prefix third-party configuration with `_` and have a structure like this:
> 
> ```
> ./
> ├── config
> │   ├── dev/
> │   │   ├── _framework.yaml
> │   │   └── services.yaml
> │   ├── prod/
> │   ├── test/
> │   │   └── services.yaml
> │   ├── _framework.yaml
> │   ├── _doctrine.yaml
> │   ├── ...
> │   └── services.yaml
> ├── src/
> └── ...
> ```
> 
> It's something I already do in my personal non-flex apps, it makes sure that custom config is not in the same place than third-party config. And when I remove a package (which I did a few months ago by removing a lot of bundles), I just remove files, without looking for additionnal config in other files, like Flex would do.
> 
> This would guarantee that custom non-prefixed yaml files can still be decoupled in multiple files (sometimes, a single `services.yaml` is just not enough for bigger apps...) and loaded at the end of the loading process.
> 
> Another advantage is the removal of a directory level, which seems nice to me.
> 
> But not sure it's relevant nor useful for a DX perspective, and it would need a big change in current recipes (even if it's a simple renaming of all currently versioned yaml files), and maybe another explanation about third-party config vs app config...
> 
> WDYT?

**Comment by yceruto** [comment]
As the current convention we could puts environment directories at root of `config` just for app-conf (https://github.com/symfony/recipes/pull/162#discussion_r135772430) ?

**Comment by yceruto** [comment]
I think also that `packages` directory is important here for two reason (i.e. must keep it): (1) make sure that app-conf can override packages config and (2) separate app-conf from packages-conf to avoid mess.

**Comment by fabpot** [comment]
I prefer to introduce suffixed names like proposed in #162. The proposals here won't work anyway as `services.yml` takes precedence.
