### ISSUE TITLE
Failure during install fails to update composer.json file

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/flex#142]
### steps to reproduce

`composer create symfony/skeleton foo`
`cd foo`
`composer config minimum-stability dev`
`composer req api`

### buggy outcome 1/2
```
Script make cache-warmup returned with error code 2
!!  
!!    [Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]  
!!    You have requested a non-existent service "".                               
```
how do you quickly debug that btw? the error message is just useless...

### buggy outcome 2/2

composer.json file doesn't contain anything about api-platform, despite the fact the package is installed and listed by `composer show`.
Do `composer up` and they are just removed, leaving Flex in an inconsistent state.

**Comment by fabpot** [comment]
Indeed, that's a known issue. The issue here is that if Composer scripts fail, composer reverts the changes done in `composer.json`. So, a composer up removes the package as it's not listed in `composer.json`. Not sure what we can do here . Any suggestions?

**Comment by fabpot** [comment]
We could make running the scripts non fatal.

**Comment by nicolas-grekas** [comment]
Can we hook after composer write the composer.json file?
If yes, can we store the exit status, make the scripts not fail from composer pov, then `exit 1`?

**Comment by nicolas-grekas** [comment]
Does composer have any issue already about it? Willing to solve it there? Ping @Seldaek

**Comment by chalasr** [comment]
1/2 is due to api-platform requiring some packages in dev versions, giving a mix of FWB 3.3 and console 3.4/4.0, leading to `$container->get(false)` because [this check](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/Console/Application.php#L177) is not there in FWB 3.3. We need to either backport the check in FWB:3.3  or add a conflict rule for console>3.4 in FWB:3.3.

**Comment by stof** [comment]
@nicolas-grekas I don't know of any issue related to this. This would probably involve a new `-ignore-script-failure` in the `require` command of composer, to avoid rolling-back the change and the update in case a script fails (allowing you to fix the code and run the command again)

> We need to either backport the check in FWB:3.3 or add a conflict rule for console>3.4 in FWB:3.3.

@chalasr having to to this is a sign of a BC break for the `console.command.ids` parameter in 3.4. We may need to change 3.4 to avoid this instead.

**Comment by chalasr** [comment]
@stof you're right, I'll look at it.

**Comment by weaverryan** [comment]
@Seldaek @naderman Could you guys help? Is there a way to make Composer *not* revert the `composer.json` file when a script fails? Or would that need to be added to Composer?

I keep hitting this bad behavior in Flex - it's a major ugly spot :/.

**Comment by stof** [comment]
We discussed this during the hackday, and they were OK for reverting the composer.json change only for the resolution and installation part, and not for post-update script failures. But @Seldaek said he has not time to work on it soon. So if we want a fix sooner, it is better to provide a PR rather than waiting for him to implement it.

**Comment by weaverryan** [comment]
I've just tried something: composer/composer#6842

Do you guys see any issues? If not, could you review/support it?

**Comment by weaverryan** [comment]
This should be fixed when Composer 1.5.3 is released: https://github.com/composer/composer/pull/6842#issuecomment-347661350

We don't print a message at the bottom, but the `composer.json` file is NOT reverted:

<img width="951" alt="screen shot 2017-11-28 at 4 01 21 pm" src="https://user-images.githubusercontent.com/121003/33344006-67a61420-d455-11e7-8f87-b02c708a6a22.png">

I think this is quite fine 👍

**Comment by Seldaek** [comment]
It looks quite horribly verbose though for a failure that is kinda expected and frequent.. Maybe that could be improved in flex or the cache clear command or both :)

**Comment by bitgandtter** [comment]
I think this is a responsibility of the bundle or package to improve the DX and provide a well integrated recipe, in this case DoctrineBundle should provide the version parameter so it avoids the connection and by that the env requirement and by consequence that issue is not presented.
