### ISSUE TITLE
Installing symfony/flex  Installing symfony/flex

### ISSUE THREAD

**Issue by holycd** [symfony/flex#146]
Using version ^1.0 for symfony/flex
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing symfony/flex (v1.0.17)
    Loading from cache

PHP Parse error:  syntax error, unexpected '?' in D:\wnmp\Nginx\html\symfony_demo\vendor\symfony\flex\src\Flex.php on line 266

Parse error: syntax error, unexpected '?' in D:\wnmp\Nginx\html\symfony_demo\vendor\symfony\flex\src\Flex.php on line 266

**Comment by takeit** [comment]
Make sure you are using correct PHP version (>=7.1).

**Comment by holycd** [comment]
ok,my PHP version is 7.0.8
