### ISSUE TITLE
Proposal to check technical requirements differently

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/flex#149]
### Problem

After reading this issue in Symfony repo (https://github.com/symfony/symfony/issues/24168) I propose to change how we check Symfony requirements.

The problem is that when using Flex we no longer install Symfony but independent pieces. So it doesn't make sense to check the requirements of the entire framework. For example, this check is wrong in lots of scenarios where you don't need sessions:

```php
    $this->addRequirement(
        function_exists('session_start'),
        'session_start() must be available',
        'Install and enable the <strong>session</strong> extension.'
    );
```

### Proposal

What if we allow recipes to declare their technical requirements? Some requirements are complex, like the following, so we cannot define them inside `manifest.json`:

```php
if (function_exists('apc_store') && ini_get('apc.enabled')) {
    if (version_compare($installedPhpVersion, '5.4.0', '>=')) {
        $this->addRequirement(
            version_compare(phpversion('apc'), '3.1.13', '>='),
            'APC version must be at least 3.1.13 when using PHP 5.4',
            'Upgrade your <strong>APC</strong> extension (3.1.13+).'
        );
    } else {
        $this->addRequirement(
            version_compare(phpversion('apc'), '3.0.17', '>='),
            'APC version must be at least 3.0.17',
            'Upgrade your <strong>APC</strong> extension (3.0.17+).'
        );
    }
}
```

A possible solution is to define them in a `requirements.php` file which returns an array of closures that check those requirements:

```php
<?php

$checks = [
    ['ctype extension must be enabled.', function () { return function_exists('ctype_alpha'); }],
];

if (extension_loaded('suhosin')) {
    $checks[] = [
        'suhosin.executor.include.whitelist PHP.ini configuration must include "phar"',
        function () {
            return false !== stripos('suhosin.executor.include.whitelist', 'phar');
        }
    ];
}

return $checks;
```

For security reasons, Flex would only execute the requirements of the main recipe repository.

**Comment by fabpot** [comment]
Your example won't work with your proposal as sessions are part of FrameworkBundle but not enabled by default. So, it should be dynamic depending on your config to be "perfect". I'd say that this is not worth it.

About making it more granular, it sounds like a good idea, but it should be available for all recipes, not just "core" ones. So, PHP is out of question. We could use expressions, but that would mean a dependency, so that's probably not a good idea either.

Not sure how to move forward, but the current checks are probably good enough. For the session example, we could just add some more information about when this check is relevant.

**Comment by stof** [comment]
And for some of them, we may use composer requirements for extension requirements

**Comment by javiereguiluz** [comment]
I think this proposal is not worth it. For critical requirements, we can use composer.json dependencies. For the rest of requirements, the current Requirements Checker is good enough. Closing.

**Comment by hhamon** [comment]
Would it make sense to have some sort of "requirements audit / environment audit" package that would be installed in dev environment only. This package could retrieve requirements from composer.json files and installed package with expressions.
