### ISSUE TITLE
Illegal offset from EnvConfigurator when removing a package

### ISSUE THREAD

**Issue by weaverryan** [symfony/flex#150]
Steps to repeat:

```
composer create-project symfony/skeleton tmp_flex
cd tmp_flex
composer require admin
composer remove admin
```

> preg_replace(): Compilation failed: nothing to repeat at offset 0

The error comes from: https://github.com/symfony/flex/blob/e3b1373914e8b80170e9f77492406a2903ef3b2b/src/Configurator/EnvConfigurator.php#L58

This occurs when trying to unconfigure `doctrine/doctrine-bundle`... which makes sense. I'm on php 7.1.4.

**Comment by fabpot** [comment]
The line you mention is the one I fixed yesterday. So, I think this is now fixed and will be part of the next version. Can you confirm?

**Comment by fabpot** [comment]
bb0cb8a for reference
