### ISSUE TITLE
Installation fails when make is not installed

### ISSUE THREAD

**Issue by michalpipa** [symfony/flex#154]
When `make` is not installed command `composer create-project "symfony/skeleton:^3.3" demo` fails:
```
Executing script make cache-warmup [KO]
 [KO]
Script make cache-warmup returned with error code 127
!!  sh: 1: 
!!  make: not found
```
Shell script should check if `make` is installed before executing it.

**Comment by nesl247** [comment]
Is this still an issue after #184?
