### ISSUE TITLE
Config TreeBuilder

### ISSUE THREAD

**Issue by maximecolin** [symfony/flex#163]
Hello guys,

is it possible to define and register a config TreeBuilder in Symfony Flex without a bundle ? I tried to register an extension which implement ConfigurationExtensionInterface in in Kernel::build but it doesn't seem to work.

**Comment by sstok** [comment]
As far as I know the HttpKernel with DependencyInjection doesn't allow loose Extensions without a bundle registration.

**Comment by ogizanagi** [comment]
Could you be more specific about what doesn't work? :)
Actually, it should, but I suspect you tried to use the `config:dump-reference` command, [which indeed does only look to bundle extensions](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/Command/AbstractConfigCommand.php#L121-L125) :/

**Comment by maximecolin** [comment]
@ogizanagi I just required a config in my tree then clear my cache / refresh my browser to see if Symfony ask me for the missing config key. Also tried to dump the processed config in the extension load method, but nothing.

I was asking if there is an official way to add a config TreeBuilder but it seems there isn't. It will be a nice feature i think.

**Comment by fabpot** [comment]
I'm closing this issue as this is not related to Flex.
