### ISSUE TITLE
404 not found with branch as a version

### ISSUE THREAD

**Issue by syrm** [symfony/flex#166]
Hello,

I have this in my composer : "ccmbenchmark/ting_bundle": "dev-fix/srm/library-type"

Flex try to get informations of my dependencies with this query : 
https://symfony.sh/p/doctrine,cache,iv1.7.1,1503644570;ccmbenchmark,ting,i3.4.2,1506427745;ccmbenchmark,ting_bundle,dev-fix/srm/library-type,1506542972

symfony.sh seems don't like "/" in version

**Comment by fabpot** [comment]
Fixed now.
