### ISSUE TITLE
"Uninitialized string offset: -1" with PHP 7.0

### ISSUE THREAD

**Issue by bitecodes** [symfony/flex#168]
I saw that the requirements for Symfony Flex dropped from PHP 7.1 to 7.0. But creating a new Symfony project causes an error with PHP 7.0.22.

```
composer create-project symfony/skeleton my-project -vvv

[ErrorException]
Uninitialized string offset: -1

Exception trace:
 () at /Users/Thomas/code/my-project/vendor/symfony/flex/src/Configurator/CopyFromRecipeConfigurator.php:37
```

I will use PHP 7.1 instead, but you probably want to review this.

**Comment by fabpot** [comment]
fixed
