### ISSUE TITLE
Composer require with --no-interaction ingnores reciepe

### ISSUE THREAD

**Issue by ElectricMaxxx** [symfony/flex#170]
Is there a chance to answer the interaction of using the reciepe on composer require call itself?

`composer require -n req symfony-cmf/routing-bundle` leads to an ` IGNORING  symfony-cmf/routing-bundle (2.0): From github.com/symfony/recipes-contrib:master`. But i didn't whant to ingnore the reciepe i whanted to default the interaction on `yes`. Same as i do in console `sudo apt install htop -y`

**Comment by fabpot** [comment]
This one is ignored because it's part of the contrib repository. Run `composer config extra.symfony.allow-contrib true` to change this behavior.

**Comment by ElectricMaxxx** [comment]
Ah, sorry. Forgot that. Thanks.
