### ISSUE TITLE
Out of repository versioning

### ISSUE THREAD

**Issue by ElectricMaxxx** [symfony/flex#172]
Hi,
Issues like https://github.com/symfony/skeleton/issues/23 showed that loading the reciepes from an other source the the original repository moves them out of versioning scope
### Why?
As a user i would haves said: "Oh version 3.3.9 of `framwork-bundle` is broken lets skip it and use 3.3.8 until a fix is available" But this won't work, as `^3.3` of the bundle is broken now. And for CI it is really ramdom. And now after the fix on reciepes, the bundle and its functions (yes, the Makefile is one of the functions of the bundle itself) is healed for reasons, that i as user wouldn't understand.
### Other Way
So, why can't we hold the reciepes in our repositories?  Doing so, we could keep them under the repositories versions. Why can go on an register them in both reciepes repositories, so Flex would know them. We could go on an register `symfony bot` to do the validation. And maybe we can start some kind of quality validation for issues i described in https://gist.github.com/ElectricMaxxx/15dca79636d725e972a7e9471208cfd4
At the end we wouldn't need to register them. Flex could look for github repositories with `symfony` and `bundle` as lables and a `manifest.json` in root and cache that information.

**Comment by fabpot** [comment]
I've given answers about this question many times, and I won't change my mind. Sorry. Anyway, I don't understand the issue you mention as this has nothing to do with the fact that the recipe is in the repo or not. I would even say that having the recipe decoupled is better in this case and we were able to fix it without releasing any new version.
