### ISSUE TITLE
impossible to install a bundle with multiple paths in autoload

### ISSUE THREAD

**Issue by lunika** [symfony/flex#176]
Hello,

I start a new project and I would like to try flex.

I required a bundle ([AMQPBundle](https://github.com/Wisembly/AMQPBundle)) and the `require` fails because in its `composer.json` multiple directories are declared for the same namespace prefix : https://github.com/Wisembly/AMQPBundle/blob/master/composer.json#L41

![screenshot from 2017-10-06 14-41-08](https://user-images.githubusercontent.com/767834/31278981-7c9ac1f0-aaa7-11e7-9221-4bcdb9467e09.png)

**Comment by fabpot** [comment]
fixed in #177

**Comment by lunika** [comment]
Thank you
