### ISSUE TITLE
[Proposal] Make initial config more agnostic

### ISSUE THREAD

**Issue by dbrumann** [symfony/flex#178]
One of the reasons the initial setup after creating a new project with `composer create-project "symfony/skeleton:^3.3"` does not contain a `bin/console` is that people might not want to have the console component as a dependency in their application.

Would it make sense to argue in the reverse and say, what if I want to have a pure CLI-application without a web interface? I will not need `public/index.php` or a `config/routes.yaml`, which are there from the start. As far as I can tell this could be moved into a recipe much like `cli`.

I'm not sure if this is really sensible or if it takes things too far. I think it's a neat way to introduce newcomers to the new way of building apps by pulling in dependencies with `composer req`, starting from the very basic building blocks. This will ensure that people grasp this concept before they can build their application by having to chose between `cli`, `webapp` or maybe both or something else as a first step after creating the project.

**Comment by fabpot** [comment]
If you want to create a pure CLI application, you don't need a skeleton. Just requite `symfony/cli` in a new directory and you're good to go. The skeleton and the Flex architecture is only for web applications.
