### ISSUE TITLE
Unescaped xml special chars environment variables breaks phpunit.xml.dist

### ISSUE THREAD

**Issue by clement-michelet** [symfony/flex#180]
Symfony Flex version: 1.0.29
PHP version: 7.1.10
OS: Ubuntu 16.04 from WSL

After having installed the orm-pack with `composer req orm`, my phpunit config is broken.
Flex adds the lines defined in the manifest.json. The `DATABASE_URL` is wrapped in double quotes.
But the double quotes breaks the attribute value. It should handle environment variables with double-quotes.

Generated lines :

```
<!-- ###+ doctrine/doctrine-bundle ### -->
<!-- Format described at http://docs.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/configuration.html#connecting-using-a-url -->
<!-- For an SQLite database, use: "sqlite:///%kernel.project_dir%/var/data.db" -->
<!-- Set "serverVersion" to your server version to avoid edge-case exceptions and extra database calls -->
<env name="DATABASE_URL" value=""mysql://root@127.0.0.1:3306/symfony?charset=utf8mb4&serverVersion=5.7"" />
<!-- ###- doctrine/doctrine-bundle ### -->
```

EDIT: I've renamed to issue. I didn't noticed the unescaped `&` on the value.

**Comment by fabpot** [comment]
Can you submit a pull request to fix this by added proper escaping?
