### ISSUE TITLE
[Question] Possible to use flex without adding recipes?

### ISSUE THREAD

**Issue by kbond** [symfony/flex#181]
I like the ability to use composer require <alias> and the auto-script feature but would like to disable the auto-installation of recipes. I see I can disable contrib recipes but what about official recipes?

**Comment by fabpot** [comment]
No, it's not possible. The auto-scripts feature is a Composer feature. For `composer require`, I suppose you like aliases? Or is it something else?

**Comment by kbond** [comment]
I see. I really like the "expand command" feature:

```json
    "scripts": {
        "auto-scripts": {
            "make cache-warmup": "script",
            "assets:install --symlink --relative %PUBLIC_DIR%": "symfony-cmd"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
    },
```

**Comment by fabpot** [comment]
This snippet is really just regular Composer, except for the way we describe auto-scripts where we can tell Flex that this is a script or a Symfony command. Nothing big though. Anyway, being able to disable recipes would mean disabling the main purpose of Flex. So, probably not something I willing to do.

**Comment by kbond** [comment]
Ok, no biggie, thanks!

**Comment by teohhanhui** [comment]
@fabpot Would you reconsider your stance on adding a way to disable recipes, now that Symfony Flex is presented also as a way to speed up composer resolving of Symfony packages? https://github.com/symfony/flex/pull/378
