### ISSUE TITLE
Flex options are not used

### ISSUE THREAD

**Issue by francoispluchino** [symfony/flex#189]
Currently, all recipe files are copied by the `CopyFromPackageConfigurator` configurator to the root of the project. However, Flex has options that are not used.

```php
// src/Flex.php
private function initOptions(): Options
{
    $options = array_merge([
        'bin-dir' => 'bin',
        'conf-dir' => 'conf',
        'config-dir' => 'config',
        'src-dir' => 'src',
        'var-dir' => 'var',
        'public-dir' => 'public',
    ], $this->composer->getPackage()->getExtra());

    return new Options($options);
}
```

Using these options will allow us to configure Flex for the specificities of each project.

> **Note:** Only the `bin-dir` option is used

A problematic example for all Symfony 3.x Standard Edition projects that want to upgrade to Symfony Flex with a folder structure:

- `app/AppKernel.php`
- `src/MyCompany/Component/*`
- `src/MyCompany/Bundle/*Bundle`

Given that we have to move all the configuration of the `app` directory, it would be logical in this case to have the PHP code of the `App` namespace, not in the `src` folder, but in the `src/App` folder. This allows the folder structure to be preserved:

- `src/App/*` (for any code dedicated to the project)
- `src/App/Kernel.php`
- `src/App/Controller/*`
- `src/MyCompany/*` (containing all reusable components and bundles)
- `src/MyCompany/Component/*`
- `src/MyCompany/Bundle/*Bundle`

Of course we must have a reconfigured autoload:

```json
{
    "autoload": {
        "psr-4": {
            "App\\": "src/App/",
            "MyCompany\\": "src/MyCompany/"
        }
    },
}
```

In issue #185, I proposed to use the path defined for the `App\\` namespace in the autoload to fix this problem (and some misunderstandings at the beginning, caused by the use of an old version of Flex). However, with the unused `src-dir` option, it would suffice to add the `"src-dir": "src/App"` in the extra section of Composer, to fix the problem.

Of course, the other options will also allow for greater flexibility in structure of projects, but that, you have already considered :-).

Adding the implementation of these options will not break compatibility with current recipes, given that the configor will only copy the files into the reconfigured folders (example with the option `"src-dir": "src/App"`: the `src` folder of the recipe will be copied to the `src/App` folder of the project, and not in the `src` folder).

Do you want me to implement a PR to implement all the options?

**Comment by stof** [comment]
Flex *already* support setting these options. But you are talking about configuring `dir-src` in many places in your issue description, and the option name is `src-dir`

**Comment by francoispluchino** [comment]
Sorry I wrote a little fast, I speak well of the `src-dir` option.

**Comment by stof** [comment]
These options *are* used when expanding dirs. Recipes are using `%SRC_DIR%` to be replaced by the configured option (and so on for other).

however, you will need to set this option in your project *before* the recipes are applied.

**Comment by francoispluchino** [comment]
Ok, I see the code in `Symfony\Flex\Options::expandTargetDir($target)`

**Comment by francoispluchino** [comment]
Of course, thank you for your help.

**Comment by francoispluchino** [comment]
However, there is just a problem with the `Kernel.php` file in the recipe that uses `dirname(__DIR__)` to set the path of the project root folder.

Perhaps it would be more flexible to look for the root folder by looking for the location of the `composer.json` file, and give the option to replace that search with a value for better performance?

Because if I define the `src-dir` option to `src/App`, the root path is wrong, and an exception is thrown during the installation.

**Comment by stof** [comment]
Well, just override the path in your project (once it is created, the file becomes yours, you can edit it)

**Comment by francoispluchino** [comment]
Yes, of course, it's do, but for the transfer, it is disturbing to have this error type. Thanks
