### ISSUE TITLE
Q: Default packages

### ISSUE THREAD

**Issue by kironet** [symfony/flex#190]
Hey,

In "framework-standard-edition" it was generating project with required default packages like doctrine, twig, form, swiftmailer, profiler, etc.. 

In flex version it's generating plain symfony project. Is it on purpose or? 

in standard edition you were able to start coding right away after generating a project, now you have to spend some time to require and setup packages back.

**Comment by esserj** [comment]
@kironet @fabpot is [experimenting with the concept of packs](http://fabien.potencier.org/symfony4-demo.html) (@ ±3/4th page)

that should solve that I believe?

**Comment by chapterjason** [comment]
I think it's because Symfony Flex is not only for web applications and it can happen that you dont need those packages.

**Comment by fabpot** [comment]
You should read my blog posts about Flex and the new way to think about an application: https://medium.com/@fabpot

**Comment by kironet** [comment]
I've seen it, but for new SF users it will be really confusing.
