### ISSUE TITLE
[Question] Register a bundle with some dependency bundles

### ISSUE THREAD

**Issue by trandangtri** [symfony/flex#193]
Dear,

I am approaching to support Flex Installation in my Symfony bundle, and I had a problem.

Let's say `MyBundle` are depending on another bundle, called `TheirBundle`. In the old way, the end users will add two bundles into `AppKernel` at the same time.

```php
class AppKernel extends Kernel
{
    public function registerBundles()
    {
        return [
            // ...
            new \Their\Symfony\TheirBundle(),
            new \My\Symfony\MyBundle(),
        ];
    }

    // ...
}
```

And now, I cannot do that with `composer require my/my-bundle` because the `config/bundles.php` was updated with `MyBundle` only, but `TheirBundle`. So I don't know how to fix it. 

Thanks for your support.

PS: I didn't contribute the recipe of my bundle to Symfony yet. Should I do that to get?

**Comment by Pierstoval** [comment]
This is not a problem. If your `my/my-bundle` requires `their/their-bundle`, Flex will auto-install it if i doesn't have a recipe. If it has a recipe, it will resolve it and apply it to your project.
It's all about correct packagist configuration for `their/their-bundle`.

**Comment by trandangtri** [comment]
Hi @Pierstoval,

Thanks for your quick response. 

In my case, the `their/their-bundle` didn't have a recipe yet. And it was installed by composer already for sure. But its bundle was NOT registered in `config/bundles.php`, but my bundle. It affects to some services which my bundle requires. 

Any suggestion or I missed anything? Thanks in advance.

**Comment by Pierstoval** [comment]
If `their/their-bundle` doesn't have a recipe and if it's correctly configured in packagist, Flex is capable of adding it automatically to `bundles.php`. So if it's not, it's the bundle that's not configured properly. Can you share its packagist link or its github repo?

**Comment by stof** [comment]
Make sure that `their/their-bundle` has the type `symfony-bundle` in the composer.json. Then Flex will know it is a bundle and auto-generate a recipe registering the bundle if it has none.

**Comment by trandangtri** [comment]
Here, https://packagist.org/packages/aws/aws-sdk-php-symfony
Seems it missed the type in composer file.

```json
"type": "symfony-bundle"
```

A part from this point, are there anything else I need to investigate?

**Comment by Pierstoval** [comment]
Only add `"type": "symfony-bundle"` and it should work

**Comment by trandangtri** [comment]
Hi again. Unfortunately, it didn't work although I added the symfony bundle type to the composer configuration (a forked version)

Here, `TheirBundle`
https://github.com/trandangtri/aws-sdk-php-symfony/blob/flex/composer.json

Here, `MyBundle`
https://github.com/trandangtri/sqs-queue-bundle/blob/2.x/composer.json

Seems it's not a root cause.

**Comment by Pierstoval** [comment]
Seems strange... I don't see what's the issue here :confused: :thinking: Maybe others may find something.

Maybe it's a license or package version issue (as package is not released but cloned) ? /cc @fabpot

**Comment by weaverryan** [comment]
Hmm. So one of the packages has the correct type, but flex does not generate a re I’ve for it. I noticed that bundle has a non-standard directory structure. I’m not sure how Flex determines the bundle’s class. Perhaps the dir structure prevents it from being discovered. 

To prove/disprove that theory, you could temporarily move the bundle class to the root - just to see if Flex then generates a recipe for it.

**Comment by fabpot** [comment]
@trandangtri Can you share your `composer.json`?

**Comment by fabpot** [comment]
That's because the AWS bundle does not follow the convention for the bundle name. It's currently `Aws\Symfony\AwsBundle`, but Flex looks for the following bundle class names:

Aws\Symfony\Symfony
Aws\Symfony\AwsSymfony
Aws\Symfony\AwsSymfony

**Comment by stof** [comment]
yeah, as the AWS bundle does not use any of the recognized class name, it needs a recipe to configure the class name it needs

**Comment by fabpot** [comment]
@trandangtri Can you submit a pull request to add this recipe (should be in symfony/recipes-contrib)? I would also suggest to make a PR to the bundle repository to change the bundle class name (probably by keeping an alias for BC).

**Comment by trandangtri** [comment]
Dear @fabpot 

Thanks for your information, I did all your suggestion. Let's see AWS Support team to make an action to do.

Best Regards.
