### ISSUE TITLE
Uninstalling flex causes PHP Fatal Error

### ISSUE THREAD

**Issue by aequasi** [symfony/flex#198]
# How to reproduce:

1. Clone new Symfony skeleton project containing flex
2. Initialize project (including installing dev dependencies)
2. Run `composer install --no-dev`

Gives:

```
PHP Fatal error: Uncaught Error: Class 'Symfony\Flex\Response' not found in .../symfony/flex/src/Downloader.php:243
```

**Comment by aequasi** [comment]
Also, not sure if it's related (if it's not, I can open an issue somewhere else) but, attempting to `composer install --no-dev` when flex *isn't* installed causes a different error:

```
> symfony-cmd
sh: symfony-cmd: not found
Script symfony-cmd handling the auto-scripts event returned with error code 127

```

**Comment by weaverryan** [comment]
I haven’t had a chance to debug yet, but I was able to repeat this easily: installing with no-dev deps after already installing *with* dev depa causes the uninstall, and then the error.

**Comment by weaverryan** [comment]
I've just confirmed that #199 will fix the first error.

The second error - `symfony-cmd: not found` is not fixed by that.

**Comment by fabpot** [comment]
For the second issue, you probably got a skeleton where Flex was in the `require-dev` section, but this was reverted soon after being merged.

**Comment by aequasi** [comment]
Yes, that was the case.

**Comment by PortNumber53** [comment]
I had to `composer remove symfony/lts` hopefully it helps someone

**Comment by abelardolg** [comment]
Hi there,
I have this error:

Symfony 5.0.7 (env: prod, debug: false)

Script symfony-cmd handling the auto-scripts event returned with error code 127

I deleted the flex entry inside the composer.json and these commands were executed later:
rm composer.lock
rm -rf var
rm -rf vendor
 composer clear-cache
 composer install --no-dev  --optimize-autoloader
 composer require symfony/apache-pack
![Captura de pantalla de 2020-04-03 21-14-02](https://user-images.githubusercontent.com/22522883/78396680-11d51700-75f0-11ea-92d1-52109f3312ee.png)

What's wrong? 

Any help would be welcome. Thanks and regards.

**Comment by nicolas-grekas** [comment]
These entries are managed by flex. If you remove flex, you must remove them too.

**Comment by abelardolg** [comment]
Hello,
Inside my composer.json doesn't exist entry for flex. Attached here my composer.json to be evaluated 
[composer.txt](https://github.com/symfony/flex/files/4430896/composer.txt)
Best regards.

**Comment by abelardolg** [comment]
I installed Flex and it worked for me.

Best regards.
