### ISSUE TITLE
[Question] Can we improve the first time experience?

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/flex#20]
Currently, when you execute `symfony new my_project`, a new empty app is installed and when browsing the URL suggested by the installer, you see a "Welcome Page".

With Symfony Flex, the message is similar:

![flex-what s-next](https://cloud.githubusercontent.com/assets/73419/24615688/41b7aed6-188f-11e7-81c9-8d8a7037269a.png)

... but you browse that URL and ...

![symfony-first-experience-error](https://cloud.githubusercontent.com/assets/73419/24615705/4e8541f0-188f-11e7-8f4c-c85ecb66dd81.png)

The first thing you see about Symfony is an error page. Not a good experience at all!

---

The solution is not that easy, because the "first time experience" varies a lot depending on what you want to do. The "Welcome Page" is a must if you are going to develop a normal web app ... but you don't need it if you are developing a console app or an API.

**Comment by sstok** [comment]
Can we detect if there are no routes at all (in the default AppKernel), and then show simple page with instructions to register routes? 

About the Console, this is a complex one as the FrameworkBundle heavily depends on the HttpKernel, you would need to introduce something like a CliBundle and split-up the FrameworkBundle into smaller bundles/service-integrations, which thanks to Flex no longer should require to much configuring 😛

**Comment by guzzlefry** [comment]
What about installing a welcome-bundle by default that could be easily removed via `compose rem welcome-bundle`?

**Comment by sstok** [comment]
https://github.com/symfony/symfony/pull/22637#issuecomment-299644148

**Comment by fabpot** [comment]
Taken care of in symfony/symfony#24403
