### ISSUE TITLE
[Symfony.sh] Add a link to view a recipe

### ISSUE THREAD

**Issue by Pierstoval** [symfony/flex#207]
When I navigate on symfony.sh, I can see the package details:
![image](https://user-images.githubusercontent.com/3369266/32831674-540340c0-c9f9-11e7-9a2a-3182c03ed93e.png)
What could be nice is a button to be able to `View recipe` that would link to `https://github.com/symfony/recipes(-contrib)?/tree/master/{vendor/package}` so we can navigate in the structure and see default files. 

It's useful for non-flex projects because it helps viewing default config that might not be in project's documentation, or stuff that we might add later, environment vars, etc.

WDYT?

**Comment by stof** [comment]
@javiereguiluz @fabpot I think this would make sense.

**Comment by fabpot** [comment]
Done

**Comment by Pierstoval** [comment]
:tada: Thanks @fabpot
