### ISSUE TITLE
composer.json not updated if cache warmup generate errors 

### ISSUE THREAD

**Issue by goetas** [symfony/flex#208]
When requiring a package that generates some errors in the cache warmup phase,  `composer.lock` and `symfony.lock` are correctly updated with the newly installed package,  but `composer.json` is not.

This with the first `composer update` causes the removal of the package. (In some cases I've lost hours of work because the post remove hook deleted the  config files created by the package recipe)

**Comment by goetas** [comment]
Obviously it does not happen on projects not using flex

**Comment by fabpot** [comment]
Fix in Composer.
