### ISSUE TITLE
Quoted ENV vars when not necessary

### ISSUE THREAD

**Issue by goetas** [symfony/flex#210]
Is there a way to not quote some env variables? Docker does not support quoting them and this makes more difficult to reuse the same `.env` file both on docker and symfony.

The issue looks related to symfony/flex@1f76909 where `&` is treated as a special character but inside an `.env` file only white space characters have issues as i know.

As example, the `DATABASE_URL` is generated as:

```
DATABASE_URL="mysql://db_user:db_password@127.0.0.1:3306/db_name?charset=utf8mb4&serverVersion=5.7"
```

and is interpreted as:
- `mysql://db_user:db_password@127.0.0.1:3306/db_name?charset=utf8mb4&serverVersion=5.7` by symfony 
- `"mysql://db_user:db_password@127.0.0.1:3306/db_name?charset=utf8mb4&serverVersion=5.7"` by docker

From what I know this is a long standing docker issue but this is how it works...

having just
```
DATABASE_URL=mysql://db_user:db_password@127.0.0.1:3306/db_name?charset=utf8mb4&serverVersion=5.7
```

will work on both sides.

**Comment by fabpot** [comment]
Closing for 2 reasons: we respect the syntax of a standard `.env` file and we escape according to how shells expect things (fix should be done in Docker instead). Then, we don't have `&` in the `DATABASE_URL` value anymore (see symfony/recipes#258).
