### ISSUE TITLE
Flex should ask for confirmation before removing configuration files, if package provides binaries

### ISSUE THREAD

**Issue by ostrolucky** [symfony/flex#213]
Use case:
1. composer require phpunit/phpunit
1. modify phpunit.xml.dist
1. install phpunit via offical phar method
1. composer remove phpunit/phpunit

result: symfony removed phpunit.xml.dist
expected result: Flex shouldn't blindly remove configuration file. I have modified it and I just replaced composer version of phpunit with binary

**Comment by fabpot** [comment]
That's not something we can support. Most of the time, when removing a package, removing the associated files is what needs to be done. This example is an edge case and using Git (or anything similar) let you recover from that situation. So, I'm closing as a won't fix.
