### ISSUE TITLE
Recipe class already defined

### ISSUE THREAD

**Issue by bitgandtter** [symfony/flex#219]
I was just starting a new project using the command

`composer create-project symfony/skeleton my-project`

and i got 

`Fatal error: Cannot declare class Symfony\Flex\Recipe, because the name is already in use in my-project/vendor/symfony/flex/src/Recipe.php on line 19`

NOTE: this was execute inside a directory that has already installed flex on its vendor directory, like a nested installation.

**Comment by fabpot** [comment]
Can you give us more details because I've just tested and it works well with me. I think having the whole output would help (+ probably PHP version and OS).

**Comment by bitgandtter** [comment]
here it is the command sequence and output:

```
root@4c85a612da15:/var/www/framework# composer create-project symfony/skeleton my-project
Installing symfony/skeleton (v3.3.5)
  - Installing symfony/skeleton (v3.3.5): Downloading (100%)         
Created project in my-project
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 24 installs, 0 updates, 0 removals
  - Installing symfony/flex (v1.0.41): Downloading (100%)         

Fatal error: Cannot declare class Symfony\Flex\Recipe, because the name is already in use in /var/www/framework/my-project/vendor/symfony/flex/src/Recipe.php on line 19
root@4c85a612da15:/var/www# php -v
PHP 7.1.9 (cli) (built: Sep 15 2017 00:15:33) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.9, Copyright (c) 1999-2017, by Zend Technologies
```

running inside a docker container. But as i mention above the **framework** directory has its own installation of flex.

I know this is not a common scenario this its a business requirement but the wear thing is that it tries to load flex from the out side vendors dir.

**Comment by fabpot** [comment]
I didn't see the note about your vendor directory. Not sure I fully understand your setup then. I think I have the same question as you, why `composer` would load a class from a local directory. Do you append files in your `php.ini` file or something similar? I'm afraid I cannot help you more than that without something I can reproduce.  Would it be possible for you to share a full script that would reproduce the error.

**Comment by bitgandtter** [comment]
its easy to reproduce if you run

```
composer create-project symfony/skeleton my-project
cd my-project
composer create-project symfony/skeleton my-project
```
you will end up with the issue

**Comment by fabpot** [comment]
Ok, I can now reproduce the issue. That's probably because Composer reads some files from the `vendor/` directory. Later on, when the root project is created, Composer reads files from the new embedded `vendor/` directory and that's where things crash. So, it looks like a Composer issue, for which I cannot do anything.

**Comment by bitgandtter** [comment]
Understood closing here
