### ISSUE TITLE
[Bug] Asset symlinks are not removed when removing packages

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/flex#22]
How to reproduce:

1. `$ composer req admin`
2. `web/bundles/easyadmin` symlink is created pointing at `../vendor/[...]/public/`
3. `$ composer rem admin`
4. `web/bundles/easyadmin` symlink still exists

**Comment by fabpot** [comment]
Closing as there is nothing we can do to fix this one.

**Comment by stof** [comment]
@fabpot `assets:install` does not delete existing symlinks/folders if the corresponding bundle does not provide assets anymore. It does not clean the existing content of the file for unnecessary bundle folders.

**Comment by stof** [comment]
see https://github.com/symfony/symfony-demo/pull/588 where I had to do a cleanup manually (it required doing a `rm -rf web/bundles` before running `assets:install` to have the clean state)

**Comment by fabpot** [comment]
So, that's a bug that needs to be reported on symfony/symfony. That's not related to Flex.

**Comment by stof** [comment]
@fabpot I created the issue on the symfony repo
