### ISSUE TITLE
Flex is not accepting LGPL licensed bundle

### ISSUE THREAD

**Issue by garak** [symfony/flex#221]
I tried to submit a recipe to recipes-contrib, but I got a refusal from the bot, stating:
> only MIT-like/Apache licenses are accepted 

See https://symfony.sh/r/github.com/symfony/recipes-contrib/170

Is it possible to be less strict and accept LGPL licenses?

**Comment by csarrazi** [comment]
Actually, even the Apache 2.0 license is not allowed, from what I can see

**Comment by stof** [comment]
@fabpot shouldn't this rule be enforced only for the official repo ?

**Comment by fabpot** [comment]
For the contrib repo, we also accept the Apache license. More licenses can be added if needed.

**Comment by garak** [comment]
@fabpot it happens that I need to submit to recipes-contrib a package that is licensed under LGPL. Is there any reason to forbid that?

**Comment by sstok** [comment]
FYI, MPL v2.0 (Mozilla Public License) is similar to (L)GPL but doesn't apply to the whole code-base (only files with a copyright header mentioning this), Halite switched to this license recently, and I am using it for Park-Manager. You may want to allow it 👍

LGPL is compatible with Apache 2.0 IIRC 🤔 GPL _is_ not.

**Comment by garak** [comment]
@sstok indeed, GPL3  and Apache2 [are compatible](https://en.wikipedia.org/wiki/Apache_License#GPL_compatibility).

**Comment by garak** [comment]
I think that the whole point is: why refuse any specific license? As soon as a license is open source, it should be accepted in recipes-contrib. Then, anyone is free to choose the licenses he/she likes the most, or to avoid libraries with licenses he/she doesn't like.

**Comment by mhujer** [comment]
I have an issue with Bundle licensed under multiple licenses. Although one of them is MIT, the recipe is marked as failure because of GPL2/3 https://github.com/symfony/recipes-contrib/pull/300#issuecomment-367461853

**Comment by fabpot** [comment]
@symfony-flex-server review again please

**Comment by fabpot** [comment]
@mhujer that was a bug in the validator, which is (hopefully) fixed now.

**Comment by garak** [comment]
@fabpot so a MIT license is still required, or LGPL can be accepted?

**Comment by fabpot** [comment]
I've just fixed a bug when a package has more than one acceptable license.

**Comment by fabpot** [comment]
I will try to have a look at your use case later this week.

**Comment by fabpot** [comment]
LGPL licenses added.
