### ISSUE TITLE
FrameworkBundle must be configured before all other packages

### ISSUE THREAD

**Issue by covex-nn** [symfony/flex#225]
I've copied composer.json from [symfony/skeleton](https://github.com/symfony/skeleton/blob/3.4/composer.json), added `"sonata-project/notification-bundle": "^3.2"` into `require` section. And after `composer install` i've got an error message:

```
Symfony operations: 11 recipes (073fc8f0285c8a9a7e50f725a90a200a)
  - Configuring symfony/flex (>=1.0): From github.com/symfony/recipes:master
  - Configuring sonata-project/datagrid-bundle (>=2.3.0): From auto-generated recipe
  - Configuring twig/extensions (>=1.0): From github.com/symfony/recipes:master
  - Configuring symfony/translation (>=3.3): From github.com/symfony/recipes:master


  [ErrorException]
  file(C:\Users\Mindubaev\Docker\3\test/config/services.yaml): failed to open stream: No such file or directory
```

This error was occurred because Flex tried to add container parameter for `symfony/translation` before `symfony/framework-bundle` was configured.

I think that `symfony/framework-bundle` must be configured before all other packages (except `symfony/flex`) to avoid this error.

**Comment by Pierstoval** [comment]
Did you add `sonata-project/notification-bundle` _before_ or _after_ the FrameworkBundle in the composer.json `require` section? I don't know how Composer behaves in this kind of case, if we can add a priority just by changing the order or something 😕 Because in the real end, priority should be Flex > FrameworkBundle > everything else

**Comment by xabbuh** [comment]
Is there a specific reason you did not use the `composer create-project` command?

**Comment by covex-nn** [comment]
@Pierstoval i tried both, result is the same: Composer installed and Flex tried to configure `symfony/translation` before `symfony/framework-bundle`.

To fix this we could sort recipes in [Symfony\Flex\Flex::update](https://github.com/symfony/flex/blob/8917eb9e7d490088b85ea2a4cd7f2ad52bb0d9ee/src/Flex.php#L130) after `list($recipes, $vulnerabilities) = $this->fetchRecipes()` to put Flex and FrameworkBundle in the beginning of the list for `install` job and to the end for `uninstall`.

@xabbuh i tried to find a way how to develop and test recipes localy to show a result someone before PR to recipes-contrib. The idea was to store only recipe's files + composer.json in git repository, to gitignore everything else and to let composer reinstall application again with `composer install` in other place.

Original composer.json, where Flex failed first:

```json
{
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "config": {
        "platform": {
            "php": "7.1.0"
        },
        "sort-packages": false
    },
    "require": {
        "php": "^7.0.8",
        "symfony/lts": "^3",
        "sonata-project/notification-bundle": "^3.2"
    },
    "require-dev": {
        "doctrine/doctrine-bundle": "^1.8",
        "symfony/doctrine-bridge": "^3.4",
        "symfony/dotenv": "^3.4",
        "symfony/flex": "^1.0",
        "symfony/framework-bundle": "^3.4",
        "symfony/web-server-bundle": "^3.4",
        "symfony/yaml": "^3.4"
    },
    "scripts": {
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install --symlink --relative %PUBLIC_DIR%": "symfony-cmd"
        }
    }
}
```

**Comment by fabpot** [comment]
The `composer.json` have all requirement from the skeleton in the `require-dev` section, that's not supported.

**Comment by covex-nn** [comment]
@fabpot Flex fails even when i put `sonata-project/notification-bundle` in `require` section of `symfony/skeleton` composer.json

Anyway there is no difference between `require` and `require-dev` for Flex:

* `Symfony\Flex\Flex::record` collects all Install, Uninstall and Update operations from composer, that it should record
* `Symfony\Flex\Downloader` downloads all recipes for recorded operations for `Symfony\Flex\Flex::update`
* `Symfony\Flex\Flex::update` installs or uninstalls recipes

May be Flex was not designed to be inside `require-dev` section, but it can apply receips even from there. But it is not a point! All i wanted to say with this issue is if FrameworkBundle is a hard requirement for Flex, then it must be configured after Flex and before all other packages

**Comment by fabpot** [comment]
@covex-nn Can you submit a PR with you suggested changes?

**Comment by covex-nn** [comment]
@fabpot yes, i will submit PR =)
