### ISSUE TITLE
Using SYMFONY_ENDPOINT for forks with custom branch

### ISSUE THREAD

**Issue by aivus** [symfony/flex#226]
Use case:
I want to add support of sf4 for some bundle.
For now I should:

1.  prepare code changes in the bundle repositories. 
2. Merge all this changes and release some version
3. Finally, create recipe and test it.

It seems there is impossible to test recipe for some branch in fork when using `repositories` in my `composer.json`.

**Comment by fabpot** [comment]
You don't need to release new versions. Everything else is correct.
