### ISSUE TITLE
Use %CONFIG_DIR% in ContainerConfigurator?

### ISSUE THREAD

**Issue by simshaun** [symfony/flex#236]
Hi,

I am organizing my backend (Symfony) and frontend (JS/SCSS/etc) files in two separate folders, with `composer.json` and other stuff at the root of the project. (Note: `backend` and `frontend` are only for file organization. Symfony will still be rendering most of the frontend, so it's not like its two separate apps.)

So, I've got `backend/bin/, backend/config/, backend/src/`, etc. I configured `composer.json` to set `"config-dir": "backend/config"`. That has worked fine for installing several bundles.

However, trying to `composer req validator`, I get the error:

    file(E:\_projects\foo/config/services.yaml): failed to open stream: No such file or directory

Looking at the [ContainerConfigurator](https://github.com/symfony/flex/blob/master/src/Configurator/ContainerConfigurator.php#L45), it's using `getcwd().'/config/services.yaml'`.

Compare that to the [BundleConfigurator](https://github.com/symfony/flex/blob/master/src/Configurator/BundlesConfigurator.php#L103) which uses `$this->options->expandTargetDir('%CONFIG_DIR%/bundles.php')`.

I think the ContainerConfigurator should also use the config-dir param. Right? I'll open a PR if so.

**Comment by Pierstoval** [comment]
I think you're right, experts might come after me with wiser words, but I think it's ok to create a PR with this 😄

**Comment by fabpot** [comment]
Looks like we are using a lot of harcoded 'config/' in Flex. @simshaun Can work on a PR to fix them all?

**Comment by VolCh** [comment]
Also looks like we are using a lot of 'hardcoded' `getcwd()` not only with '/config': https://github.com/symfony/flex/blob/bafa4306faab90665c54983e89b6bbd561abae26/src/Configurator/MakefileConfigurator.php#L33 https://github.com/symfony/flex/blob/b22b02a6909b3daf13a118abc8a442c2dd7dfc21/src/Configurator/GitignoreConfigurator.php#L25 
https://github.com/symfony/flex/blob/dc4b6fbe914c8a96559d0723cb9a02c38347604d/src/Configurator/CopyFromRecipeConfigurator.php#L24

But we haven't something like 'flex-root-dir' in `Flex::initOptions()` to use as base in `Options::expandTargetDir()` for project root file like `.gitignore`. Maybe it makes sense to define it with default getcwd() and use only `Options::expandTargetDir()` for paths?

**Comment by simshaun** [comment]
@fabpot I'll try to work on a PR within the next few days.

**Comment by simshaun** [comment]
Ok, so I started a PR to fix the `ContainerConfigurator`, but I'm not sure what to do with all the other instances of `getcwd()`. They are being used in cases like @VolCh mentioned. Does there need to be a new config option called `root-dir` or something like that?
