### ISSUE TITLE
Error on Symfony\Flex\Flex::getFlexId() when enabling xdebug on php.ini

### ISSUE THREAD

**Issue by neilmatillano** [symfony/flex#237]
I get this error after running command "composer install" 

[ErrorException]
  Value returned from method Symfony\Flex\Flex::getFlexId() must be of type ?Symfony\Flex\string, string given

Before this I just added in the php.ini the value xdebug.enable = 1
With the following version info: 

PHP 7.1.11 (cli) (built: Oct 27 2017 11:00:03) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans

**Comment by stof** [comment]
are you sure that Composer actually runs on PHP 7.1 ? Your error message looks like the message provided by PHP 5.x when encountering a scalar typehint

**Comment by nicolas-grekas** [comment]
Also, the return type hint has been removed since a few month on the getFlexId method, are you up to date ?

**Comment by neilmatillano** [comment]
We are using symfony v 3.3 currently

**Comment by stof** [comment]
@neilmatillano please give your Flex version, not your symfony version.

btw, `composer show` gives you the list of all packages you are using, with their version. This is the best way to report the version being used, as it gives the exact info, not a version range.

**Comment by neilmatillano** [comment]
@stof is it this one :   symfony/hhvm-flex v2.0.3 ?

**Comment by stof** [comment]
no, it is `symfony/flex`. what is `symfony/hhvm-flex` ? There is no such package on Packagist

**Comment by stof** [comment]
Can you please post the full output of `composer show symfony/hhvm-flex` to get details about what this package is ?

**Comment by neilmatillano** [comment]
name     : symfony/hhvm-flex
descrip. :
keywords :
versions : * v2.0.3
type     : composer-plugin
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
source   : [git] https://github.com/MakeMeReach/flex a38ed699beb01de58dc7433781a28b11b6dae26a
dist     : []
names    : symfony/hhvm-flex

autoload
psr-4
Symfony\Flex\ => src

requires
composer-plugin-api ^1.1
php ^7.1

requires (dev)
composer/composer ^1.4
symfony/phpunit-bridge ^3.2.8

We are using hhvm so i guess we need this support.
For symfony/flex , i dont have it, I guess because we are not using the latest symfony.
but also we cannot upgrade to the latest symfony because of the lack of hhvm support on the latest version.

**Comment by nicolas-grekas** [comment]
So, you are using a non official fork of Flex.
Please report your issue on the repos you're using:
https://github.com/MakeMeReach/flex
I'm closing here since this is out of scope.

**Comment by fabpot** [comment]
Also, the fork has not been updated since August. We've made many changes, added features and fixes many bugs since then.

**Comment by neilmatillano** [comment]
@fabpot , there's no option on the fork to report this issue? Or do you think anyone contributing on the fork can help?

**Comment by stof** [comment]
Well, if the owner of the unmaintained fork does not even have an issue tracker, it would be one more reason to avoid using it.

On a side note, Symfony 4 officially dropped support for HHVM a few months back (as HHVM announced that they don't care about PHP 7 parity)
