### ISSUE TITLE
Introduce config option for root directory

### ISSUE THREAD

**Issue by simshaun** [symfony/flex#243]
This is a continuation of #236 -- there are still many instances of `getcwd()`.

- https://github.com/symfony/flex/blob/master/src/Flex.php
  (copies `.env.dist to .env`)

- https://github.com/symfony/flex/blob/master/src/Configurator/CopyFromPackageConfigurator.php
- https://github.com/symfony/flex/blob/master/src/Configurator/CopyFromRecipeConfigurator.php
- https://github.com/symfony/flex/blob/master/src/Configurator/EnvConfigurator.php
- https://github.com/symfony/flex/blob/master/src/Configurator/GitignoreConfigurator.php
- https://github.com/symfony/flex/blob/master/src/Configurator/MakefileConfigurator.php

They all assume that the file/dir paths they need are relative to the dir composer is executed from. For my personal needs that's fine, but I'm wondering if some people could need that to be configurable.

For that, I think a new config option (e.g. something like `root-dir`) would need to be introduced.

Thoughts? I will open a PR if this is something others are interested in.

**Comment by fabschurt** [comment]
@simshaun I so do agree with this feature request! The new SF 4 project structure is great, but I’m currently a bit annoyed by the fact that Flex can’t support another «Symfony root». I generally design my projects with the help of the Hexagonal/Clean architecture, so everything Symfony-related is generally stored into `src/Symfony/` and not directly into `src/`, so every time some file/directory is created via a Flex recipe, I have to manually move it to the right destination.

As a side note, I have the same problem with the `make:controller` console command from the *MakerBundle* for example: it will create the new controller in `src/Controller/` with an `App\Controller` namespace, whereas I would like it to be in `src/Symfony/Controller/` with the `App\Symfony\Controller` namespace. I’m not sure how much this is related to our main issue here, maybe not that much.

**Comment by nicolas-grekas** [comment]
Implemented in https://github.com/symfony/flex/pull/448
