### ISSUE TITLE
[Proposal] Create a command to download and apply recipe right from a package

### ISSUE THREAD

**Issue by covex-nn** [symfony/flex#244]
It is not posible to install recipe for private packages with Flex yet (see https://github.com/symfony/flex/issues/206). I suggest to create a special composer command to be able to do this in semi-automatic mode:

```
$ composer apply <package> <version> [--require]
```

To apply a private recipe, a package must contain a recipe (`manifest.json` and other recipe related files) together will its files in repository. Information about recipe dir could be stored in `extra` section of `composer.json`:

```json
{
    "extra": {
        "recipe-dir": ".flex"
    }
}
```

If a `--require` option was given, then a package must be installed into a project and added to `require` section of main `composer.json`

It is possible to implement such command with Composer and Flex right now:

* A `Composer\Package\PackageInterface` object could be created with `$composer->getRepositoryManager()->findPackage($name, $version)` method
* Package contents could be downloaded with `$composer->getDownloadManager()->download($package, $tmpDir)`
* Then, **somehow**, a `Symfony\Flex\Recipe` object could be instantiated using `manifest.json` file from `extra.recipe-dir` directory.
* And then recipe object could be passed to `Symfony\Flex\Configurator::install` method to install
* The only problem here is that there is no _official_ way how to create and validate a recipe object: right now all data for recipe is downloaded from `symfony.sh`

Actually, i have already created a [working prototype](https://github.com/covex-nn/extra-flex) of `apply` command. To see how it works run these commands:

```
composer create-project symfony/skeleton .
composer require covex-nn/extra-flex
composer apply covex-nn/extra-flex-foobar 1.0.2
```

After execution of these commands a [recipe](https://github.com/covex-nn/extra-flex-foobar/blob/master/.flex/manifest.json) from [covex-nn/extra-flex-foobar](https://github.com/covex-nn/extra-flex-foobar/) package will be applied to a project: `translations`, `src/Entity` and `src/Repository` directories will be created and `EXTRA_FLEX` variable will be added to `.env` and `.env.dist`.

So, i can use my own solution right now, while there is no something similar in Flex. But, i do not like it because it is not standard. It would be great if Flex will support such command to automate configuration for private packages.

**Comment by nicolas-grekas** [comment]
Closing as staled.
