### ISSUE TITLE
Handling on composer install

### ISSUE THREAD

**Issue by grachevko** [symfony/flex#245]
1. Use `composer update` or `composer req`.
2. Change new files (delete some configs), then commit it and push.
3. Another developer pull it, make `composer install` 

Result: Deleted configs copied again. 

In my opinion this is unexpected behavior to see changed files after `composer install` command.

**Comment by Pierstoval** [comment]
Have you checked your `symfony.lock` file? If it's not updated, config files from an already installed recipe shouldn't be created again 😕

**Comment by grachevko** [comment]
hm. Not all dependencies was added to `symfony.lock`.
After `rm -rf vendor` and `composer install` flex add all dependencies. 
Thanks :+1:
