### ISSUE TITLE
How to disable particular flex recipy when installing unrelated package through composer?

### ISSUE THREAD

**Issue by przemoli** [symfony/flex#255]
I'm installing codeception, and among it's dependencies is phpunit/phpunit. Flex detects that and enables recipe script. However script just exits whole process after some work without letting composer perform actions for codeception. End result is that no symlinks are created for codeception (there should be ./bin/codeception)

Worst part is that flex recipe will execute even if I manually installed it beforehand.

So how do I disable specific flex recipe, so that composer can install other packaged uninterrupted?

PHP 7.1
Synfony installed through composer create-project symfony/skeleton, resolved to symfony 4.0.2
composer.json:

> {
>     "type": "project",
>     "license": "proprietary",
>     "require": {
>         "php": "^7.1.3",
>         "ext-iconv": "*",
>         "symfony/console": "^4.0",
>         "symfony/flex": "^1.0",
>         "symfony/framework-bundle": "^4.0",
>         "symfony/lts": "^4@dev",
>         "symfony/yaml": "^4.0"
>     },
>     "require-dev": {
>         "codeception/codeception": "^2.3",
>         "symfony/dotenv": "^4.0",
>         "symfony/phpunit-bridge": "^4.0",
>         "symfony/thanks": "^1.0"
>     },
>     "config": {
>         "preferred-install": {
>             "*": "dist"
>         },
>         "sort-packages": true
>     },
>     "autoload": {
>         "psr-4": {
>             "App\\": "src/"
>         }
>     },
>     "autoload-dev": {
>         "psr-4": {
>             "App\\Tests\\": "tests/"
>         }
>     },
>     "replace": {
>         "symfony/polyfill-iconv": "*",
>         "symfony/polyfill-php71": "*",
>         "symfony/polyfill-php70": "*",
>         "symfony/polyfill-php56": "*"
>     },
>     "scripts": {
>         "auto-scripts": {
>             "cache:clear": "symfony-cmd",
>             "assets:install --symlink --relative %PUBLIC_DIR%": "symfony-cmd"
>         },
>         "post-install-cmd": [
>             "@auto-scripts"
>         ],
>         "post-update-cmd": [
>             "@auto-scripts"
>         ]
>     },
>     "conflict": {
>         "symfony/symfony": "*"
>     },
>     "extra": {
>         "symfony": {
>             "id": "01C2CSJMDMMQ60Y168268V92GW",
>             "allow-contrib": false
>         }
>     }
> }

**Comment by weaverryan** [comment]
Hi there!

What do you mean by “the script just exits whole process”. What error does the phpunit script cause? The phpunit script should not cause the process to fail - so there could be a bug in its recipe. Can you post you whole error and how to reproduce?

**Comment by przemyslawlib-blueveery** [comment]
I was trying to check opposite, installed symfony 3.2 which I assume do not have flex enabled, installed codeception but there was still no `bin/codecept` so I assume that bug exist in documentation of codeception. Binary from vendor folder do work.

So this issue can be closed as solved.

**Comment by weaverryan** [comment]
Cheers :)
