### ISSUE TITLE
Running `composer install --no-dev` removes changes introduced by dev dependency recipes

### ISSUE THREAD

**Issue by jaikdean** [symfony/flex#268]
After adding and installing dev dependencies with Flex recipes, subsequently running `composer install --no-dev` removes the dev packages as expected, but also reverts the changes made by the recipes in various version-controlled files and removes the package from `symfony.lock`. As far as I'm aware, `composer install` shouldn't affect any version-controlled files.

I checked with @Pierstoval who confirmed this isn't expected behaviour.

I have created a simple [test case](https://github.com/jaikdean/flextest) repository containing three commits:

* The first just adds a barebones `composer.json`.
* The second is the result of `composer update`.
* The third is the result of then running `composer install --no-dev`.

**Comment by Pierstoval** [comment]
Seems like Flex is removing recipes files when `composer install --no-dev` **removes** the dev packages.

Even though we can imagine that some files could _safely_ be removed, they're actually part of the project so I think this shouldn't happen 😕

**Comment by fabpot** [comment]
Indeed, that's not the correct behavior. Fixes by #324
