### ISSUE TITLE
composer should check for required extension `ctype`

### ISSUE THREAD

**Issue by docteurklein** [symfony/flex#269]
Hi! 
Nothing terrible, but I thought it would worth it to add an issue to not forget.

Currently getting this error: 

```
Fatal error: Uncaught Error: Call to undefined function Symfony\Flex\Configurator\ctype_digit() in /usr/src/app/example/sample-app/vendor/symfony/flex/src/Configurator/EnvConfigurator.php:47
Stack trace:
#0 /usr/src/app/example/sample-app/vendor/symfony/flex/src/Configurator/EnvConfigurator.php(25): Symfony\Flex\Configurator\EnvConfigurator->configureEnvDist(Object(Symfony\Flex\Recipe), Array)
#1 /usr/src/app/example/sample-app/vendor/symfony/flex/src/Configurator.php(52): Symfony\Flex\Configurator\EnvConfigurator->configure(Object(Symfony\Flex\Recipe), Array)
#2 /usr/src/app/example/sample-app/vendor/symfony/flex/src/Flex.php(235): Symfony\Flex\Configurator->install(Object(Symfony\Flex\Recipe))
#3 [internal function]: Symfony\Flex\Flex->update(Object(Composer\Script\Event))
#4 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(171): call_user_func(Array, Object(Composer\Script\Event))
#5 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(96): Composer\EventDispatc in /usr/src/app/example/sample-app/vendor/symfony/flex/src/Configurator/EnvConfigurator.php on line 47
/usr/src/app/example/sample-app #
```

**Comment by nicolas-grekas** [comment]
Or w could just add ext-ctype to its Composer.json

**Comment by docteurklein** [comment]
yes, that's what I meant with the title, sorry for the non-clarity :).

Sorry if it's the wrong place, but I also noticed that `ext-xml` was mandatory for `cache:clear` and some other stuff to work.
Should we add it too ? (this time in the appropriate package, not flex).

By the way, I noticed that this error left my fresh installation in an inconsistent, unrepairable way. It was missing the `bin` folder, but re-running `composer install` didin't do anything.

**Comment by nicolas-grekas** [comment]
would you mind sending a PR for ext-ctype on this repo?
for ext-xml, it's already in FrameworkBundle's composer.json
about the inconsistent state, that's something for Composer :)

**Comment by docteurklein** [comment]
I'm about to send a PR :)

Sorry I edited the comment, it's about `ext-dom`, not `ext-xml`.

**Comment by docteurklein** [comment]
maybe not the best place, but here is the stack trace for missing `ext-dom`:

```
In XmlUtils.php line 50:

  [RuntimeException]
  Extension DOM is required.


Exception trace:
 Symfony\Component\Config\Util\XmlUtils::parse() at /usr/src/app/example/sample-app/vendor/symfony/config/Util/XmlUtils.php:131
 Symfony\Component\Config\Util\XmlUtils::loadFile() at /usr/src/app/example/sample-app/vendor/symfony/dependency-injection/Loader/XmlFileLoader.php:380
 Symfony\Component\DependencyInjection\Loader\XmlFileLoader->parseFileToDOM() at /usr/src/app/example/sample-app/vendor/symfony/dependency-injection/Loader/XmlFileLoader.php:44
 Symfony\Component\DependencyInjection\Loader\XmlFileLoader->load() at /usr/src/app/example/sample-app/vendor/symfony/framework-bundle/DependencyInjection/FrameworkExtension.php:111
 Symfony\Bundle\FrameworkBundle\DependencyInjection\FrameworkExtension->load() at /usr/src/app/example/sample-app/vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php:71
```

The nearest package to add the requirement could be `symfony/config`, but I guess it's an "optional" dependency, only used if you load xml files?

**Comment by nicolas-grekas** [comment]
doesn't FrameworkBundle always use that code path?
if confirmed, then ext-dom could be added there

**Comment by xabbuh** [comment]
FrameworkBundle already [depends on `ext-xml`](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/composer.json#L20). Shouldn't that be enough?

**Comment by docteurklein** [comment]
it's `ext-dom` which is not checked.

**Comment by fabpot** [comment]
ctype is fixed now, for ext-dom, it's not from Flex, so closing it here.
