### ISSUE TITLE
Make yaml config files indent configurable

### ISSUE THREAD

**Issue by Soullivaneuh** [symfony/flex#274]
By default, any generated configuration file from recipe has a 4 space default indention.

If we have a project with 2 space indention, we always have to fix it manually.

Could you please consider to add an option for it?

**Comment by fabpot** [comment]
The coding standard for Symfony dictates 4 spaces for YAML files. If you need something else, you need to change the generates files manually or via a tool. We cannot make everything configurable. Moreover, Flex is opinionated :)

**Comment by Soullivaneuh** [comment]
> Moreover, Flex is opinionated :)

It would be quite bad to get rid of flex just for that. Is it too difficult to make it configurable?

**Comment by stof** [comment]
Well, it would require to implement a system processing files before dumping them (and a system to configure this processing on a per-type basis). Overkill IMO.

**Comment by fabpot** [comment]
@Soullivaneuh Let's put this into perspective: nobody should care about the indentation of a YAML file. 4 spaces for YAML is what we've been doing for years. Nobody ever complained about this choice. My point is that everybody should stick with the "default". Now, if you want to do something different, that's fine, but the burden is on you, not us.

**Comment by Soullivaneuh** [comment]
No problem @fabpot, I was just asking if the option could be implemented with ease or not. I have the answer, and yes, I'll maybe write a tool for that. :+1:

**Comment by Nek-** [comment]
@soullivaneuh did you do it? x)
