### ISSUE TITLE
Bundle not automatically registered on special library

### ISSUE THREAD

**Issue by Soullivaneuh** [symfony/flex#278]
Example with this one: https://packagist.org/packages/greg0ire/enum

The bundle class is here: https://github.com/greg0ire/enum/blob/9a3efcc042b6f0fc8a8562320a336b7dc4ba72cb/src/Bridge/Symfony/Bundle/Greg0ireEnumBundle.php

But this one is not added on `bundles.php`.

Two possibilities:

1. The bundle class namespace is different (`Greg0ire\Enum\Bridge\Symfony\Bundle`) and not found by flex
2. The package is not registered as a `symfony-bundle` on packagist. Because it is not necessarily a bundle, but provide a bridge to integrate it as a bundle.

If it's the option 2, the package type can not be changed because we can set multiple package types on composer.

What do you think?

Another reproducible sample packages:

- https://packagist.org/packages/sllh/iso-codes-validator
- https://packagist.org/packages/knplabs/doctrine-behaviors

**Comment by weaverryan** [comment]
I believe it's the second problem: that the type is not `symfony-bundle`.

@Soullivaneuh Can you solve it by creating a recipe and using the `bundles` configurator - https://github.com/symfony/recipes#bundles-configurator. I believe this is the proper answer. And if so, we should really make sure that the most popular bundles that have this situation are covered. I found another: the bundle inside AliceDataFixtures (https://github.com/theofidry/AliceDataFixtures/blob/master/src/Bridge/Symfony/FidryAliceDataFixturesBundle.php).

**Comment by fabpot** [comment]
If the package is not of type `symfony-bundle`, no auto-registration is done. In that case, you should submit a recipe (and we would then bypass the validation rule about the Composer type).
