### ISSUE TITLE
"Prefetching" does not respect composer authentication settings

### ISSUE THREAD

**Issue by naderman** [symfony/flex#284]
Even though I have authentication configured and everything works without flex, I get prompted for authentication on a private repository when I use flex.

```
$ composer install --ignore-platform-reqs
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 119 installs, 0 updates, 0 removals
  - Installing symfony/flex (v1.0.57): Downloading (100%)         

Prefetching 117 packages 🎶
  - Connecting     
    Authentication required (repo.packagist.com):
      Username:
```

**Comment by nicolas-grekas** [comment]
Fixed in 1.0.58 with #276, isn't it?

**Comment by nicolas-grekas** [comment]
Meanwhile, could you please have a look at
https://github.com/composer/composer/pull/6985
and 
https://github.com/composer/composer/pull/6979
?
I badly need them now :)

**Comment by naderman** [comment]
@nicolas-grekas ah sorry, I missed that issue ...

**Comment by naderman** [comment]
Ok, so update to 1.0.58 worked, but I had to manually delete the vendor folder first, to force flex to reinstall before the prefetch process. 

I guess it's a bit of an issue if the plugin itself tries to execute anything before the plugin itself gets updated ^_^

**Comment by fabpot** [comment]
Closing as it seems to be fixed now.
