### ISSUE TITLE
Improve workflow when not using Env vars

### ISSUE THREAD

**Issue by apfelbox** [symfony/flex#287]
Hi 👋 

we are currently migrating to Flex and have encountered a small DX issue. I currently don't have a nice proposal, but just wanted to point out that there might be an area to improve.

If you are not using env variables, the `EnvConfiguration` command currently just bails out:
https://github.com/symfony/flex/blob/9f2d70e7ab263473be95bb1ec55d42418b5f15e5/src/Configurator/EnvConfigurator.php#L35-L38

In this case though, the information about which configuration parameters (in form of env variables or `env(VAR): value` in your `parameters.yaml`) the bundle expects is just lost:

![2018-01-11 at 17 44](https://user-images.githubusercontent.com/1032411/34836124-31afc3e2-f6f7-11e7-9a59-bdf3c63d14c2.png)

I am not sure about how to improve the situation except printing a message like:

> Hey, this bundle needs some env variables. This is what we would have added to your `.env.dist` file, but since you don't have one, you have to add these parameters yourself: [... print `manifest.json["env"]` ...]

So currently you have to hunt down the recipe manually in Github (potentially search the correct version), look at the `manifest.json` and proceed from there. This might be improved by just printing the already available info to the CLI in the installation process?

What do you think?

**Comment by Pierstoval** [comment]
I think it's just about a few lines of code in the EnvConfigurator, so I'd say: submit a PR, it sounds nice 👍

**Comment by fabpot** [comment]
I think that *not* using a `.env.dist` is not supported. We make it so that it's possible, but that's definitely not a use case I want to support. If you don't have a `.env.dist` file, for whatever reasons, you are on your own. Keep in mind that Flex is flexible BUT opinionated.

**Comment by Pierstoval** [comment]
As it's not supported, I think it's a good reason to show a warning to the user telling him/her to either create the file, or be warned that env vars defined by recipes won't be usable if he/she does not set it.

**Comment by apfelbox** [comment]
@fabpot our issues with parameters as env vars is that we just have to many. 
We need to duplicate them around multiple entry points in nginx, we need to copy them in the deploy script and every bin/console call is prepended with around 10 env vars. That is not very comfortable and quite error prone. 

Is there a better way to do this? I am very thankful for every tip, as I really have no idea on how to improve this. 

What is the performance impact of DotEnv in production? It will be slower than compiled-in parameters, but is it significant? One file access and some parsing?

**Comment by javiereguiluz** [comment]
@apfelbox I agree that repeating each env var in so many places (.env, .env.dist, phpunit.xml, console commands, your web server, etc.) is not nice. We are at least trying to remove the phpunit repetition (see #251).

**Comment by fabpot** [comment]
I don't have a definitive answer but some hints:

* First, no everything should be an env vars. I'm trying to reduce the number of env vars to the strict minimum. Most configs do not need to be env vars.

* With Symfony 3.4, you can store most things in a file that is exposed as 1 env var. Can be nice.

* Performance is not that significant, not using DotEnv in prod is more like a "good practice" than anything else. If you want to use it in prod, I don't think it will kill your server :)

**Comment by Pierstoval** [comment]
Once env vars are set in the virtual host of your nginx / apache instance, it's not needed to repeat it.
Same for the command-line: of course you will have to duplicate the same config, but you can put it in either `/etc/environment` or `/etc/profile` or in `/etc/profile.d/your_file.sh`.

**Comment by apfelbox** [comment]
@Pierstoval 
> Once env vars are set in the virtual host of your nginx / apache instance, it's not needed to repeat them.

Hmm, can't really confirm that:

```nginx
#fastcgi_param TEST "test123";     # <- does not work
location /app.php {
    include php-fpm.conf;
    fastcgi_param TEST "test123";  # <- does work

    fastcgi_pass php7.2-testproject;
}
```

So I either have to repeat them for every entry point or have to create a new include file for every project.

> [...]you can put it in either `/etc/environment` or `/etc/profile` or in `/etc/profile.d/your_file.sh`.

That is true, doesn't work however in shared hosting environments. We have quite a few projects on the same server (they are too small for an own VM) so I would need to manually source different files then. Also calling `bin/console` in a script becomes "difficult" too.

@fabpot thank you for your input.

> Most configs do not need to be env vars.

How do you define the config, that doesn't need to be env vars, but differs between the servers? Do you still have a `parameters.yaml` around?

> With Symfony 3.4, you can store most things in a file that is exposed as 1 env var. Can be nice.

Exposing it as 1 file is quite nice (by using the `env()` prefixes as described [here](https://symfony.com/blog/new-in-symfony-3-4-advanced-environment-variables)) but this version leads to having one huge `app.config` blob with an arbitrary structure. By using different, specific `app.config.db_url` (etc...) I have a small sense of security that these parameters must be defined.

Is it possible to destructure env vars, something like (don't mind the concrete syntax please):

`services.yaml`
```yaml
parameters:
    app.config.db: `%env(json:file:CONFIG_FILE).db%`
    app.config.secret: `%env(json:file:CONFIG_FILE).secret%`
```

? 

That could be a nice integration to combine the best of both worlds.
(It would need to error early if the destructuring fails)

**Comment by Pierstoval** [comment]
> How do you define the config, that doesn't need to be env vars, but differs between the servers? Do you still have a `parameters.yaml` around?

You can still use one if you need. It was previously handled by [incenteev/composer-parameter-handler](https://github.com/Incenteev/ParameterHandler), and you can still use it even with Flex if you need fils.



> Exposing it as 1 file is quite nice (by using the `env()` prefixes as described here) but this version leads to having one huge `app.config` blob with an arbitrary structure. By using different, specific `app.config.db_url` (etc...) I have a small sense of security that these parameters must be defined.

This is where you can take advantage from extensions or compiler passes: you can retrieve this array and pass it through a `Configuration` class, or make manual checks, to validate the config structure at compile time, or store this configuration in a service that will check it at runtime, possibly making a checksum of it before, to know if it's possible to retrieve it from cache and reduce the amount of env processing at runtime… Plenty solutions, actually.

At compile time, you can even split it and insert it in the container afterwards with something like `foreach ($config as $key => $value) { $container->setParameter('config.'.$key, $value); }`.

Hope this helps

**Comment by nicolas-grekas** [comment]
Closing as this improved a lot recently, with https://github.com/symfony/recipes/pull/501 as the last step.
