### ISSUE TITLE
No matching package found.

### ISSUE THREAD

**Issue by salihevrendemir** [symfony/flex#289]
symfony/flex v1.0.9 requires composer-plugin-api ^1.1 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by xabbuh** [comment]
You need to update your version of Composer as the one you are using right now is too old. If you are using a version of Composer that was shipped with your Linux distribution, you may need to install Composer manually [as described in the documentation](https://getcomposer.org/doc/00-intro.md#installation-linux-unix-osx).

**Comment by salihevrendemir** [comment]
composer version problem. closed please
