### ISSUE TITLE
Flex installs recipes in unattended `composer install` on CI

### ISSUE THREAD

**Issue by Majkl578** [symfony/flex#290]
Running `composer install --no-interaction` causes Flex to install and configure recipes. This is unacceptable on CI server, it installed unwanted recipes and broke whole build.

Just upgraded to 1.0.61.
I do not have `symfony.lock` because it was always created with empty empty (`[]`) anyway. Even after upgrading all Symfony packages from 3.3 to 4.0.
Granted, Flex is probably confused by `symfony.lock` absence, but in such case it should not install all recipes during `composer install`.

Edit:
Workaround: Running `composer install` locally generates the lock file, but breaks the app since it configures all recipes (even those violating semver). But at least the lock file can be picked up and other changes reverted.

**Comment by fabpot** [comment]
Having a project without a `symfony.lock` is not supported anymore. This file is how we know if recipes should be installed or not. There is no way around it. You should update your project to get the `symfony.lock` file.

**Comment by raziel057** [comment]
@fabpot Is it a good practice to modify the symfony.lock file to remove the recipe? Because all demo files that are created from a recipe are not expected to be generated when installing the dependencies on CI servers or in production.

For example: https://github.com/symfony/recipes/issues/450

**Comment by fabpot** [comment]
No, you should not modify the `symfony.lock` file. If you want to remove the side-effects of a recipe, just remove the files and rollback the config, but keep the entry in `symfony.lock`. That way, Flex wonn't try to reinstall the recipe next time you run composer update.
