### ISSUE TITLE
Recipe is not auto-generated for symfony-bundle from recipes-contrib

### ISSUE THREAD

**Issue by covex-nn** [symfony/flex#291]
When user answer 'n' on a question about `symfony-bundle` from recipes-contrib

```php
$question = '    The recipe for this package comes from the "contrib" repository, which is open to community contributions.
    Do you want to execute this recipe?
    [<comment>y</>] Yes
    [<comment>n</>] No
    [<comment>a</>] Yes for all packages, only for the current installation session
    [<comment>p</>] Yes permanently, never ask again for this project
    (defaults to <comment>n</>): ';
```

.. then `symfony-bundle` will not be registered in `config/bundles.php` (recipe will not auto-generated).

Right now the answer will be always 'n', because of https://github.com/symfony/flex/issues/285, and symfony bundles from recipes-contrib will not be registered in `config/bundles.php` when `extra.symfony.allow-contrib` is false.

**Comment by covex-nn** [comment]
@fabpot to fix this issue, i tried to replace

```php
if ('n' === $answer) {
    continue;
}
```
... with ...

```php
if ('n' === $answer) {
    if ('symfony-bundle' == $recipe->getPackage()->getType()) {
        $recipe = new Recipe($recipe->getPackage(), $recipe->getName(), $recipe->getJob(), [
            'manifest' => [
                'bundles' => $recipe->getManifest()['bundles']
            ],
            'origin' => sprintf('%s:%s@auto-generated recipe', $recipe->getName(), $recipe->getPackage()->getPrettyVersion())
        ]);
    } else {
        continue;
    }
}
```
... in `Symfony\Flex\Flex::update` to replace _contrib_ recipe with _auto-generated_ one.

But there is another problem: after removing such package, all files from _contrib_ recipe will be removed too (if they were created after installing a package). I do not know if this is acceptable.

**Comment by stof** [comment]
hmm, this would require remembering in the symfony.lock that the recipe used for installation was the auto-generated one (and so the removal should only unregister the bundle). What do you think @fabpot ?

**Comment by nicolas-grekas** [comment]
Anyone willing to make this happen? PR welcome.
