### ISSUE TITLE
Contrib recipes are being ignored automatically

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/flex#295]
At the beginning of Symfony Flex, contrib recipes were ignored. Then Fabien changed it to ask you whether you want to install or ignore contrib recipes. But now it looks like we are ignoring them again.

I run this:

```
$ composer create symfony/skeleton my_project
$ cd my_project/
$ composer require nelmio/api-doc-bundle
```

And this is the result:

![nelmio-recipe-ignored](https://user-images.githubusercontent.com/73419/34953395-fbb9e9ec-fa1c-11e7-9deb-eebd245f9b59.png)

Is this behavior change intended?

**Comment by Pierstoval** [comment]
It's related to #285 IIUC
