### ISSUE TITLE
create a command to run missing recipes

### ISSUE THREAD

**Issue by SimonHeimberg** [symfony/flex#297]
Add a command like `composer flex-install`, which checks if the recipes have run for all installed packages. (It checks which packages are in composer.lock but not in symfony.lock)
Alternative: `composer install` runs the missing recipes.

Use cases:
* When the connection is broken while running composer, the installation is done by composer (maybe from cache), but the recipes are not run.
* When [upgrading existing application to flex](http://symfony.com/doc/current/setup/flex.html#upgrading-existing-applications-to-flex).

Work-around:
Delete the dependencies in vendor/, then run `composer install`.

**Comment by fabpot** [comment]
Implemented in #338
