### ISSUE TITLE
Dev packages get unpacked to no-dev section

### ISSUE THREAD

**Issue by vudaltsov** [symfony/flex#302]
After running `composer unpack symfony/profiler-pack`:

![image](https://user-images.githubusercontent.com/2552865/35120279-a8271c58-fca8-11e7-8cbc-3389dbcd90b9.png)

**Comment by fabpot** [comment]
I'm not able to reproduce the bug. It's been fixed already or there is something about your project I don't know about. In any case, feel free to reopen with a way to reproduce if that's still an issue for you. Thanks.

**Comment by vudaltsov** [comment]
@fabpot , here's how you can reproduce it:

```bash
composer create-project symfony/website-skeleton test-unpack-dev
cd test-unpack-dev
composer unpack symfony/profiler-pack
```

The `symfony/profiler-pack` package is initially in the `require-dev` section. So after running the `unpack` command I expect it to be unpacked into the `require-dev` section. But it actually gets unpacked to `require`.
