### ISSUE TITLE
Command "unpack" is not defined

### ISSUE THREAD

**Issue by RobertClasen** [symfony/flex#307]
After running `composer require debug`, when I run `composer unpack debug` I get:

```
[Symfony\Component\Console\Exception\CommandNotFoundException]
Command "unpack" is not defined.
```

**Comment by xabbuh** [comment]
Are you using the Composer version that is shipped with Ubuntu? Its Composer version is 1.0 which does not allow to use the `unpack` command (see #303). Try installing Composer as a phar like described in https://getcomposer.org/doc/00-intro.md#installation-linux-unix-osx.

**Comment by RobertClasen** [comment]
@xabbuh I'm on macOS 10.13.2 and Composer is installed [globally](https://getcomposer.org/doc/00-intro.md#globally):

```
$ which composer
/usr/local/bin/composer

$ composer --version
Composer version 1.6.2 2018-01-05 15:28:41
```

**Comment by xabbuh** [comment]
You are right. I was able to reproduce. You can downgrade Flex to 1.0.64 as a workaround for now.
