### ISSUE TITLE
CURLMOPT_MAX_HOST_CONNECTIONS not supported on older versions

### ISSUE THREAD

**Issue by PohlmanUSA** [symfony/flex#311]
When I was installing a new Symfony project on a CentOS VM, I got the following error:
                                                                                                                                                           
    [ErrorException]
    Use of undefined constant CURLMOPT_MAX_HOST_CONNECTIONS - assumed 
    'CURLMOPT_MAX_HOST_CONNECTIONS' (this will throw an Error in a future version of PHP)  
                                                                                                                                                           
Doing some digging I found that RHEL only offers cURL 7.29. This constant was only added in version 7.30.

I'm not sure if Flex needs to include a composer requirement of lib-curl ^7.30 or if there is a work around for older versions of the cURL library.

**Comment by nicolas-grekas** [comment]
We could just skip the line using this constant in this situation, it would still work. Would you mind sending a PR?

**Comment by PohlmanUSA** [comment]
https://github.com/symfony/flex/pull/312
