### ISSUE TITLE
Cannot declare class Symfony\Flex\ScriptExecutor Exception

### ISSUE THREAD

**Issue by vudaltsov** [symfony/flex#313]
![image](https://user-images.githubusercontent.com/2552865/35689545-d98d3908-0784-11e8-87e1-770e37ff7d4e.png)

**Comment by vudaltsov** [comment]
It looks like this issue takes place only when installing to parent directory with `../`.

If I do `cd ../ && composer create-project symfony/skeleton testskeleton` everything is okay.

**Comment by jakzal** [comment]
Could it be related to #243?

**Comment by vudaltsov** [comment]
@jakzal , looks like it is

**Comment by fabpot** [comment]
This only happens if the current directory is a Symfony project. I would say that this is an edge case. If someone wants to invest time fixing this, I would be more than happy to accept a pull request, but this is very low priority for me. Closing for now.
