### ISSUE TITLE
Lock file not up to date on new Symfony project

### ISSUE THREAD

**Issue by derrabus** [symfony/flex#316]
To reproduce this issue, simply create a new project and run `composer install` afterwards.

```sh
composer create-project symfony/skeleton demo
cd demo
composer install
```

Composer will issue a warning, stating that the lock file is outdated.

> Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.

This is a bit unexpected since composer has just installed my dependencies and created the lock file from it.

If I run `composer update` afterwards, composer only updates the `content-hash` property.

**Comment by teohhanhui** [comment]
This is because the `extra.symfony.id` is updated. Very unexpected and a bad thing to do outside of composer update / require (things that you'd expect to modify the state). This should be considered a bug.

**Comment by teohhanhui** [comment]
It also has consequences for downstream distributions based on Symfony Flex. For example in https://github.com/api-platform/api-platform, we're forced to pass `SYMFONY_SKIP_REGISTRATION` to every `composer` command, e.g.

```shell
SYMFONY_SKIP_REGISTRATION=1 composer validate --no-check-publish
```

**Comment by sstok** [comment]
If the registration is not mandatory maybe add a command to create a new registration id rather then always registering the user?
