### ISSUE TITLE
Quote inconsistency between env vars in phpunit.xml.dist and .env

### ISSUE THREAD

**Issue by weaverryan** [symfony/flex#317]
https://github.com/symfony/recipes/pull/361 created an interesting issue :).

After this change, `.env` looked like this:

```
DATABASE_URL='mysql://root:@127.0.0.1:3306/test_maker'
```

(it used double quotes before). BUT, this broke `phpunit.xml.dist`, which now looks like this:

```
<env name="DATABASE_URL" value="'mysql://root:@127.0.0.1:3306/test_maker'"/>
```

The extra single quotes become part of the value. 

I'm proposing that we revert https://github.com/symfony/recipes/pull/361 in https://github.com/symfony/recipes/pull/363. 

I'm not sure how to fix this. Sometimes, you *do* want double-quotes - so you can have `\n` and other things. But many times, we want the user to have single quotes. Perhaps we should *always* use single quotes in the recipes? And the user can change to double if they want? I could open a PR - I just wasn't sure at first.

**Comment by fabpot** [comment]
Indeed, 361 is wrong. Flex (the latest versions) manages the escaping automatically depending on the context. So, there is nothing to "fix". If that does not work correctly, then it's a bug that needs to be corrected.

**Comment by stof** [comment]
Well, the thing is, at the time Flex sets the default value for the DATABASE_URL, it will consider that the escaping is unnecessary. But when people change their .env file to put their actual credentials, they may face issues with the `$` in their password, which gets expanded as a variable.

Btw, I'm not even sure Flex properly escapes env variables containing a `$`

**Comment by stof** [comment]
An option could be to have Flex *always* single-quoting values in .env, and letting people wanting variable expansion unquote values (or switch to double quote), instead of breaking things for all people not even knowing that Dotenv performs such expansion.

**Comment by weaverryan** [comment]
I was thinking the same thing

**Comment by nicolas-grekas** [comment]
Use `.env.test` instead, see https://github.com/symfony/recipes/pull/481
