### ISSUE TITLE
Set multiple namespaces to use old bundles in Symfony4

### ISSUE THREAD

**Issue by SlimenTN** [symfony/flex#320]
This is my question on stackoverflow https://stackoverflow.com/questions/48849982/symfony-4-the-autoloader-expected-class-to-be-defined-in-file
As you can see I wanted to use an old Bundle but it's not working even tho I did changed the `composer.json` file to work with the new namespace.
And as conclusion is it possible to add old bundles (without installing them via composer) with **their default namespaces**, or I should change them all and add `App/` to make them work ?

**Comment by fabpot** [comment]
You don't need to change the namespace of your existing bundles. As long as you register the namespace in composer.json, that will work (like any other third party bundle actually).
