### ISSUE TITLE
Unable to install SF4 behind a proxy

### ISSUE THREAD

**Issue by xabbuh** [symfony/flex#328]
From symfony/symfony#26353:

Hi,

I don't know if it's a composer issue or a SF4 issue, but I think it's Symfony because, lastest version of SF3 install fine with composer. 

HTTP_PROXY and HTTPS_PROXY are correctly filled in system variables environnement of my Windows 7. I also set these variables in bash environnement (MINGW64).
Composer was updated to the lastest version.

When I execute the first command of the symfony setup documentation : composer create-project symfony/website-skeleton my-project , the 2 first libraries dowload and install fine (ocramius/package-versions (1.2.0) and symfony/website-skeleton (v3.4.4)), but the third ( symfony/flex (v1.0.70)) give me the following network error : 

  [Composer\Downloader\TransportException]
  The "https://symfony.sh/ulid" file could not be downloaded: failed to open
  stream: Cannot connect to HTTPS server through proxy

It's strange because everything work fine with SF3.

**Comment by nicolas-grekas** [comment]
@Isarien would you be able to debug the issue?

**Comment by nicolas-grekas** [comment]
Ping @andreybolonin @Lisarios also as you reacted to the issue: could you answer these questions if you experience the issue?

**Comment by Isarien** [comment]
@nicolas-grekas Yes I will try.

**Comment by Isarien** [comment]
@nicolas-grekas : I am trying to debug  :D

**Comment by Isarien** [comment]
**php --ri openssl** : 

`openssl

OpenSSL support => enabled
OpenSSL Library Version => OpenSSL 1.1.0h  27 Mar 2018
OpenSSL Header Version => OpenSSL 1.1.0h  27 Mar 2018
Openssl default config => C:\usr\local\ssl/openssl.cnf

Directive => Local Value => Master Value
openssl.cafile => no value => no value
openssl.capath => no value => no value
`
**php --version** : 
`PHP 7.2.4 (cli) (built: Mar 28 2018 04:27:01) ( ZTS MSVC15 (Visual C++ 2017) x64
 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Xdebug v2.6.0, Copyright (c) 2002-2018, by Derick Rethans
`
When I execute composer from  source, it seems a little more vebose. Now the error message is :+1: 
`Plugin installation failed, rolling back
  - Removing symfony/flex (v1.0.78)

                                                                               
  [Composer\Downloader\TransportException]                                     
  The "https://symfony.sh/ulid" file could not be downloaded: curl_setopt():   
  CURLOPT_DNS_USE_GLOBAL_CACHE cannot be activated when thread safety is enab  
  led                                                                          
  curl_setopt(): cannot represent a stream of type MEMORY as a STDIO FILE*     
`

And the var_dump of stream_context_get_params($ctx) : 
`array(2) {
  ["http"]=>
  array(7) {
    ["follow_location"]=>
    int(0)
    ["max_redirects"]=>
    int(20)
    ["proxy"]=>
    string(24) "tcp://url.my.proxy:3130"
    ["request_fulluri"]=>
    bool(true)
    ["header"]=>
    array(5) {
      [0]=>
      string(49) "Package-Session: d033f0c7c2516ba0caadaf2472fd2c0a"
      [1]=>
      string(21) "Accept-Encoding: gzip"
      [2]=>
      string(17) "Connection: close"
      [3]=>
      string(47) "Proxy-Authorization: Basic b2ZsOkAyOVkxMzc5aUA="
      [4]=>
      string(56) "User-Agent: Composer/source (Windows NT; 6.1; PHP 7.2.4)"
    }
    ["protocol_version"]=>
    float(1.1)
    ["ignore_errors"]=>
    bool(true)
  }
  ["ssl"]=>
  array(7) {
    ["SNI_enabled"]=>
    bool(true)
    ["ciphers"]=>
    string(714) "ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA"
    ["verify_peer"]=>
    bool(true)
    ["verify_depth"]=>
    int(7)
    ["capture_peer_cert"]=>
    bool(true)
    ["cafile"]=>
    string(70) "D:\wamp64\www\composer\vendor\composer\ca-bundle\src/../res/cacert.pem"
    ["disable_compression"]=>
    bool(true)
  }
}
` 
I replace the url of my proxy by url.my.proxy

**Comment by Isarien** [comment]
Hi,

Did you change something ? Now it works.

I think the issue can be closed.

Thanks

Olivier

**Comment by nicolas-grekas** [comment]
Thanks for the feedback, closing therefor.
If someone else experiences the issue, we can reopen.
