### ISSUE TITLE
Remove swiftmailer-bridge or show it's deprecated.

### ISSUE THREAD

**Issue by frankdejonge** [symfony/flex#340]
Right now when you visit symfony.sh and search for "mail" the first non-contrib hit is the deprecated bridge. If people don't investigate further (and a lot of people won't) they'll be installing a deprecated package. It would be good to know when/if a package is deprecated (we could even use the packagist API for this).

**Comment by Pierstoval** [comment]
The package is abandoned, so if it's installed, Composer itself will say it in the terminal output

**Comment by frankdejonge** [comment]
@Pierstoval while that's true, it's not a great experience. Why show it to people when we want them to stop using it in the first place?

**Comment by fabpot** [comment]
I've removed all abandoned packages (class-loader, locale, propel1-bridge, and swiftmailer-bridge).

**Comment by frankdejonge** [comment]
Thank you, @fabpot! 🤘
