### ISSUE TITLE
[Question] What is the `id` in `composer.json`?

### ISSUE THREAD

**Issue by c33s** [symfony/flex#350]
composer.json contains a id in the extra -> symfony section. 
```
extra:
    symfony: { id: XXXX, allow-contrib: false }
```
it feels a little bit like a tracking id. what is it used for? can we disable it? `false` leads to a new id.

**Comment by Pierstoval** [comment]
It's used for Flex-based applications stats IIRC

**Comment by c33s** [comment]
opt-in/opt-out would be a good thing.  GDPR/DSGVO https://www.eugdpr.org/

personally i would prefer opt-in like debian is doing it. 
the installer asks if i want to install the statistics package `popularity-contest` and i can choose not to.
https://packages.debian.org/search?keywords=%20popularity-contest&searchon=names&suite=all&section=all
and the statistics are public
https://popcon.debian.org/

**Comment by Pierstoval** [comment]
I think @fabpot can give you a lot more info about this subject 😉

**Comment by fabpot** [comment]
@Pierstoval Please do NOT comment when you don't know. Giving some wrong info is really bad.

The `id` is only used for private repositories, that's all. You can opt-out easily by just removing the value (setting the value to an empty string).

**Comment by c33s** [comment]
... and thanks for clearification

**Comment by fabpot** [comment]
My bad. The way to avoid the id generation is to simply remove the entry.

See https://github.com/symfony/flex/blob/master/src/Flex.php#L567
