### ISSUE TITLE
[Question] Should we improve discoverability of binaries?

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/flex#36]
The scenario is:

* I install a new package in my app
* The package contains some binaries that installs in bin/ or vendor/bin/

The problem is:

* How can I possibly know that the package installed those binaries? Maybe I'm missing some great script/command.

The possible solutions:

* Add a 1-line message for each installed binary. E.g.: `// added bin/check.php`
* Do nothing and rely on people reading the package docs or looking into bin/ dir themselves.

**Comment by fabpot** [comment]
Closing this one as I think this should just be part of the docs of the installed package. Flex should not be a substitute for proper documentation.
