### ISSUE TITLE
Unpacking should intersect constraint when there is already one

### ISSUE THREAD

**Issue by stof** [symfony/flex#370]
See https://github.com/ro0NL/sf-project/commit/b204330a1f053f530b930bf8710dd36cdca5e85e

When having a root constraint for a package and unpacking with another constraint on the same package, we cannot just use the constraint for the pack. We need to take the intersection of both constraints.

**Comment by stof** [comment]
And the same is true for conflict rules (after fixing https://github.com/symfony/flex/issues/371), but using the union of ranges (which is easier, as you can simply join both constraints with `||`, even if it may not be the simpler constraint)

**Comment by ro0NL** [comment]
Just got the same

```diff
-        "symfony/validator": "^4.1",
+        "symfony/validator": "^3.0 || ^4.0",
```

**Comment by stof** [comment]
Well, for requirements, skipping might be an option (even though it might still create issues by broadening the constraint). But for conflict rules, it would end up with missing conflicting versions.

**Comment by nicolas-grekas** [comment]
Closing in favor of https://github.com/symfony/flex/issues/645

**Comment by nicolas-grekas** [comment]
Reopening since the logic in place didn't work as expected and was reverted in #695
See also #694

Help wanted.

**Comment by nicolas-grekas** [comment]
Closing as there is little incentive to work on this.
PR welcome when this incentive is high for you.
