### ISSUE TITLE
Unpacking does not support conflict rules

### ISSUE THREAD

**Issue by stof** [symfony/flex#371]
When unpacking a pack, conflict rules are not unpacked, which might create a different result if there was any.

**Comment by nicolas-grekas** [comment]
When a conflict rule in a pack conflicts with an existing conflict rule in the main composer.json, we would ideally compute the union of both conflicting rules.

**Comment by nicolas-grekas** [comment]
Copy/pasting from https://github.com/symfony/flex/issues/645#issuecomment-655677296:
> About skipping conflicts, that might be unneeded actually: when packs are installed, the conflicts are taken into account. Now that #651 locks the major version of installed packages when unpacking, this kinda freezes the resolved conflicts. Of course, it's always possible that removing the conflicts will yield a different solution after unpacking, but the window becomes quite narrow. Maybe narrow enough to close #371 and save us from spending time on this.

**Comment by nicolas-grekas** [comment]
Closing as there is little incentive to work on this.
PR welcome when this incentive is high for you.
