### ISSUE TITLE
Configurable src>App directory to namespace mapping

### ISSUE THREAD

**Issue by MetalArend** [symfony/flex#374]
After all these years, most would consider the src directory somehow the default directory to put your classes. And then Flex introduces the `src` > `App` mapping. Updating an old project, one of the first things I would have to do is change the namespace of all the files available in the `src` directory. Or create another directory which would not be the `src` directory to put all files in. 

Luckily, fixing this is not that hard to do: change the `config/services.yml` and `composer.json` files.

However, once you start installing recipes, they still consider the link between the src directory and the `App` namespace a given. The `config/routes/annotations.yml` file expects the Controller directory to be always in the `src` directory. Take a look at the Doctrine recipe, they simply copy files to the `src` directory, and consider that directory available at the `App` namespace in their configuration. I'm quite sure this assumption is used in more recipes. It feels wrong to introduce an assumption like that, without making it an option that can be configured.

If the idea of Flex is installing new dependencies with less boilerplate code to set up, it's a strange thing to do it this way. I would rather have a recipe introduce less code and let me type more, than introduce code with the wrong assumptions in my project, and I have to go look for all the wrong mappings.

Could we introduce some configuration variable (in the extra section in `composer.json`) to tell which location to use for the `App` namespace? Or even better, make it possible for Flex to use the `composer.json` mapping? It might also be an improvement to let recipes have their files in the default directory structure, but map those files to the actual mapping when running the recipe? And have placeholders in the files, which can be replaced with the actual mapping.

**Comment by slootjes** [comment]
This is already discussed: https://github.com/symfony/flex/issues/196

**Comment by Pierstoval** [comment]
One of the tickets was closed by Fabien saying he's not ok with the feature but PRs are accepted and will gladly be reviewed.

This means that you can make a PR to Flex.

But just to say, if the `App` namespace becomes configurable, it means that **every** recipe referring to this namespace must be updated with the new system. Not a "simple" update about a `composer.json` rule...

**Comment by MetalArend** [comment]
I would consider that a good thing. You have to be backwards compatible, not "all the newest features should always be fully integrated" compatible. But then again, I am far more hesitant to change the flex code than to update all the recipes to be enhanced. :)

**Comment by nicolas-grekas** [comment]
Having it configurable would make it much harder to ship recipes - as eg you'd expect Kernel.php to use your namespace. That'd mean we would have to deal with file *templates*. Then the possibility would be forwarded to maker bundle where you'd expect the same configurability.

That's a lot of complexity to add for something you can achieve on your own using your IDE of a sed script most of the time.

:-1:
