### ISSUE TITLE
[RFC] Add support for Flex Hooks in recipes

### ISSUE THREAD

**Issue by Pierstoval** [symfony/flex#376]
I was thinking about the Composer scripts API: just provide a callable, and the script is executed after a special composer event.
 
For Flex, we already have configurators but they are based on the code in Flex itself + the JSON config in the recipes.

What about adding a special `hooks.php` file that would be here to customize the recipe's behavior with PHP code instead of plain JSON, but only for install & remove? (contrary to composer scripts that have many more events)

This could be done by making this file return a callable implementing a special interface in the Flex project that would define `installPackage()` and `removePackage()`, which can be achieved with an [instance of an anonymous class](https://secure.php.net/manual/en/language.oop5.anonymous.php) for example:

```php
// acme/my-package/1.0/hooks.php
return new class implements RecipeHook {
    public function installPackage() {
        // Do my stuff on install
    }
    public function removePackage() {
        // Do my stuff on removal
    }
};
```

This way, some packages may change the recipe's files on-the-fly before they are added to the project, such as FOSUserBundle that needs the ORM's driver (in this case, the hook would simply, on install, retrive Doctrine's config and retrieve the name of the entity manager or possibly the driver).

WDYT?

**Comment by nicolas-grekas** [comment]
Closing as staled.
