### ISSUE TITLE
[Question] Why are Composer extra options modified?

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/flex#38]
I was documenting the `manifest.json` format of Flex recipes and I found confusing that the special variables are `%BIN_DIR%`, `%CONF_DIR%`, etc.  instead of their original names `%bin-dir%`, `%conf-dir%`. The same goes for your custom variables defined in the `extra` section of `composer.json`.

Is there any good reason to do this? Otherwise, I'd recommend to keep those variables unchanged because:

* It lowers the learning curve (I don't have to learn that to use `bin-dir` I must use instead `BIN_DIR`)
* It doesn't mangle the original var names (if a developer wants to use `mY-BiN-dIr` we should let them do that instead of lowercasing or uppercasing it ... to avoid the problems we had in Symfony when forcing lowercase service ids)
* Uppercasing them makes them look like env vars ... but they are not env vars.

**Comment by xawiers** [comment]
I agree.
in extra I must use "web-dir" to overwrite WEB_DIR. And at first sight they are totally different names.
So better to stick to one naming.
Another thing that was weird - flex should at least write info message what's replaced value of %WEB_DIR% in info messages. I didn't understood at first that this was replaced in internal command execution process to "web".
Maybe something like one of these
```
Executing script assets:install --symlink --relative %WEB_DIR% ("web") [OK]
Executing script assets:install --symlink --relative web (%WEB_DIR%) [OK]
Executing script assets:install --symlink --relative web [OK] (%WEB_DIR% => web)
```

**Comment by fabpot** [comment]
Closing as there is no more activity here.
