### ISSUE TITLE
Repository type is not registered - v1.0.81

### ISSUE THREAD

**Issue by ArthurHoaro** [symfony/flex#382]
The latest release seems to break [custom repositories](https://getcomposer.org/doc/05-repositories.md#vcs) feature in `composer.json`.

Step to reproduce:

Add this in your `composer.json`: 
```
"repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/0x46616c6b/monolog"
        }
    ],
```

Then run `composer update`.

Expected result: the update run properly

Actual result: 
```
Loading composer repositories with package information                                                                                                                         Updating dependencies (including require-dev)         
Package operations: 74 installs, 0 updates, 0 removals
  - Installing symfony/flex (v1.0.81): Loading from cache
Plugin installation failed, rolling back
  - Removing symfony/flex (v1.0.81)

                                          
  [InvalidArgumentException]              
  Repository type is not registered: vcs  
```

The update works fine if I manually set `symfony/flex` to v1.0.80.

composer v1.6.5
PHP 7.2.7

**Comment by malukenho** [comment]
Same problem here. I just locked on `v1.0.80` as well, and it worked fine.

**Comment by dpeuscher** [comment]
Same here

**Comment by chubidu** [comment]
Same problem here, expect I'm getting this error with `"type": "path"`

`Repository type is not registered: path`

**Comment by andre-qup** [comment]
Same problem here. It will actually happen with any private repo "type".  Seems that 1.0.81 is upping symfony/cache Minor version and looking at flex 1.0.81 actual code changes I see nothing that can cause this - might be the cache repo breaking it.

**Comment by fabpot** [comment]
I've just released 1.0.82 (which is the same as 1.0.80) as a hotfix.

**Comment by xabbuh** [comment]
should be fixed with #384

**Comment by karousn** [comment]
+1

**Comment by fabpot** [comment]
v1.0.83 is out with a fix, can you test and report?

**Comment by malukenho** [comment]
@fabpot I've tested it. It is okay now. 🙇
