### ISSUE TITLE
flex not working

### ISSUE THREAD

**Issue by serjoagronovba** [symfony/flex#383]
PHP Fatal error:  Uncaught Error: Function name must be a string in vendor\symfony\flex\src\ParallelDownloader.php:246

cant do anything with composer, like require, installl and etc
php 7.2.7
xampp windows 10
it happens immidiatly after i install the skelton/skelton via composer create-project
even if i require flex manually, without the composer create-project, it does the same issue

**Comment by fabpot** [comment]
I've just released 1.0.82 (which is the same as 1.0.80) as a hotfix.

**Comment by fabpot** [comment]
closing as a duplicate of #381
