### ISSUE TITLE
Disable PHP's garbage collection?

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/flex#386]
I was testing the great performance improvements made by Nicolas with this command:

```
composer create symfony/skeleton:v4.1.1.1 my_project
```

The command is now faster, but PHP's garbage collector takes more than 40% of the execution time!

![before-gc](https://user-images.githubusercontent.com/73419/42678237-95817700-867e-11e8-8214-f3a32810d584.png)

If I run this other command:

```
php -d zend.enable_gc=0 composer create symfony/skeleton:v4.1.1.1 my_project
```

The difference is astonishing:

![comparison](https://user-images.githubusercontent.com/73419/42678306-c8cebece-867e-11e8-847a-8e9edfb36da6.png)

The memory consumption obviously increases a lot ... but only from 137 MB to 260 MB.

So, is this something we could do? Only conditionally depending on the available `memory_limit` in php.ini? Thanks!

**Comment by Pierstoval** [comment]
Have you tested the difference with the website-skeleton, which is much bigger, to know the memory consumption difference?

**Comment by ogizanagi** [comment]
Do we now which part(s) are actually concerned and could we control the gc manually/disabling it in these parts? Composer is [already disabling the garbage collector](https://blog.blackfire.io/performance-impact-of-the-php-garbage-collector.html).

https://tideways.com/profiler/blog/how-to-optimize-the-php-garbage-collector-usage-to-improve-memory-and-performance might also interest you :)

**Comment by javiereguiluz** [comment]
I remembered that Composer disables GC ... that's why the results shocked me. Maybe it's something about my local setup?

Can any of you reproduce those results? You just need to execute this command and see how much takes the GC. Thanks!

```bash
$ blackfire run composer create symfony/skeleton:v4.1.1.1 my_project
```

**Comment by nicolas-grekas** [comment]
As the profile shows, the garbage collector DOES its job. Composer disables it on the path where we know it won't find anything to collect. Clearly not the case here. 

Definitely :-1: to disable it completely. People will add dependencies, and nobody knows how many installs this will just break by requiring huge amount of memory.

**Comment by ogizanagi** [comment]
@javiereguiluz : Here is a profile comparison with and without GC: https://blackfire.io/profiles/compare/d9e104b9-f2f6-4810-be2b-af339ffbd763/graph

**Comment by javiereguiluz** [comment]
@ogizanagi thanks for the comparison. In your case, the installation time was reduced by 70% !!!!!!!!! ... and memory just increased 0.3% (from 140 MB to 141 MB).

In any case, let's close as "won't fix". Thanks!
