### ISSUE TITLE
Cache namespace is already in use

### ISSUE THREAD

**Issue by francis-roux-serret** [symfony/flex#388]
Since v1.0.83, a new file Cache.php was added in src/
This file cause an error in Download.php beacuse it uses  (line 14):
use Composer\Cache;
which causes an error because "Cache" already exists in this namespace (because of that new file)
Can you fix this ?

**Comment by Retalyx** [comment]
Got the same problem 
![image](https://user-images.githubusercontent.com/3114980/42880627-3229f536-8a95-11e8-9ed6-3f55b4b62e07.png)

**Comment by nicolas-grekas** [comment]
Anyone willing to submit a patch?
