### ISSUE TITLE
flex.symfony.com no more available

### ISSUE THREAD

**Issue by chou666** [symfony/flex#392]
I have an error when I run the commands:

composer require symfony/requirements-checker
composer require symfony/web-server-bundle --dev

  [Composer\Downloader\TransportException]
  The "https://flex.symfony.com/versions.json" file could not be downloaded: php_network_getaddresses: getaddrinfo failed: H¶te inconnu.
  failed to open stream: php_network_getaddresses: getaddrinfo failed: H¶te inconnu.

Do you have an hosting problem with flex.symfony.com?

**Comment by stof** [comment]
this rather look like a network issue you have. `getaddrinfo failed` means that DNS resolution failed on your machine.

**Comment by chou666** [comment]
Ok thanks for your answer. I will check

**Comment by yashari01** [comment]
I have the same problem, i have tested with 3 different network but can't get   "https://flex.symfony.com/versions.json"

**Comment by stof** [comment]
That's totally expected: https://symfony.com/blog/the-old-flex-infrastructure-is-shutting-down
