### ISSUE TITLE
[Question] Where should the old app/Resources/ contents live now?

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/flex#40]
I'm switching the Symfony Demo app to Symfony Flex. I don't know what's the new practice to store the old `app/Resources/*` contents.

For example, `app/Resources/views/` are now `templates/` but what about:

* Translation files:
   `app/Resources/translations/` -> `translations/` ?
* Overridden bundle templates, for example  error pages:
   `app/Resources/TwigBundle/views/Exception/` -> ??
* Web assets (it's common to store the sources of the assets in that dir)
   `app/Resources/assets/` -> `assets/` ?

**Comment by yakobe** [comment]
@javiereguiluz Sorry for picking up on a closed Question but could you share where `app/Resources/TwigBundle/views/Exception/` templates should be using the flex structure? I cannot get the override working and i've tried several configurations.
Many thanks.

**Comment by fabpot** [comment]
@yakobe Try `src/Resources/TwigBundle/views/Exception/`, that should work.

**Comment by javiereguiluz** [comment]
Just saying: I would expect this to live in `templates/TwigBundle/Exception/...`

(and if I want to overwrite a translation file: `translations/TwigBundle/messages...` and overwrite an asset: `assets/TwigBundle/scss/...`, etc.)

**Comment by Pierstoval** [comment]
> Just saying: I would expect this to live in templates/TwigBundle/Exception/...
Yep, maybe the [TwigBundle's extension](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/TwigBundle/DependencyInjection/TwigExtension.php) can be updated to be able to change `kernel.root_dir` into a configurable parameter?

> (and if I want to overwrite a translation file: translations/TwigBundle/messages... and overwrite an asset: assets/TwigBundle/scss/..., etc.)

Overriding translations is possible by adding a file in the `translations` directory with the same translation domain name as the bundle's one, the latest translation will be used in the translator, so no need for directories if the bundle defines translation domains different than the bundle itself.

For assets, it's more an Encore problem, and I'm not sure that it would be easily solvable...

**Comment by BPScott** [comment]
At risk of reopening old discussions: following #56, it seems Flex is moving towards a [skeleton](https://github.com/php-pds/skeleton) style structure with renaming web->public and etc->config.

Skeleton also suggests making a `resources/` folder at the root for rather than storing things in `src/Resources/`. Is it also worth following that convention?

**Comment by yakobe** [comment]
@fabpot Thanks, that works 👍 

I also agree with @javiereguiluz 's expectation that they would be in `templates/TwigBundle/Exception/...`. It looks a little bit funky to have them in src now that we have a `templates/` directory.

**Comment by fabpot** [comment]
Of course... and we thought about that as well... see symfony/symfony#23339
