### ISSUE TITLE
Cant update

### ISSUE THREAD

**Issue by kironet** [symfony/flex#406]
Hi,

I'm trying to update(composer update) my project, but I'm getting this error:

```
 [ErrorException]                                                             
  Declaration of Symfony\Flex\ParallelDownloader::getRemoteContents($originUr  
  l, $fileUrl, $context) should be compatible with Composer\Util\RemoteFilesy  
  stem::getRemoteContents($originUrl, $fileUrl, $context, ?array &$responseHe  
  aders = NULL)
```

**Comment by xabbuh** [comment]
Looks like you need to update Flex first: `composer update symfony/flex --no-plugins`

**Comment by DanielBadura** [comment]
When i try this: `composer update symfony/flex --no-plugins` before installing my dependencies then i get this error: 
```
composer update symfony/flex --no-plugins
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 3 installs, 63 updates, 0 removals
 - Updating symfony/flex (v1.0.80 => v1.0.89)

...

Writing lock file
Generating autoload files
> symfony-cmd
sh: 1: symfony-cmd: not found
Script symfony-cmd handling the auto-scripts event returned with error code 127
Script @auto-scripts was called via post-update-cmd
The command "composer update symfony/flex --no-plugins" failed and exited with 127 during .
Your build has been stopped.
```

**Comment by DanielBadura** [comment]
Why did i not try this myself before..
It worked with `--no-scripts` thanks!

**Comment by emxjay** [comment]
@B-Galati Marvelous! Thanks.

**Comment by WillGibson** [comment]
While resurrecting my PHP playground after nearly 18 months on Node/TypeScript land, I had to resort to 2GB to get past this...

```
php -d memory_limit=2G /usr/local/bin/composer update symfony/flex --no-plugins --no-scripts
```

That's a lot of memory for a composer update!

**Comment by nicolas-grekas** [comment]
But you disabled plugins, so don't expect flex to be involved in any way!

**Comment by WillGibson** [comment]
I concur, but I closed my terminal now so can't double check history easily. I think there were two things in play, the incompatible signature thing and a memory limit thing. I may have lost track of exactly which it was in the end due to going to the bar in our hotel for a while :-)

**Comment by WillGibson** [comment]
In the end I only needed to increase the PHP memory limit in my PHP container to 256GB to get `composer install` to behave. It took a while to work through a load of other things that seemed to be feeding into the general malaise, but that's my fault for leaving a PR on a personal project to go stale for about 18 months because I was working in a great place and got all my code fun at work :-)
