### ISSUE TITLE
"extra.symfony.require" setting restrict packages outside the range of "symfony/symfony"

### ISSUE THREAD

**Issue by pamil** [symfony/flex#410]
Behat requires `symfony/class-loader` in `~2.1||~3.0` version. This Symfony package has been dropped in `4.0` branch.

I'd like to use `extra.symfony.require` set to `4.1.*` in order to test my application in that Symfony version, but it's impossible right now:

```
Restricting packages listed in "symfony/symfony" to "4.1.*"
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - behat/behat v3.5.0 requires symfony/class-loader ~2.1||~3.0 -> satisfiable by symfony/symfony[v3.4.14].
    - behat/behat v3.5.0 requires symfony/class-loader ~2.1||~3.0 -> satisfiable by symfony/symfony[v3.4.14].
    - behat/behat v3.5.0 requires symfony/class-loader ~2.1||~3.0 -> satisfiable by symfony/symfony[v3.4.14].
    - Conclusion: remove symfony/symfony v3.4.14
    - Installation request for behat/behat (locked at v3.5.0, required as ^3.2) -> satisfiable by behat/behat[v3.5.0].
```

Fixing this bug would require checking if the package being restricted is defined in `symfony/symfony`'s replace list at given version: https://github.com/symfony/symfony/blob/0874f7098fb92d8773e252a0076f2947bff45047/composer.json#L34-L86

**Comment by stof** [comment]
it restricts symfony/symfony and all symfony components.
