### ISSUE TITLE
"extra.symfony.id" missing. How to obtain one?

### ISSUE THREAD

**Issue by gesof** [symfony/flex#417]
Right after creating a Symfony Recipes Server it is stated:
"Authorize projects to use the recipes by adding their project's IDs in config.json (where PROJECT_ULID is the value of composer config extra.symfony.id)". 

I could not find a way to generate that ID and it seems that this piece of information is missing from all related documentation I could find online.

**Comment by stof** [comment]
the flex plugin adds a `composer symfony:generate-id` command

**Comment by gesof** [comment]
A search on google by that command got me 5 results, one being the source code of that command and the other 4 being about other subjects. With your comment there will be two good results on Google. Thank you.
