### ISSUE TITLE
what about CHANGELOG.md?

### ISSUE THREAD

**Issue by tarlepp** [symfony/flex#418]
It would be really nice to have changelog to show what has been changed between different versions.

**Comment by fabpot** [comment]
Flex is feature complete, it's mostly about optimizations and small bug fixes now. So, probably not worth it.

**Comment by bogdaniel** [comment]
Since the latest update 1.9 with the auto unpack feature maybe a changelog with important changes would be nice.  Waking up and having a composer.json full with new libraries kinda makes your head spin around.
