### ISSUE TITLE
[Feature] Opt out of src folder structure modifications

### ISSUE THREAD

**Issue by mnavarrocarter** [symfony/flex#419]
I love using Flex, is such an awesome tool and y really love it, because of the pack syntax and the autogenerated config, and env variables.

There's a feature that I don't like that much though, and it's when flex creates folders in my src dir. I'm following clean architecture directory structure. I know that it is a simple as a folder delete, but if I want to share the project with another colleague, flex will create the folders again. 

So, if this is a feature that you would like to implement, that would be awesome. I don't really know how to go about it, since I don't really know how composer plugins work. :)

If flex can be hooked into, maybe I could create a plugin that prevents src folder creation.

Thanks!

**Comment by mnavarrocarter** [comment]
Mmm...I think I tested that a few weeks ago. But thanks for the reply @fabpot. I'll take a look again and I'll tell you how it goes. :)

**Comment by xabbuh** [comment]
In general, I don't think allowing to skip parts of a recipe is a good idea. Doing that raises the risk that recipes won't work properly as, for example, the generated config files may rely on some PHP files being copied into the `src` directory.

**Comment by fabpot** [comment]
Closing as there is no issue since we record the installed recipes in symfony.lock.
