### ISSUE TITLE
RFC: Custom generate()'ors

### ISSUE THREAD

**Issue by ckrack** [symfony/flex#420]
As @fabpot already mentioned in #78. We have %generate()% as a placeholder for generators, with secret being the only implemented right now.

It would be great to be able to write custom generators.

My usecase right now is, I want to write a recipe for [Optimus](https://github.com/jenssegers/optimus).
It requires a prime number, an inverse and a random number for obfuscation.
I would use the following pseudo-code:
```json
{
    "env": {
        "OPTIMUS_PRIME": "%generate(optimus, prime)%",
        "OPTIMUS_PRIME": "%generate(optimus, inverse)%",
        "OPTIMUS_PRIME": "%generate(optimus, random)%"
    }
}
```

This would create an object of my tagged `App\Flex\Configurator\Generator\OptimusGenerator` service and call `$generator->generate('prime');` etc on it.

Of course the generator would be in the recipes-code, so it must run after that being copied.

Maybe we can tag them as services or name them in the manifest.

```json
{
    "generators": {
        "optimus": "App\\Flex\\Configurator\\Generator\\OptimusGenerator"
    }
}
```

What do you think?

**Comment by Pierstoval** [comment]
I really like the idea, but as it's a proposal for non-standard generator names, IMO the keyword should probably contain a name that's impossible to reuse, for example the vendor + package name, something unique :thinking: 

But for the case of Optimus, as you already have a CLI provider, a solution I see would be a `--output-format=env | tee .env .env.dist` option to your command that would add env vars with the associated values, to avoid burdening Flex with features that will probably be used by a very few amount of packages :confused:

**Comment by ckrack** [comment]
Good point, however the generators naming could be taken from the JSON and would be local to the recipe installation.

**Comment by nicolas-grekas** [comment]
Closing as staled.
