### ISSUE TITLE
Disable reciepts or  Flex in Symfony 4.1

### ISSUE THREAD

**Issue by Manuel-Linkener** [symfony/flex#422]
Each time we do a fresh `composer install` on a project that was newly cloned from git, some flex scripts mess with files:

- adding stuff to files like `.gitignore`, `phpunit.xml.dist`, even though the files already contain this and are formatted to be more readable.
- created files and folders like `translations/` folder and `new .gitignore` files, even tough the project does not use any translations.
- creates `src/Controller`, `src/Entity` for some reason
- Modifying the `config/services.yaml` file and creating invalid Yaml (it adds a `locale` parameter with 4 spaces indent, even though the file uses 2 space indent)

I tried to disable those receipts and I failed. I like the flex feature that creates the config files, but I would like to disable certain receipts, that mess with files and folders.

If this is not possible: is there a way to remove Symfony Flex from a Symfony 4.1 project? When I remove the dependency, the composer install stops working and I can not find any documentation about Symfony 4.1 without Flex.

**Comment by stof** [comment]
have you committed the symfony.lock file in your project ? If no, having issues like that is totally expected, as that file is the place where Flex remembers which recipes have already been applied.
If you don't store it in your project, running Flex on a fresh clone will consider that none of the recipes have been applied, and will apply them all.

**Comment by Manuel-Linkener** [comment]
I committed the `symfony.lock` file and tested it (yesterday) and this solved most of the problems but the modification of the `config/services.yaml` and it created 2 new config files (`config/translation.yml` and `config/validation.yaml`). I saw this behavior again today, so I wrote this issue.

Now (after your response) I recreated everything (fresh clone, delete symfony.lock), then `composer install` and reverted the Flex stuff I don't want (modified files + deleted the created folders and so on).

Then I committed the newly created symfony.lock and tested a fresh install (git clone + composer install). Now it actually works and Flex does not do any modifications anymore!

Not sure why it was not locked before for symfony/translation and symfony/validation, but it seems to be fixed.

Thanks for your fast response, you do great work here!

**Comment by Pierstoval** [comment]
Maybe you had an older version of Flex. For further troubleshooting, one might run `composer update symfony/flex --no-scripts --no-plugins` to update Flex only and then retry everything to see if it's ok :)

**Comment by Manuel-Linkener** [comment]
@Pierstoval okay, next time I have a problem like this I will try to update Flex only first. Thanks!

**Comment by Pierstoval** [comment]
Since Flex is pretty stable now, I think you won't ever have the problem anymore, but it's mostly for people coming to this issue after googling something :wink:
