### ISSUE TITLE
Unable to have private recipe repository because PR validation from Symfony Flex Bot fails everytime

### ISSUE THREAD

**Issue by SebTM** [symfony/flex#424]
I had a repository to store changed/individual recipes for flex or use it for testing new recipes before making a pull-request to "symfony/recipes-contrib". At some point this repository was not needed and I deleted it, as I had a new thing to test I recreated it and installed the Symfony Flex Server App (at Github) again. After creating the PR the bot says "The pull request does not exist, is closed, or has already been merged."

My thought was, this is a not common use-case (recreate repository with the same name - so IDs of the pull-requests start at 1 again), so I created a test repository with the name "recipe-test20180922" which includes the date so I am sure that this was never used in my namespace before. But also there - with different commit ids, different code, I get "The pull request does not exist, is closed, or has already been merged."

https://github.com/SebTM/recipes/pull/1
https://github.com/SebTM/recipe-test20180922/pull/1

You can have a look here yourself. Would be nice if you can help me or at least provide the correct place/person to contact for.

**Comment by alexperegrina** [comment]
I have the same problem

**Comment by h3llr4iser** [comment]
Same problem trying to test recipes:

Validation status is not available

The pull request does not exist, is closed, or has already been merged.

Tested Recipe: github.com/dfutura/symfony-recipes#1

**Comment by dkeller85** [comment]
Any updates to this ?
I am having the same issue, when trying to setup a private recipe repo.

**Comment by SebTM** [comment]
Let's try to ping @fabpot - can you help? :)

**Comment by nicolas-grekas** [comment]
Closing as private recipes are not supported.
