### ISSUE TITLE
Add support for multiple bundles in auto-configured packages

### ISSUE THREAD

**Issue by emodric** [symfony/flex#427]
Currently, if a package has a `symfony-bundle` type and does not have a recipe, it is automatically added to `bundles.php`, extracted from PSR4 autoload config. However, this only works for the first bundle listed in PSR-4 autoload.

It would be great if Flex would automatically activate all bundles it finds in autoload config, not just the first one.

~Additionally, if some of them are listed in `autoload-dev` section, it would be great if those were automatically activated for `dev` environment too.~ Disregard this, this is not always wanted and most probably cannot be automated.

**Comment by Pierstoval** [comment]
Deciding whether a bundle should be enabled for a specific environment is the role of the recipe itself. And having multiple bundles in a single repository is not the best option for maintenance :confused:

**Comment by emodric** [comment]
Some users prefer monolithic repos with multiple bundles, which separate concerns. And best option for maintenance is whatever is easier for the package developer, no? ;)

**Comment by Pierstoval** [comment]
Yes of course, but if one bundle needs a tough update, the other will also be updated with no changes, which is counter-productive in terms of versioning. Separate concerns = separate packages, whatever seems easier :smile: It's about clean coding, mostly :wink:

**Comment by emodric** [comment]
In my case, repo is not split in multiple packages in Composer. One repo, one package, one versioning strategy. Bundles are used to separate code for various parts of the application.

That should be a supported use case.

**Comment by Pierstoval** [comment]
This is not a common case, and it's not any best practice in any SF documentation, I don't think that Flex should support this natively without a recipe.

However, you can still create a recipe for your package and add the two bundles in the `bundles` configurator :+1:

**Comment by emodric** [comment]
Nope, I can't, because Flex doesn't accept GPL licensed packages.

**Comment by nicolas-grekas** [comment]
Would you be able to send a PR doing so?

**Comment by emodric** [comment]
Yep, but in a couple of days.
