### ISSUE TITLE
Handling of already existing files when requiring/removing a pack

### ISSUE THREAD

**Issue by Lyrkan** [symfony/flex#428]
Hi there,

I've seen multiple issues opened on the Encore repository that were caused by an already existing `package.json` file when requiring the related pack (the most recent one being https://github.com/symfony/webpack-encore/issues/411).

Since the recipe [adds this file](https://github.com/symfony/recipes/blob/0516ca401683a82fb37b27296fd4f2803b257d54/symfony/webpack-encore-pack/1.0/manifest.json#L5) using the `copy-from-recipe` configurator it fails silently when the user already has one (which may not be an uncommon situation and means that Encore won't be installed). 

Also annoying: if the user decides to remove the pack it will also remove the `package.json` file (which has probably been modified by then) without any warning.

The first issue could probably be handled by adding a message if `copy-from-recipe` wasn't able to copy a file for this reason, but:

* I'm not sure that it will be enough for the users to know what they have to do (even though we could add something in the doc about it I'm afraid it won't be *that* obvious)
* There may be some situations where that message would probably not be needed and have the opposite effect (people being worried about a warning message that they could safely ignore)

For the second problem, `package.json` could probably be ignored in the `removeFiles` method [the same way it's currently done for the ".git" repository](https://github.com/symfony/flex/blob/c218d231f8dba262e6b5c99a5e720861864ece12/src/Configurator/CopyFromRecipeConfigurator.php#L78), but I'm not sure that adding something that specific to a recipe into Flex's code would be a good idea...

**Comment by maxhelias** [comment]
:+1: for add a message when the file isn't copy.

For the second problem, I do not know if it's possible, but in Flex.php we have the `askAndValidate` method to ask the user. Is it possible to add it to the configurator and add an option to force the remove without asking?
