### ISSUE TITLE
Flex breaks composer scripts

### ISSUE THREAD

**Issue by alexander-schranz** [symfony/flex#431]
When you have flex installed it breaks [composer scripts](https://getcomposer.org/doc/articles/scripts.md#executing-php-scripts):

Install [flex](https://github.com/symfony/symfony/blob/8d277ce3e594c196594170e4fbbc37be98ba4f73/.travis.yml#L210):

```bash
composer global require --no-progress --no-scripts --no-plugins symfony/flex dev-master
```

run `composer install` with following composer.json

```json
{
    "scripts": {
        "auto-scripts": [
            "@php -r 'echo 1;'"
        ],
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
    }
}
```

you get:

```bash
  [InvalidArgumentException]
  Command type "@php -r 'echo test;'" is not valid.
```

without flex this works as expected.

**Comment by nicolas-grekas** [comment]
Would you be able to send a fix?

**Comment by nicolas-grekas** [comment]
Couldn't you just use another name than "auto-scripts" in your not-flex project?

**Comment by alexander-schranz** [comment]
@nicolas-grekas we did currently. But think ignoring autoscripts by the flex executor if they  are not in the symfony format will avoid other developers investigate time finding the error. Think we are not the only developer which tries to structure the composer.json in all projects the same way.

**Comment by fabpot** [comment]
Ignoring auto-scripts not in the right format would be bad for DX as no errors would be raised.

**Comment by alexander-schranz** [comment]
@fabpot thats not correct as the default composer script executor is called which will raise an error when it's not compatible with the composer script execution.

**Comment by nicolas-grekas** [comment]
See my proposal in #459. It should help understand the issue earlier, which is the most important thing here to me.
