### ISSUE TITLE
composer require keep unbounded constraint

### ISSUE THREAD

**Issue by henri9813** [symfony/flex#433]
When i run 
`composer require symfony/console`

My composer.json got a new line which correspond to this package, but the version is unbounded, 
```
 "symfony/console": "*",
```
How can i get fixed version ? ( example: ^4.1 etc.. ) 

Regards

**Comment by Pierstoval** [comment]
You do not need it when using Flex, because the version constraint for Symfony packages is in the `extra.symfony.require` composer option.

**Comment by Soullivaneuh** [comment]
@Pierstoval We especially don't want this option, that's why we removed it.

But composer still require an unbound constraint.

**Comment by nicolas-grekas** [comment]
Hello, wrong repo: constraints are set on this one: https://github.com/symfony/skeleton
But the constraints *are* bounded, thanks to the extra.symfony.require line in
https://github.com/symfony/skeleton/blob/master/composer.json#L59

**Comment by Soullivaneuh** [comment]
Hello @nicolas-grekas,

I'm not sure it's related to the skeleton. Constraint are indeed bounded thanks to the `extra.symfony.require` option.

The issue we have is we removed this option and `composer require symfony/package` still add un unbound constraint instead of searching for the last stable one.

As the option resolving is related to flex, isn't that the good place for this issue?

**Comment by stof** [comment]
Well, if you remove the Flex-specific constraint, you are left with normal composer constraints.

What Flex does is filter out the available versions based on `extra.symfony.require` when reading Packagist metadata. It does not do special things in the solver.
Btw, this Flex feature does not require using a `*` constraint for your requirement (you only need to make sure that your `extra.symfony.require` constraint gives you some versions matching your requirement)

**Comment by nicolas-grekas** [comment]
> composer require symfony/console
> My composer.json got a new line which correspond to this package, but the version is unbounded,
> "symfony/console": "*",

OK, this is Flex doing it, reopening :)

**Comment by nicolas-grekas** [comment]
fixed in #435
