### ISSUE TITLE
create-project command modifies the composer.json file when installed as global dependency

### ISSUE THREAD

**Issue by emodric** [symfony/flex#440]
When Flex is installed as a global dependency (to take advantage of its parallel downloader), `composer create-project` modifies the `composer.json` file.

For example, running the following:

```
composer create-project ezsystems/ezplatform
```

will:

1) remove author names from `authors` section, making the `composer.json` file invalid
2) remove `name` and `description` from the file
3) Change license to `proprietary`

Flex should not modify the `composer.json` file if it is not specified as a hard dependency in the project itself.

**Comment by stof** [comment]
I'm quite sure this is done on purpose in Flex (well, except the part about making the composer.json file invalid, which is probably a bug).
When creating a project from a skeleton, keeping the name and the license of the skeleton itself for your project does not actually make sense.

**Comment by stof** [comment]
Yeah, removing the author name is a bug in the removal of the package name (it actually removes any `name` property).

/cc @nicolas-grekas

**Comment by emodric** [comment]
Well, since the project doesn't go on Packagist, it doesn't really matter. I would argue that its quite useful to know from which blueprint was the project instantiated originally.

**Comment by emodric** [comment]
License change is also questionable, since in eZ Platform case, it needs to remain on GPL2.

**Comment by nicolas-grekas** [comment]
Thanks for the report, looks like a bug yes, when used globally this shouldn't happen.

**Comment by hectorprats** [comment]
I think it's best to create a 'type' key from composer.json that is 'skeleton'. And flex erase name, description and authors if the key is that.
