### ISSUE TITLE
sync:recipes --force does not update .gitignore entries

### ISSUE THREAD

**Issue by weaverryan** [symfony/flex#457]
When testing the `sync:recipes --force`, my `.gitignore` file WAS updated to add *new* packages that previously did not have any `.gitignore` rules and now have some.

But, for FrameworkBundle (for example), I DID already have some entries in `.gitignore` from its recipe. However, those entries were *not* updated.

To replicate

```
git clone git@github.com:symfony/symfony-demo.git
cd symfony-demo
git checkout v1.2.7
composer install
rm -rf vendor/symfony/flex
git clone git@github.com:symfony/flex.git vendor/symfony/flex
composer sync-recipes --force
```

**Comment by Pierstoval** [comment]
Yep, the GitignoreConfigurator does not take the sync "force" state.

I submitted #458 to attempt to fix it :)
