### ISSUE TITLE
sync-recipes --force should ignore files that did not change since the last time a recipe was updated

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/flex#461]
No need to reset a file to its initial state when the recipe that defines it did not update the file.

**Comment by weaverryan** [comment]
This will make `sync-recipes --force` much easier to use over time - it made many unnecessary changes (replaced config files that didn't change, re-added files I had deleted). Hopefully the same logic can be provided to all the configurators - e.g. if the `env` details haven't changed, let's not remove and re-add the recipe.
