### ISSUE TITLE
New release ?

### ISSUE THREAD

**Issue by lyrixx** [symfony/flex#474]
When I create a fresh skeleton, I can read [this](https://github.com/symfony/recipes/blob/481ce0a9f1619c0bea95d1b37c4477a9880f7039/symfony/flex/1.0/.env#L13):

```
# Run "composer dump-env prod" to compile .env files for production use (requires symfony/flex >=1.2).
```
But flex 1.2 is not released yet so it could not work.

BTW this new line could have been added to the 1.2 version of flex:
```diff
- recipes/symfony/flex/1.0/.env
+ recipes/symfony/flex/1.2/.env
```

**Comment by nicolas-grekas** [comment]
We should merge https://github.com/symfony/flex/pull/451 before releasing 1.2

**Comment by lyrixx** [comment]
Fixed : https://github.com/symfony/flex/releases/tag/v1.2.0

Thanks
