### ISSUE TITLE
Skip/override some validations for private recipes

### ISSUE THREAD

**Issue by nicwortel** [symfony/flex#481]
I'm filing this issue under symfony/flex as I couldn't find a repository for the flex-server (and the integration with status checks in GitHub pull requests).

Trying to create a private recipes repository for our company, I'm running into the following issue. Everything works fine for the recipes themselves, but when creating a pull request to merge our new recipes into master the symfony-flex-server bot reports that the changes are invalid.

The following validation errors are reported (both multiple times, but I've limited this to a single example per error type):

> symfony/framework-bundle/4.0/config/packages/framework.yaml (lines 2, 3, 4, 5, 7, 8, 9, 14, 15, 16)
> Indendation must be a multiple of 4 blanks

The reason is that we follow a standard of 2 spaces indentation for YAML files, instead of 4 (mainly to prevent any issues and inconsistencies with arrays of objects in YAML, and because we apply this to all YAML files, not just Symfony's). I see how it makes sense to enforce this coding standard for the official Symfony recipes, but I believe it makes less sense to enforce this for private recipe repositories.

> symfony/framework-bundle/4.0/docker-compose.yml
> Should be renamed to "symfony/framework-bundle/4.0/docker-compose.yaml"

In this case I've added a file `docker-compose.yml` to the recipe, so any project that installs the FrameworkBundle automatically comes with a `docker-compose.yml` file. However, the Symfony flex validation fails on the `.yml` extension as it enforces the use of `.yaml`. While this makes sense for Symfony YAML configuration files, I don't think that Symfony Flex should enforce this extension for files that are not read by Symfony.

I couldn't find much documentation on the Flex server, so perhaps there is an existing way to disable/suppress/configure the validation of Flex recipes that I'm not aware of. If there is not, I would like to see a way to achieve this. Or perhaps the Flex server should only do *functional* checks for custom recipe repositories (making sure that the syntax of the `manifest.json` is correct and the recipe works, etc.), and only enforce (coding) standards for the official symfony/recipes and symfony/recipes-contrib repositories?

**Comment by nicolas-grekas** [comment]
Private recipes are not officially supported sorry.
