### ISSUE TITLE
Question: Do you add required dev packages to root of composer.json?

### ISSUE THREAD

**Issue by ArminVieweg** [symfony/flex#483]
Hi, I've realized that my composer.json contains for me unknown stuff at root level after performing an update. I didn't know that this is even allowed in composer.json schema:

    "customer/base-bundle": {
        "version": "dev-develop"
    },
    "customer/a-bundle": {
        "version": "dev-develop"
    },
    "customer/b-bundle": {
        "version": "dev-develop"
    },
    "customer/c-bundle": {
        "version": "dev-develop"
    },
    "symfony/polyfill-intl-idn": {
        "version": "v1.11.0"
    },

I also asked on Stackoverflow: https://stackoverflow.com/questions/55458191/why-does-symfony-flex-adds-own-dev-develop-bundles-to-root-level-in-composer-j

I hope you know where this comes from and what's its purpose. 

Thanks, 
Armin

**Comment by weaverryan** [comment]
@ArminVieweg Are you sure that's content from your `composer.json` file? Flex *does* update a `symfony.lock` file, and that content matches what's in that file. If your composer.json file is being updated, that is either a bug or some weird setup in your system is causing this.

**Comment by ArminVieweg** [comment]
I should mention that I use an alternative `composer-dev.json`, by changing environment variable COMPOSER.

Could this cause the issue? 

The only difference between original composer.json are the urls to custom VCS repos.

**Comment by stof** [comment]
hmm, could it be that the usage of the `COMPOSER` env variable confuses Flex when looking for its lock file ?

**Comment by weaverryan** [comment]
Here it is: https://github.com/symfony/flex/blob/master/src/Command/SyncRecipesCommand.php#L55

The temporary fix would be to also set a `SYMFONY_LOCKFILE` to `symfony.lock`, so that Flex doesn't automatically try to determine it, which is broken in your case. But, Flex should perhaps detect this better or throw an exception.

**Comment by ArminVieweg** [comment]
Cool! What also could help is to rename composer-dev.json to dev-composer.json. Then the str_replace should work :)

**Comment by ArminVieweg** [comment]
I can confirm: You should not interrupt the string "composer.json" in your alternative composer filename... But prepending e.g., "dev-" works like charm.

It also creates a "dev-symfony.lock" file then, when you provide a "dev-composer.json" file.
