### ISSUE TITLE
Parallel downloading not works when installing without running scripts

### ISSUE THREAD

**Issue by Koc** [symfony/flex#487]
Symfony Flex v1.2.2. I'm trying to optimize docker build by applying section "3. Composer install before codebase" from [this guide](https://medium.com/@c.harrison/speedy-composer-installs-in-docker-builds-41eea6d0172b).

And the problem is: when I run
```
RUN composer install --prefer-dist --no-scripts --no-dev --no-autoloader && rm -rf /home/www-data/.composer
```
then parallel downloading stops working. Don't know why it happens, because flag `--no-plugins` is not set. IFIK Symfony Flex works as plugin so `--no-scripts` flag shouldn't affect parallel downloader.

**Comment by nicolas-grekas** [comment]
> Symfony Flex works as plugin so --no-scripts flag shouldn't affect parallel downloader

not the case apparently, nothing we can do about on Flex' side
