### ISSUE TITLE
Auto-generated recipes and HTTP 500s errors

### ISSUE THREAD

**Issue by respinoza** [symfony/flex#490]
I noticed that if the recipe server fails (returns 500 errors), flex will keep going by auto-generating recipes, no warning or errors.

Now, we are running https://github.com/moay/symfony-flex-server but certainly this could happen to the official end point too.

From my point of view, I think we should at least show a warning message (I really think we should just throw an error and stop) when a 500 error happens as this is different from a 404 (no recipe found).

I can create a PR if everybody agrees with this, finally, I looked at the code to see how much effort will be and I am a bit lost on how the downloading works, specially the one from composer so if someone could point me to the right direction it will be appreciated.

Thank you

**Comment by nicolas-grekas** [comment]
PR welcome yes!
