### ISSUE TITLE
Activate http compression

### ISSUE THREAD

**Issue by staabm** [symfony/flex#492]
Curl doesnt use compression on the transport layer per default.. should flex activate curl based http compression?

https://curl.haxx.se/libcurl/c/CURLOPT_ACCEPT_ENCODING.html

**Comment by nicolas-grekas** [comment]
Doesn't Composer already handle compression in its RemoteFilesystem class?

**Comment by staabm** [comment]
Composers RemoteFilesystem supports zlib as far as I can see.
Curls supports also more modern compressions like brotli.

Initially I opened this issue because I got the impression the CurlDownloader in this repo should use it... is composers RemoteFilesystem also used?

**Comment by nicolas-grekas** [comment]
>  Curls supports also more modern compressions like brotli.

true, but I'm not sure that'd make a significant enough improvement - and not sure packagist supports it anyway

> is composers RemoteFilesystem also used?

absolutely

**Comment by staabm** [comment]
Ok, I will check with Jordi
