### ISSUE TITLE
Allow to specify that a recipe should be applied only if another package is also available

### ISSUE THREAD

**Issue by stof** [symfony/flex#495]
We have this use case for DoctrineBundle. The bundle itself allows configuring both DBAL and ORM, but has a requirement only on DBAL (the ORM is an optional dependency precisely for people using DBAL only).

The current recipe configures the ORM part. This is fine for people using the orm-pack, but breaks things for people using DoctrineBundle (see https://github.com/doctrine/DoctrineBundle/pull/960).

I see several alternatives to solve that DoctrineBundle case:

1. split the bundle in 2, one for DBAL and one for ORM. While that might be the right solution (@alcaeus and I already discussed that in Brussels and it might happen, but not in the next few months), it requires time and won't solve things for people using the existing bundle rather than the replacement. And we might not be alone with that situation
2. move the ORM config into a recipe of the orm-pack package while the `doctrine/doctrine-bundle` recipe would configure DBAL. This is bad because unpacking the pack would not keep the ORM config.
3. move the ORM config into a recipe of `doctrine/orm`. This is bad *today* if you install the ORM without installing DoctrineBundle.

This feature request is about unlocking the third case. If you could say that the `doctrine/orm` requires `doctrine/doctrine-bundle`, it would be applied only if you install the ORM and you have the bundle.

**Comment by stof** [comment]
note that this feature might also be the right way to handle the case solved by a `conflict`  in #464. We solved that by saying that we don't apply the `symfony/messenger` recipe if you have an outdated FrameworkBundle. But things also break if you don't have FrameworkBundle (which was not tested as it is part of the skeleton). The clean solution would be a requirement on an uptodate FrameworkBundle instead (as the messenger component recipe indeed work only if you have FrameworkBundle)

**Comment by Pierstoval** [comment]
Splitting the bundle in 2 seems the best option to me. What are the exact blockers for this?

**Comment by alcaeus** [comment]
> What are the exact blockers for this?

Time. Maybe I can get to it in time for Symfony 5, but @stof and I also discussed a nice BC way to do it.

**Comment by stof** [comment]
and this split would still not fix it for anyone using the existing DoctrineBundle.

**Comment by nicolas-grekas** [comment]
I'm closing here because I don't think the solution belongs to flex, where we'd better keep low complexity.
