### ISSUE TITLE
[security] Secret should not be stored in environment variables

### ISSUE THREAD

**Issue by dunglas** [symfony/flex#50]
Secrets such as passwords and SSH keys must not be stored in environment variables. Basically, environment variables are often stored (unencrypted) in logs and displayed when an error occurs.
The Docker security team recently published a post explaining why storing secrets in env variables should be avoided: https://diogomonica.com/2017/03/27/why-you-shouldnt-use-env-variables-for-secret-data/
They also released a tool to manage secrets. 

Flex actually use environment variables to store secrets (ex: the Doctrine recipe). It should use files or a system similar to the one introduced by Docker instead.

**Comment by mahono** [comment]
Maybe solve it by referencing a file in an env variable?

**Comment by dkarlovi** [comment]
This has been discussed in https://github.com/symfony/recipes/issues/64 too.

**Comment by dunglas** [comment]
And here: https://github.com/symfony/recipes/pull/89#issuecomment-311506666

I'm working on a patch for the DI component, but I've no ETA yet.

**Comment by dkarlovi** [comment]
@dunglas excellent, great to see someone with leverage push this issue further. :+1:

**Comment by fabpot** [comment]
Closing this one as discussion is now happening on symfony/symfony
