### ISSUE TITLE
Referencing "real" env var with dump-env

### ISSUE THREAD

**Issue by DavG** [symfony/flex#500]
Hello,

Suppose I have in my etc/environment DEFAULT_APP_CDN=https://cdn.somewhere.com

In Flex 1.2.0, I can write in my .env
`APP_CDN=${DEFAULT_APP_CDN}`
Then with 
`composer symfony:dump-env whatever`
I got in .env.local.php
`'APP_CDN' => 'https://cdn.somewhere.com'`
And that's pretty cool.

But starting with Flex 1.2.1, I got 
`'APP_CDN' => ''`

Was it not supposed to work from the start ? 
Is there another solution to do this ?

Thx

**Comment by nicolas-grekas** [comment]
That's desired behavior: dump-env is context-free.
If that doesn't work for you, you can create your own dumping logic.

**Comment by DavG** [comment]
So it was a bug in 1.2.0, fixed but undocumented.

Ok, I would do my own.

**Comment by DavG** [comment]
@nicolas-grekas I see this still works without dump-env (ie only with .env), I can reference a real environment variable in my .env 
APP_CDN=${DEFAULT_APP_CDN}

Then in PHP, $_ENV['APP_CDN'] / $_SERVER['APP_CDN'] has the real value.

Can you tell me if it's the desired behavior, in this case ?
Or is it going to break in a future release ?

Thanks.

**Comment by nicolas-grekas** [comment]
Got it, see #507
