### ISSUE TITLE
Add the ability to sync the recipe of a single package

### ISSUE THREAD

**Issue by tsantos84** [symfony/flex#501]
Currently `sync-recipes` syncs all packages that have recipes and can be dangerous if I need to sync only one recipe. A useful improvement would be sync a single recipe so we can have more control in what are being updated. To support that, a separated command to list all packages configured by recipes could be added in this feature, like this:

`composer recipe:list` which would print:

* symfony/console [oficial]
* symfony/validator [oficial]
* tsantos/serializer-bundle [contrib]

and now is possible to sync one or more package:

`composer sync-recipes symfony/console tsantos/serializer-bundle`

The same above command could be renamed to:

`composer recipe:sync symfony/console tsantos/serializer-bundle`

    I'm not sure if this command should list packages names or recipes names.

Following this way, we could have a namespace called `recipe` to hold all commands related to recipes.

* recipe:list
* recipe:sync
* recipe:fix

**Comment by Pierstoval** [comment]
Why would one need `composer recipe:list` when you can just see this in `symfony.lock` quite clearly?

**Comment by keichinger** [comment]
@Pierstoval it's way more convenient and could also be used for some statistics/analytics that are gathered by your CI. You could make the same argument about almost any other console command.

**Comment by tsantos84** [comment]
As @Pierstoval said, it's better to run a command and see the list of recipes rather than open the symfomy.lock file.

**Comment by nicolas-grekas** [comment]
I wouldn't change the existing names as that's a too hard road for e.g. documentation, slides, tutorials.
But having a `--dry-run` option would be great, and being able to specify a list of packages on the existing command too.

**Comment by tsantos84** [comment]
What about to keep the original name as alias to the new ones?

**Comment by nicolas-grekas** [comment]
The new names would need to be significantly better, but I'm not sure they are personally :)

**Comment by maxhelias** [comment]
Look at the RFC #518 your need is listed

**Comment by nicolas-grekas** [comment]
Closing in favor of #501

**Comment by maxhelias** [comment]
Rather : https://github.com/symfony/flex/pull/562
