### ISSUE TITLE
Once upgrade symfony 3.4 to flex Boolean issue happen:  ->cannotBeEmpty() is not applicable to BooleanNodeDefinition.

### ISSUE THREAD

**Issue by Pasuvan** [symfony/flex#506]
In BooleanNodeDefinition.php line 51:                                                            
  ->cannotBeEmpty() is not applicable to BooleanNodeDefinition.

**Comment by xabbuh** [comment]
Please provide more information here. How can one reproduce the issue? How is it related to Flex? Do you get a stack trace?

**Comment by Pasuvan** [comment]
I was followed by Symfony official link: https://symfony.com/doc/current/setup/flex.html#upgrading-existing-applications-to-flex
Once i was removed Symfony/symfony and then add symfony/flex pack after that update the composer above error happened.
A lot of bundles are added and the recipe also added.

**Comment by nicolas-grekas** [comment]
Hi, sorry but there is nothing we can do without a better description.
I'm pretty sure this is not related to flex, please have a look at symfony/symfony if you can report with more details. Thanks for your understanding.
