### ISSUE TITLE
Undefined index: version_normalized

### ISSUE THREAD

**Issue by yceruto** [symfony/flex#508]
Error: 
 * AppVeyor: https://ci.appveyor.com/project/fabpot/symfony/builds/25060723#L73
 * Travis: https://travis-ci.org/symfony/symfony/jobs/541735605#L2605

https://github.com/symfony/flex/blob/bc7390dcfa6d50e431e4d15b647544e59a6e3146/src/Cache.php#L82

or

https://github.com/symfony/flex/blob/bc7390dcfa6d50e431e4d15b647544e59a6e3146/src/Cache.php#L101

**Comment by nicolas-grekas** [comment]
Reproduced, I'm on it.
