### ISSUE TITLE
Cannot install latest symfony/phpunit-bridge with older Symfony versions

### ISSUE THREAD

**Issue by emodric** [symfony/flex#510]
Hi. I think #499 broke installing dependencies similar to this:

```
{
    "require": {
        "symfony/flex": "^1.2",
        "symfony/framework-bundle": "*"
    },
    "require-dev": {
        "symfony/phpunit-bridge": "^4.3"
    },
    "extra": {
        "symfony": {
            "require": "3.4"
        }
    }
}
```

In our setup, we always used the latest available PHPUnit Bridge, no matter what Symfony version was installed, and this worked fine for ages since PHPUnit Bridge has no dependencies on other Symfony components. With Flex 1.2.6, this install now gives the following:

```
Restricting packages listed in "symfony/symfony" to "3.4"
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package symfony/phpunit-bridge ^4.3 exists as symfony/phpunit-bridge[v3.4.0] but these are rejected by your constraint.
```

**Comment by stof** [comment]
@nicolas-grekas `symfony/phpunit-bridge` should not be considered listed in `symfony/symfony`, as we don't replace it. What could be causing this ?

**Comment by nicolas-grekas** [comment]
It shouldn't be listed in https://flex.symfony.com/versions.json /cc @fabpot

**Comment by emodric** [comment]
Hi. Any news on this?

**Comment by fabpot** [comment]
Should be fixed now.

**Comment by emodric** [comment]
Thank you, it is working fine now!
