### ISSUE TITLE
Allow `dump-env` run without composer

### ISSUE THREAD

**Issue by jorge07** [symfony/flex#512]
**Use case**

A Docker image without composer for a production environment

**Problem**
 
I don't have composer installed, this command needs to run at preStart and there's no alternative but build my own.

It's already 4y running symfony in prod with containers and it's the first time I need composer in a production image and I really want to avoid install it just to run this command... Looks so hacky

**Comment by bendavies** [comment]
we don't use the dumped `.env.local.php` file or `DotEnv` in prod. all env vars are provided to the container.
so we just do this instead:
```Dockerfile
RUN echo '<?php return [];' > .env.local.php
```

**Comment by jorge07** [comment]
Thanks @bendavies this will work but still a hacky solution. I'm sure there're better ways to solve that. But ATM I'll follow your solution 👍

**Comment by nicolas-grekas** [comment]
It's not a hack, it's the correct solution. Doc PR welcome.

**Comment by miroslav-chandler** [comment]
Hi. I am faced with the same problem.
I need to copy the composer into the production image only for the one command.
Maybe dump-env can be moved to the Symfony commands?
