### ISSUE TITLE
Overriding values from `.env.local.php` is not possible and is not equivalent using`DotEnv`

### ISSUE THREAD

**Issue by bendavies** [symfony/flex#516]
This https://github.com/symfony/flex/issues/476, reopened, as it wasn't fixed.

It is not possible to override `env.local.php` with real env vars.
That is, using `composer dump-env` is not equivalent to using `DotEnv`.

Please see this repository for a reproducer and the README for a description of the problem.
https://github.com/bendavies/symfony-flex-env-issue

Thanks

**Comment by mareksuscak** [comment]
We got tripped up by this as well. What's the status of this issue? Doesn't seem to work still.

**Comment by teohhanhui** [comment]
@mareksuscak It should have been fixed by #611. Are you using the latest versions? What are the issues you're having?

**Comment by mareksuscak** [comment]
@teohhanhui yeah just realized we need to sync `config/bootstrap.php` manually. what a pain. this really should get documented in its own blog post.

**Comment by mareksuscak** [comment]
is it possible to rerun recipes with a command by any chance?

**Comment by tristanbes** [comment]
yes @mareksuscak :

`composer sync-recipes --force`

⚠️ You need to review your modified files one by one because ALL the reciepes will be re-run, so you'll loose some of your configuration.

There's a PR opened that will add the feature to re-run only 1 reciepe. So hopefully that'll change soon.

**Comment by mareksuscak** [comment]
sweet, thank you so much guys 🙏
