### ISSUE TITLE
Unicode in output breaks CI/CD pipelines

### ISSUE THREAD

**Issue by kevinreniers** [symfony/flex#528]
Hi,

We use https://github.com/REBELinBLUE/deployer for our deploys and since migrating to Flex we've been running into seemingly random crashes of our pipeline.

I finally figured out the cause being the Unicode musical notes being outputted here: https://github.com/symfony/flex/blob/a388cacccf6e3c5e5a395e020c5aa05849ea4ccc/src/ParallelDownloader.php#L75

Because the mysql database for this tool uses the utf8 character set with an utf8_unicode_ci collate, every time a composer install has to download something, the pipeline crashes.

Could anything be done on the Flex level to only output standard UTF8 instead?

Edit: also created an issue on the deployer's repository in the meantime.

**Comment by lyrixx** [comment]
Could you try to add the `--no-ansi` option to you command?

    composer install --no-ansi

**Comment by cgkkevinr** [comment]
`--no-ansi` is already being used and doesn't affect it, `-q` would fix it but kind of defeats the purpose of keeping server logs for our builds.

**Comment by stof** [comment]
I suggest reporting this to deployer. The MySQL `utf8_unicode_ci` collation is precisely known for *not supporting* standard unicode, but only a subset of it (it only supports UTF-8 chars fitting in at most 3 bytes, which leaves out half of unicode)

**Comment by Pierstoval** [comment]
The musical node is a 4-byte unicode character, so the collation needs to be changed for `utf8mb4_unicode_ci`, but this may break indexes sizes in MySQL, so you have to carefully check if you have indexes before changing collation, and if you do, change their size in MySQL config

**Comment by nicolas-grekas** [comment]
@cgkkevinr could you please send a PR that would disable the emojis when colors are disabled (based on `$output->isDecorated()` I suppose)
