### ISSUE TITLE
[Question] The new workflow created by env vars

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/flex#53]
Here are some common scenarios for Symfony developers. Please, confirm that I got right the first one and please, tell me how to solve the other two. Thanks!

### BEFORE

1. Browse `app.php` instead of `app_dev.php`

### AFTER

1. Edit `.env` and change `APP_ENV` to `prod` and `APP_DEBUG` to `0`
2. Reload `index.php`
3. Undo the `.env` changes to continue developing the app

---

### BEFORE

1. Edit `app/config/config_test.yml` and change the database parameters.

### AFTER

???

---

### BEFORE

1. Use Incenteev Param Handler to create the production `parameters.yml` from
   the `parameters.yml.dist`
2. Check that `app/config/config_prod.yml` contains the right config.

### AFTER

???

The `.env` is gone in production. Where do I configure the production values of
that config?

**Comment by ro0NL** [comment]
For the first; you can still create that file if necessary.

For the latter two; using env vars is optional, im not sure we can even really use it as we host multiple projects on the same server, so DB_URL or so cannot be set globally.

However i dont like having .env.prod and such.. thats why we have config_prod.yml. Env vars should not become the new parameters, its goals and usecases are different. And TBH i expected #22561 to work...

**Comment by Koc** [comment]
does env vars supports array lists and hashes like yml? looks like not

**Comment by ro0NL** [comment]
No.. why should it? An env var is stringish.

See also https://github.com/symfony/symfony/issues/22151#issuecomment-289265144

**Comment by Koc** [comment]
In yml it is possible configure some nested structure, like

```yml
notification_emails:
  email@site.com: "name 1"
  email2@site.com: "name 2"
```

in env it is impossible. Does we should combine env and yml?

**Comment by ro0NL** [comment]
Should probably be something like

```
  email@site.com: '%env(NAME1)%'
  email2@site.com: '%env(NAME2)%'
```

**Comment by javiereguiluz** [comment]
@Koc as you know, the `.env` file is for config options that depend on the machine where the app is executed (usual case: database credentials). For the notification emails, maybe you can define them:

1) In the app/config/config.yml file as regular params:

```yaml
parameters:
    notification_emails: ...
```

2) As constants in some mailer service (if you use PHP 7.1, you can even define them as private constants):

```php
private const NOTIFICATION_EMAILS = ['...', '...'];
```

3) Then, disable the actual sending of emails in the dev machine using the SwiftMailer options.

**Comment by Koc** [comment]
1. it can be some private information like api keys per hostname (multi-domain project) and we wan't share them with developers
2. hardcode + same as 1

**Comment by Koc** [comment]
a little example of our real-life parameters.yml from one project

![2017-05-10_17-47-17](https://cloud.githubusercontent.com/assets/191082/25904825/074b95aa-35a9-11e7-8a27-8f7c9a8abf1c.png)

**Comment by javiereguiluz** [comment]
Do the params displayed in the screenshot change from one machine to another? It looks like only the Google and Yandex secrets would change from your local machine to production. So, you can define those static params in `app/config/config.yml` (`etc/container.yaml` in Flex) and the dynamic params (the secrets) define them in the `.env` file.

**Comment by Koc** [comment]
this is multi-site project with per-site configuration. Also some configuration are nested.

Does parameters.yml would totally replaced with env? Or we can use both?

**Comment by javiereguiluz** [comment]
@Koc the only question that you must ask yourself is: do I have to change *this* option if I execute this app in the computer of my workmate or in production?

For example, you have a param called `hostnames_configuration.metaltop.dev.category_slug_field: null`  That's a "static param" because it's probably going to be the same wherever you execute the app. (If you reuse this code in another project, that config value may change ... but again, it doesn't depend on the machine where the app is running).

**Comment by stof** [comment]
@Koc you can use both. parameters.yml has *nothing* special in Symfony. It is just a YAML file imported by the main config file (just like `security.yml` is).
What makes parameters.yml special in SE is just the fact that it appears in `.gitignore`.

**Comment by Koc** [comment]
@javiereguiluz this project deployed with 3 different configurations. Like paas. One portal for metallurgical engineering, second for building materials, third for food. Food portal even hasn't `hostnames_configuration.metaltop.dev.category_slug_field: null`, it has other structure.

**Comment by iltar** [comment]
In the new situation, I would have only 1 front-controller (`app.php`) to edit my files, which is a better situation than before. However, I'm not willing to change my env variables each time I want to visit prod. Also, a second hostname is kind of an issue. How should I solve this?

**Comment by ro0NL** [comment]
> For the first; you can still create that file if necessary.

:)

**Comment by iltar** [comment]
@ro0NL But that's not really a sane default for the `app.php` and `app_dev.php` for flex then. Either:
 - I will have to extract the `app_dev.php` part from this file or
 - Have a lot of extra development effort changing values in files

**Comment by ro0NL** [comment]
Imo. having 1 front controller (based on env) is a sane default, i rarely visit `app_prod.php` today really.

But that also heavily relies on the fact i assume SF doesnt mess up; in my perspective if `dev` is all good, and CI passes, im ready to deploy.

Given https://github.com/symfony/recipes/blob/master/symfony/framework-bundle/3.3/web/index.php `index_prod.php` would be as simply

```php
putenv('APP_ENV', 'prod');
require 'index.php';
```

no?

**Comment by iltar** [comment]
I always use `app_dev.php` to develop, but there are often cases where I need to verify behavior in prod mode. 

I believe your `putenv()` example is a viable alternative

**Comment by ro0NL** [comment]
> I always use app_dev.php to develop

Same here, and i always keep patching vhosts to allow for `domain.dev/` :)

**Comment by Pierstoval** [comment]
The biggest personal project I'm working on is a monolithic app deployed on Heroku, and having something like 2 different domain names and lots of subdomains. I'm using 2 env vars to specify main hosts, it works like a charm.

And all my `parameters.yml` does is defining default env vars, like the `.env` file would do with Flex, because database, mailer and even secret configuration is handled via env vars and "defaulted" in `parameters.yml`.

I know @Koc example is very different because it's way much bigger than a simple multi-domain app, but it means there is a way to migrate to environment vars for at least some parts of the app itself, or change this system to a kernel-environment-based configuration (and kernel env would be set by... env vars? 😉) which is much more maintainable.

For @Koc's example, for instance, I certainly would keep using a `parameters.yml` file, or a similar system as said above, even with Flex, simply because per-app application is way more complex than simply handing a few environment vars.

**Comment by Koc** [comment]
`.env` file creates only for first installation. When another developer clone my repo and doing `composer install` - no interactive asking of parameters as before was when using Incenteev Param Handler

**Comment by Pierstoval** [comment]
You can all take a look at symfony/symfony#23823 and support the idea of having JSON strings as env vars so they can be deserialized at runtime 😉

**Comment by Koc** [comment]
@Pierstoval, had already voted. But in any case inlined json is worse than yaml. Yaml multiline and readable.

**Comment by Pierstoval** [comment]
@koc Yaml doesn't exist in a `.env` file, as said before, if you need yaml, use yaml 😄

**Comment by fabpot** [comment]
Closing this issue as it diverged from the original report. The only question that is not answered about the original question is how to define env vars for test. The answer is that you can define them in `phpunit.xml`.

**Comment by fabpot** [comment]
See symfony/recipes#170

**Comment by rabbl** [comment]
I have just looked for an answer of this question and solved it the following way:

add to the doctrine-test-config file: config/packages/test/doctrine.yaml

doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%_test'

Now you can use all doctrine commands with the test environment.
