### ISSUE TITLE
[Docker] Specify root-dir

### ISSUE THREAD

**Issue by ro0NL** [symfony/flex#534]
Follow up of https://github.com/symfony/flex/pull/128

While im a bit skeptical about this in general, i'd like to specify the path to my *DEV* docker- and compose file. (this is the feature request :))

Assuming those files live in the root-dir is wrong. The trend im seeing is a dedicateed `devops/` directory within applications, or more decoupled even.

Symfony doesn't own the docker configuration IMHO and assuming we can simply append sections might bite us. In the end any setup may need much more granularity and fine grained  control, in terms of maintaining a (custom) docker landscape. (read: full DTAP)

Other thing is it targets "dev" (aka homestead for symfony), while in fact the best practice im seeing is to build images from a base and cover all your application staging environments/concerns: https://docs.docker.com/develop/dev-best-practices/#how-to-keep-your-images-small

AFAIK it's not possible for recipes to specify overrides/alternative configs per environment. Are we really sure for SF to expand territory in this direction?

IMHO to do this right, recipes should provide their services and let the recipe server built dedicated images pushed to some "Symfony Docker Hub". Then it works for everybody.

**Comment by nicolas-grekas** [comment]
Any relation with https://github.com/symfony/flex/pull/448 ?

**Comment by ro0NL** [comment]
Not sure.. changing to root dir affects all other integrations as well. I think i'm looking for e.g.

```
'Dockerfile' => '%ROOT_DIR%/devops/environment/dev/Dockerfile'
'docker-compose.yaml' => '...',
```
