### ISSUE TITLE
PHP 7.3.7: Seld\JsonLint\ParsingException on install

### ISSUE THREAD

**Issue by jdsaphir** [symfony/flex#546]
When trying to create a project with PHP 7.3.7, the following exception gets thrown:
```
  [Seld\JsonLint\ParsingException]
  "https://flex.symfony.com/p/symfony,flex,iv1.4.4,1562912965" does not contain valid JSON
  Parse error on line 1:

  ^
  Expected one of: 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '['
```

I'm behind a corporate proxy so I thought it came from there, but it works correctly with PHP 7.1.30, so I assume the problem comes from Flex, not my proxy.

You can see more (verbose and stack trace) in the SO question I opened before finding that out: https://stackoverflow.com/questions/57097687/seld-jsonlint-parsingexception-does-not-contain-valid-json-while-install

**Comment by stof** [comment]
could it be that you have the curl PHP extension enabled in one of your runtime but not in the other one ? That would change how HTTP requests are done (and might give different results for the corporate proxy).

**Comment by jdsaphir** [comment]
> 
> 
> could it be that you have the curl PHP extension enabled in one of your runtime but not in the other one ? That would change how HTTP requests are done (and might give different results for the corporate proxy).

I did have curl enabled on my 7.3.7 but not my 7.1.30. With PHP 7.1.30 it works regardless of whether curl is enabled or not. With PHP 7.3.7, it only works if curl is disabled.

Quite weird, but I guess it means the issue doesn't come from Flex?

**Comment by nicolas-grekas** [comment]
Please report back if this still happens.
