### ISSUE TITLE
Documentation on contributing, running tests, supported platforms

### ISSUE THREAD

**Issue by leongersen** [symfony/flex#552]
Is there any documentation on contributing to Flex? I just submitted my first PR here, and I had to check the Travis configuration to figure out the PhpUnit version to run the tests with. I also noticed the current tests do not pass on Windows. Are they supposed to?

**Comment by nicolas-grekas** [comment]
Yep, they're supposed to pass :)
There is not much any doc for contributing. Feel free to ask specific questions if you have any.
