### ISSUE TITLE
Could not restrict packages to 5.0.*

### ISSUE THREAD

**Issue by fbourigault** [symfony/flex#553]
In https://github.com/liip/LiipImagineBundle/pull/1202 I'm trying to restrict Symfony version to `5.0.*`. However it works when restricting to `4.4.*`.

- 4.4: https://travis-ci.org/liip/LiipImagineBundle/jobs/574909063#L689
- 5.0: https://travis-ci.org/liip/LiipImagineBundle/jobs/574909064#L689

Does someone know why it's not working?

**Comment by stof** [comment]
this is because https://flex.symfony.com/versions.json does not list 5.0 as being a version available for the split components /cc @fabpot

**Comment by fbourigault** [comment]
I see. Does using dev-master would help?

**Comment by stof** [comment]
no, as Flex handles dev-master based on its branch alias anyway. You will need to wait for the fix on the flex server.

**Comment by nicolas-grekas** [comment]
or you can restrict to >=4.4 and allow v5 in your root requirement, that should do it.

**Comment by fbourigault** [comment]
Closing as 5.0 is now listed in https://flex.symfony.com/versions.json.
