### ISSUE TITLE
Make console path configureable

### ISSUE THREAD

**Issue by alexander-schranz** [symfony/flex#556]
In sulu we have a 2 kernel setup and if you use `bin/console` a warning is triggered always. As flex hardcoded `bin/console` in https://github.com/symfony/flex/blob/b5146ae56af9cce02d578a110ec85583fafeb063/src/ScriptExecutor.php#L102 this warning will always be triggered. It would be good if the console would be configureable over a composer extra parameter. If somebody suggest how to configure it in the composer.json and how to call the option I can create a PR for it.

**Comment by nicolas-grekas** [comment]
I'm seeing that you have a workaround in sulu isn't it?
I'd better not increase the complexity in flex if possible.
