### ISSUE TITLE
Symfony flex remove comments from bundles.php

### ISSUE THREAD

**Issue by alexander-schranz** [symfony/flex#557]
When flex is updating the bundes.php it remove all comments from it.

**Comment by GPHemsley** [comment]
I'm pretty sure `bundles.php` is regenerated from scratch every time:

https://github.com/symfony/flex/blob/305a6cd75a54992f47f46eb655245b6c9a06997a/src/Configurator/BundlesConfigurator.php#L79-L101

**Comment by fabpot** [comment]
This file is indeed overwritten when a package is added or removed (we keep additional registered bundles though, but we don't keep comments).

**Comment by sstok** [comment]
If you need to disable or comment a bundle temporary use something like `BundleClass::class => ['disabled'  => true]` or ` BundleClass::class => ['comment' => 'This needs to be enabled before X']`
