### ISSUE TITLE
Flex breaks composers artifact repository

### ISSUE THREAD

**Issue by kevinpapst** [symfony/flex#560]
Hi!

When using Flex I cannot install packages via composers built-in [artifact repository](https://getcomposer.org/doc/05-repositories.md#artifact).

**Expected behavior:**
Flex should not break composer built-in functionality.

**Actual behavior:**
My composer.json includes
```
    "repositories": [
        {
            "type": "artifact",
            "url": "var/installer/"
        }
    ]
```
and when having `symfony/flex:1.4.5` installed I run into this problem:
```
$ composer require foo/my-package 1.0
Loading composer repositories with package information
Updating dependencies (including require-dev)
Restricting packages listed in "symfony/symfony" to "4.3.*"
Package operations: 1 install, 0 updates, 0 removal
  - Installing foo/my-package (1.0): Downloading (100%)
Downloading (100%)
Downloading (100%)

  [Composer\Downloader\TransportException]
  "var/installer/my-package-1.0.zip" appears broken, and returned an empty 200 response
```
When removing Symfony Flex the installation from my local zip works as expected.

**What I tried:**

Seeing `Downloading (100%)` 3 times lead me to `Composer\Downloader\FileDownloader` and its retries loop. So I debugged further (with and without Flex) and finally found the main difference being 
- `Composer\Util\RemoteFilesystem::getRemoteContents()` using `file_get_contents()` 
- `Symfony\Flex\ParallelDownloader::getRemoteContents()` using the `Symfony\Flex\CurlDownloader`

The latter fails when trying to use curl to fetch the zip from my local filesystem. 

@nicolas-grekas any idea how to work around that problem without removing flex? Is Flex supposed to work in such a setup?

I tried [replacing this line](https://github.com/symfony/flex/blob/master/src/ParallelDownloader.php#L247) with `if (stripos($originUrl, '://')  === false || !$this->downloader) {` and everything worked. But not knowing enough about composer internals I am not sure if this is the right place to start working on a bugfix.

**Comment by nicolas-grekas** [comment]
Looks similar to #548 
we should call the downloader only when the url matches `^https?://` I suppose.
Up for sending a PR?

**Comment by kevinpapst** [comment]
Sure, I can try... for the line I linked above?
Just to make sure: can Composer packages only be distributed via http(s)?

**Comment by nicolas-grekas** [comment]
> can Composer packages only be distributed via http(s)?

it's the opposite way around: Flex's downloader can only do http(s), so it should not be used otherwise.

**Comment by kevinpapst** [comment]
PR in #561 - I found a piece of code which looks very similar here:
https://github.com/symfony/flex/blob/master/src/Flex.php#L605

I didn't add any test, as there is currently none for the class.
