### ISSUE TITLE
Minor typo in "type must be symfony-bundle" error message

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/flex#58]
`regiters` -> `registers`

![typo-in-type-must-be-symfony-bundle](https://cloud.githubusercontent.com/assets/73419/25613672/5fcabfec-2f2f-11e7-9484-f407c4acd4a9.png)

**Comment by stof** [comment]
Wrong repo to report this. symfony/flex is not responsible for validating recipes

**Comment by javiereguiluz** [comment]
But there is no other repo to report issues related to the Symfony Flex Server. In #55 I reported other typo.

**Comment by fabpot** [comment]
fixed, thanks.

**Comment by stof** [comment]
@javiereguiluz it is in a private sensiolabs repo (the one for symfony.sh)...
