### ISSUE TITLE
Issue installing some bundles

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/flex#59]
The recipe says:

```json
{
    "bundles": {
        "JavierEguiluz\\Bundle\\EasyAdminBundle\\EasyAdminBundle": ["all"]
    },
    "...": "..."
}
```

But when you execute:

```bash
$ composer req admin
```

Flex adds this to `etc/bundles.php`:

```php
<?php

return [
    // ...
    'JavierEguiluz\Bundle\EasyAdminBundle\JavierEguiluzEasyAdminBundle' => ['all' => true],
];
```

And this makes the app fail:

![flex-issue](https://cloud.githubusercontent.com/assets/73419/25625669/6984c914-2f5d-11e7-8599-f43361d71bf2.png)

**Comment by stof** [comment]
@fabpot is the auto-guessing winning over the explicit recipe ?

**Comment by fabpot** [comment]
fixed in f5bd6e0

**Comment by javiereguiluz** [comment]
It's working for me now. Thanks!

**Comment by fabpot** [comment]
Explicit recipes always win over auto-guessing.

**Comment by anacona16** [comment]
This also happen with other bundles that don't have recipe, for example I installed [EasySecurityBundle](https://github.com/EasyCorp/easy-security-bundle)

Flex append this to bundles.php

```php
<?php

return [
    // ...
    'EasyCorp\Bundle\EasySecurityBundle\EasyCorpEasySecurityBundlee' => ['all' => true],
];
```

But it's wrong, it should be:

```php
<?php

return [
    // ...
    'EasyCorp\Bundle\EasySecurityBundle\EasySecurityBundlee' => ['all' => true],
];
```

And with other bundles is the same.
