### ISSUE TITLE
composer validate fails for `flex-require`

### ISSUE THREAD

**Issue by c33s** [symfony/flex#594]
having a simple composer.json file with the `flex-require` fails with `The property flex-require is not defined and the definition does not allow additional properties`

how to reproduce:

wget https://getcomposer.org/download/1.9.1/composer.phar

create `composer.json`:
```json
{
    "name": "c33s/example",
    "type": "project",
    "license": "MIT",
    "description": "x",
    "require": {
        "symfony/flex": "^1.3.1"
    },
    "flex-require": {
        "sensio/framework-extra-bundle": "^5.1"
    }
}
```

run `php composer.phar validate`

**Comment by nicolas-grekas** [comment]
Yes, of course. You're supposed to resolve the `flex-require` section with flex itself before using the composer.json file.

**Comment by c33s** [comment]
@nicolas-grekas shouldn't you team up with composer and make it valid?

**Comment by nicolas-grekas** [comment]
Decoupling FTW, they focus on their issues...
