### ISSUE TITLE
Flex recipes are not running

### ISSUE THREAD

**Issue by Pheetbag** [symfony/flex#595]
Hi, i am creating a new symfony 4.4 project, the installation of Symfony had no problem, but now i need to install knpOauth2Bundle as a dependency, an also SentryBundle for symfony. Those dependencies have recipes to be execute but instead of being executed the console show a message for confirmation before execution of the recipes, and instead of letting me answer, it takes the default value (no execution of the recipes). I tried also using the sync-recipes command but that solve nothing and the problem is exactly the same. 

I am including a screenshot of what is logged to the console as the error.

![image](https://user-images.githubusercontent.com/29952264/71669926-b2dbd980-2d44-11ea-9735-8ad301791c0c.png)

If you want to reproduce my configuration the only thing i did before trying to install the dependencies was running `symfony new example-app --full --version=lts`

**Comment by xabbuh** [comment]
Is this on Windows using PHP 7.4?

**Comment by Pheetbag** [comment]
> Is this on Windows using PHP 7.4?

Yes. windows 10, PHP 7.4.0 and composer 1.9.0.

I was able to solve the problem changing the `extra.symfony.allow-contrib` config to `true` in my composer.json. But anyway i didnt close this issue because i guess the CLI promp should allow me to change that configuration and seeing instead this error by default is very confusing.

**Comment by xabbuh** [comment]
IIRC that's related to a PHP bug in PHP 7.4.0. Afaik that has already been fixed, but I don't know if the fix is already part of a stable release.

**Comment by Pheetbag** [comment]
I got it. Well then i can close this issue, on the meantime the `extra.symfony.allow-contrib` will do the trick, thanks for the help.
