### ISSUE TITLE
Incorrect version installed when installing dev package

### ISSUE THREAD

**Issue by dspiegel** [symfony/flex#598]
I have flex recipes for a my bundle dst/web-app-bundle with following folder layout:

├── dst
│   ├── web-app-bundle
│   │   ├── 4.0
│   │   ├── 4.1
│   │   ├── 4.3.0
│   │   └── 4.4

When I install web-app-bundle:4.4.x-dev branch, flex loads >=4.3.0 recipe and not the 4.4 which I need it to load in order to test branch changes.

Any idea what I could be doing wrong or is this an issue with flex?

The entire flex functionality seems to be mystery when it comes to what folder rev will be grabbed or how it is done. Everything else in composer world uses tag while flex seems to follow arbitrary rules. I must be missing some flag or something to properly pick correct recipe version.

I would appreciate any help to correct this.

Kind Regards, Dave

**Comment by dspiegel** [comment]
Anyone? Unable to properly test move to 4.4 without testing correct recipe version.

**Comment by maxhelias** [comment]
Maybe the minimum stability ? Are you using it to allow to get dev dependencies ?
https://getcomposer.org/doc/04-schema.md#minimum-stability

**Comment by dspiegel** [comment]
@maxhelias 
Project and all bundles install just fine with the 4.4.x-dev. It's the Flex recipes that are installing with incorrect version. Flex installs the 4.3.x folder version of recipes and not the 4.4.x folder.

Here is summary of my project:

1. create project my-starter-app:4.4.x-dev  (branch 4.4)
     a. starter-app pack loads 6 private bundles @4.4.x-dev  (branch 4.4)
     b. One of those bundles will require the needed symfony/* at version 4.4.*
     c. All packages install with expected versions. My bundles all show 4.4.x-dev version
     d. Flex starts recipe configuration. All of my bundles which have recipes, configure incorrect recipe from 4.3.x recipe folder instead of 4.4.x recipe folder.

Install fails due to incorrect yaml config files for my bundles.

I have found a work around to complete my testing. I have created a 4.4.0 tag for each of my 4.4 branch bundles. Flex now installs correct recipe folder version. I do not feel comfortable doing this as it will require removing the tags each time I change code until I am ready to merge branch back into master and release.

Hopefully I have explained enough to understand the issue with Flex or perhaps I am doing something wrong with Git branches/tags. Maybe I need to also create branch for flex recipes? It's just not clear.

Thanks, Dave

**Comment by maxhelias** [comment]
Sorry i misunderstood 😅

**Comment by nicolas-grekas** [comment]
I'm not sure how this works - are your recipes private? We don't support private recipes so not sure that's something we can help you with on this repository.
An idea still: check that `dev-master` is correctly aliases in the `branch-alias` section of your composer.json file. That's where flex (and composer) look to approximate which current version is installed.

**Comment by dspiegel** [comment]
@nicolas-grekas thanks for info. I do not have a branch-alias section. This is good info, because as I said flex is a bit of mystery as to how it selects recipe version. 
How should branch-alias definition look or can you point me to good reference that explains usage?

**Comment by nicolas-grekas** [comment]
I think the doc of composer is the best place to start:
https://getcomposer.org/doc/articles/aliases.md#branch-alias
