### ISSUE TITLE
Bundle doesn't put himself in bundles.php after composer require

### ISSUE THREAD

**Issue by voodooism** [symfony/flex#601]
I'm developing several bundles for my project now, and I've noticed a strange thing.
Some bundles put themself in bundles.php file, but some others not. And I can't figure out what it depends on.

I attached two composer.json files first which works and the second not. I hid some details

```
{
    "name": "me/package-name-bundle",
    "type": "symfony-bundle",
    "description": "description",
    "license": "proprietary",
    "authors": [
        {
            "name": "My Name",
            "email": "my@email.com"
        }
    ],
    "require": {
        "php": "^7.1.3"
    },

    "autoload": {
        "psr-4": { "App\\MyNameSpace\\": "src/" }
    }
}
```

```
{
  "name": "me/package-name-two-bundle",
  "type": "symfony-bundle",
  "description": "description",
  "license": "MIT",
    "authors": [
        {
            "name": "My Name",
            "email": "my@email.com"
        }
    ]

  "require": {
    "php": "^7.2"
  },

  "require-dev": {
  },

  "suggest": {
  },

    "autoload": {
        "psr-4": { "App\\MyNameSpace\\": "src/" }
    }

    "autoload-dev": {
        "psr-4": { "App\\MyNameSpace\\Tests\\": "src/" }
    }
}
```

Anyway, I can't figure out what it depends on and can't find it in the documentation?
Can anybody explain to me is it bug or I do something wrong?

**Comment by voodooism** [comment]
Is there any dependency between package name and a main class of bundle(which extends Symfony\Bundle)?
In other words, may it happens because my bundle class name is `MySoLongBundleNameBundle` but the project name in composer.json is just `vendor/bundle-name-bundle`?

**Comment by andrew-demb** [comment]
> Is there any dependency between package name and a main class of bundle(which extends Symfony\Bundle)?
Yes

You can see logic for auto-generated recipes here:
https://github.com/symfony/flex/blob/b13714e1d598758711e8c785d545f0460314ba4f/src/SymfonyBundle.php#L33

And here
https://github.com/symfony/flex/blob/b13714e1d598758711e8c785d545f0460314ba4f/src/Flex.php#L761-L776

**Comment by kbond** [comment]
I have also run into this. I thought flex looked for any class that is a bundle recursively but found it only looks at the root of your bundle's configured autoload path (src). Then it only looks for `<YourNamespaceBundle>`.

I had my bundle in `src/Bundle/MyBundle` and flex did not find it.
