### ISSUE TITLE
[Symfony Flex Server] 404 error right after installation

### ISSUE THREAD

**Issue by ablaise** [symfony/flex#603]
Hello,

When installing Symfony Flex Server, I came across a 404 error which seems to trigger errors when validating a pull request.

> https://flex.symfony.com/z/registered?installation_id=xxx&setup_action=install
> 404 page not found

Any pull request gives the following result when used on a normally valid recipe.

![pullrequest](https://user-images.githubusercontent.com/8725004/72990357-4eb2af80-3df0-11ea-8309-e63b1d612692.png)

![invalidpullrequest](https://user-images.githubusercontent.com/8725004/72990386-57a38100-3df0-11ea-8b44-c7261fc7ea65.png)

It says that the pull request does not exist while I am working on it. I did not have this error on older versions of Symfony Flex Server, which is why I think the 404 error causes this issue with fresh installations.

It doesn't seem to be related to a problem on my github account because I tried with other accounts and the error remains the same.

**Comment by topwebstudio** [comment]
This will also happen if you try to register new Flex private repository.

**Comment by ablaise** [comment]
> This will also happen if you try to register new Flex private repository.

Indeed, I was referring to private repository.

**Comment by emgolubev** [comment]
I have the same issue

**Comment by fabpot** [comment]
Support for private repos has been discontinued as there was no interests.

**Comment by emgolubev** [comment]
> Support for private repos has been discontinued as there was no interests.

Thank you for answer

**Comment by emgolubev** [comment]
> Support for private repos has been discontinued as there was no interests.

@fabpot I just tried it on public repo and got the same result :( 
https://flex.symfony.com/r/github.com/oat-sa/recipes-flex/1

```
Validation status is not available
The pull request does not exist, is closed, or has already been merged.
```

**Comment by fabpot** [comment]
When I said private repository, I was referring to symfony/recipes and symfony/recipes-contrib vs any other repos.

**Comment by emgolubev** [comment]
@fabpot do you support only `symfony/recipes` and `symfony/recipes-contrib`? In my case do I need to create my flex server?

**Comment by NicolasGuilloux** [comment]
I just spent 2 hours trying to make it work for our private bundles until I found this issue. I guess I followed an aged tutorial. It could be really great to disable the Github Apps or at least to warn the user that this feature is no longer available.

At least, please change the error which does not tell anything useful to understand the situation.

![image](https://user-images.githubusercontent.com/4090627/82645272-e72c3580-9c12-11ea-8178-d24fecc4c8fd.png)
