### ISSUE TITLE
Legacy Tags are not removed when using Satis

### ISSUE THREAD

**Issue by b-viguier** [symfony/flex#608]
Hello 👋 😃 
I'm facing an unexpected behavior when using Flex with our internal Satis: Flex doesn't achieve to restrict packages listed in "symfony/symfony" when I have packages in an upper version in Satis.
Example: expecting to restrict to version `4.4`, but since I have `5.0` packages in Satis, Flex is still installing `5.0` packages from Satis.

I created a project from scratch `composer create-project symfony/website-skeleton:^4.4 my_project_name`, then I added my Satis and performed a `composer update` with XDebug and here results of my investigations…

* Packages are correctly filtered by Flex when Composer call [`computeWhatProvides`](https://github.com/composer/composer/blob/e5b948c683e98ed2618431456ad447d0d7c8d209/src/Composer/DependencyResolver/Pool.php#L199), but it merges filtered packages with [`packageByExactName` or `packageByName` list](https://github.com/composer/composer/blob/e5b948c683e98ed2618431456ad447d0d7c8d209/src/Composer/DependencyResolver/Pool.php#L214-L221)
* These lists are computed in `addRepository`, from a call to [`getPackages`](https://github.com/composer/composer/blob/e5b948c683e98ed2618431456ad447d0d7c8d209/src/Composer/DependencyResolver/Pool.php#L104)
* Unfortunately, in this case the `Cache` class cannot apply packages filtering since it's expecting a missing [provider prefix `provider-symfony$`](https://github.com/symfony/flex/blob/master/src/Cache.php#L44). 
* This suffix is set by [Composer itself](https://github.com/composer/composer/blob/master/src/Composer/Repository/ComposerRepository.php#L340), but seems applied only when looking for a specific package, not when listing all packages…

If I remove the `0 === strpos($file, 'provider-symfony$')` test it works as expected, but I guess that it's done for performance issues 🤔 

What do you think about it? Is there a better way to apply packages filtering in composer?
Thanks for you work 👍

**Comment by nicolas-grekas** [comment]
How does this work with composer 2?
Would you be able to fix this? We need someone with an actual Satis server to fix this...

**Comment by b-viguier** [comment]
Seems fixed with composer 2.

Here both procedures/results.

```
composer create-project symfony/website-skeleton:^4.4 my_project_name2
```
I edit `composer.json` to add satis repository
```
composer update
```

## Composer 1


<details>
<summary>In output we see that some libraries are updated from 4.4 to 5.2</summary>
<p>

```
Warning from https://repo.packagist.org: You are using an outdated version of Composer. Composer 2 is now available and you should upgrade. See https://getcomposer.org/2
Loading composer repositories with package information
Warning from https://repo.packagist.org: You are using an outdated version of Composer. Composer 2 is now available and you should upgrade. See https://getcomposer.org/2
Updating dependencies (including require-dev)
Restricting packages listed in "symfony/symfony" to "4.4.*"
Package operations: 2 installs, 15 updates, 0 removals
  - Updating symfony/finder (v4.4.20 => v5.2.4): Loading from cache
  - Updating symfony/http-foundation (v4.4.20 => v5.2.4): Loading from cache
  - Updating symfony/routing (v4.4.20 => v5.2.4): Loading from cache
  - Updating symfony/filesystem (v4.4.20 => v5.2.4): Loading from cache
  - Updating symfony/config (v4.4.20 => v5.2.4): Loading from cache
  - Updating symfony/dependency-injection (v4.4.20 => v5.2.4): Loading from cache
  - Updating symfony/dom-crawler (v4.4.20 => v5.2.4): Loading from cache
  - Updating symfony/var-exporter (v4.4.20 => v5.2.4): Loading from cache
  - Updating symfony/cache (v4.4.20 => v5.2.4): Loading from cache
  - Updating symfony/options-resolver (v4.4.20 => v5.2.4): Loading from cache
  - Installing symfony/polyfill-intl-grapheme (v1.22.1): Loading from cache
  - Installing symfony/string (v5.2.4): Loading from cache
  - Updating symfony/inflector (v4.4.20 => v5.2.4): Downloading (100%)         
  - Updating symfony/mime (v4.4.20 => v5.2.4): Loading from cache
  - Updating monolog/monolog (1.26.0 => 2.2.0): Loading from cache
  - Updating symfony/monolog-bridge (v4.4.20 => v5.2.4): Loading from cache
  - Updating symfony/security-csrf (v4.4.20 => v5.2.4): Loading from cache
Writing lock file
Generating autoload files
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
```
</p>
</details>

## Composer 2

<details>
<summary>Output is pretty clear, nothing is updated</summary>
<p>

```
Loading composer repositories with package information
Restricting packages listed in "symfony/symfony" to "4.4.*"
Updating dependencies
Nothing to modify in lock file
Writing lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
Generating autoload files
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
```
</p>
</details>

Not sure if it worth the time to try to fix this since everything is OK with composer 2… Could be closed from my point of view 👍

**Comment by fabpot** [comment]
I would vote to close if it works with Composer 2.
