### ISSUE TITLE
Symfony.lock php version save the current php version instead of the composer.json's one

### ISSUE THREAD

**Issue by fredpeaks** [symfony/flex#609]
When a new dependency is added via `composer require`, the symfony.lock file is updated and the "`php version`" section is updated with the current used php version. This leads to problems if the version is superior to the one required in composer.json and different of the version used when a `composer install` is called on another machine (`Fatal Error: composer.lock was created for PHP version ...`).
Symfony.lock should save the version that is indicated in composer.json and not the current one.

**Comment by weaverryan** [comment]
Hi!

What do you mean specifically by “the version that is indicates in composer.json”? Are you referring to the PHP version under require? Or the config.platform.php version? If the latter, I believe that’s exactly how it works - I just set my config.platform.php a few days ago in a composer.json and, after a composer update, symfony.lock had been updated to the new PHP version (the one matching what I added to composer.json).

Cheers!

**Comment by fredpeaks** [comment]
Hi ! Thanks for your reply.
I was talking about the php version set under the require section of composer.json. But I didn't knew that the config.platform.php section was here to solve this kind of problems. I'm gonna try it as soon as possible.
But I still think it's weird that symfony.lock behave differently than composer.lock regarding to the php version (and weirder the error message saying that `composer.lock was created for PHP version 7.3` when composer.lock refers to php 7.2 and the server running the `composer install` command is in php 7.2 which is the required version in composer.json).
Maybe there is a good reason for that behavior but I don't see it right now.

**Comment by fredpeaks** [comment]
Setting the config.platform.php fixes the problem. Thanks @weaverryan.

**Comment by xabbuh** [comment]
Let's close then. Thank you for the feedback @fredpeaks. 👍
