### ISSUE TITLE
[Question] What about use flex local, without internet 

### ISSUE THREAD

**Issue by pcabreus** [symfony/flex#61]
Should be an official recipe, ok, I agreed with that. But in my case, to really use flex I will need to use it in local, with my satis repository. Can I do it? What I'll need to do for having a 172.0.0.1:8123/recipes with a local copy of the official recipe.
With this I could even have my own recipies without using the official repository.

**Comment by sstok** [comment]
Flex is really new so it's not yet possible to install a local Flex server at the moment.

**Comment by stof** [comment]
The flex plugin does not read from the recipe repository directly but from an API. And the flex server (not open-source currently) is processing the recipes config files.

So for now, it is not possible.

**Comment by stof** [comment]
if you reverse-engineer the format of the API based on the plugin source code, you may build a compatible API though, and use it, as the flex plugin supports specifying a custom endpoint (which is how you can test your PRs on the recipe repository btw).
But the API of the flex server is still in alpha state currently, and may change at any time (without backward compatibility promise), so I would not advice doing it.

**Comment by pcabreus** [comment]
Copied
