### ISSUE TITLE
Don't execute indirect recipies

### ISSUE THREAD

**Issue by Nemo64** [symfony/flex#613]
If you get a library, that has a recipe, though a dependency, then flex will execute that recipe even though it isn't relevant for the current project. See https://github.com/brefphp/bref/issues/619

Is there an opt-out for indirect dependencies or a way for a library author to declare that this isn't intentional?

**Comment by fabpot** [comment]
A recipe is about modifying files and adding new ones. If you don't accept the changes, you're all good.

**Comment by Nemo64** [comment]
Sure, and when you explicitly install a library it is awesome 👍 

The problem is when I get changes from a library I didn't _explicitly_ install.

I described the problem in the bref issue: https://github.com/brefphp/bref/issues/619#issuecomment-613330183

> - ignore it, in which case my project now has an implicit dependency to Nyholm/psr7 and will break should this dependency not be required anymore
> - remove that config file but for that I (hypothetical user that hasn't done the research yet) would have to figure out why it was even created, what it does and that I don't need it
> - embrace it and properly create a hard dependency to Nyholm/psr7 because my project now has a config file wich depends on that library being there.

I think in most cases, flex probably shouldn't executed recipes that aren't direct dependencies of the root project. Maybe with a configuration in the composer.json to change that within a library for a dependency.

**Comment by stof** [comment]
Well, if the dependency is removed, Flex will also clean the files created by the recipe.

**Comment by Nemo64** [comment]
Oh, I didn't know that. 👍 

So the "ignore it" option it is.
Still not the most beautiful behaviour i think.

**Comment by stof** [comment]
Ignoring the indirect dependencies would make packs useless. Packs are meta-packages bringing you a bunch of related packages together (for instance, we have an `orm-pack` which installs doctrine-bundle and the doctrine ORM, and a `debug-pack` which installs various debugging tools). If indirect recipes are not applied, these tools would be installed but not configured.

**Comment by Nemo64** [comment]
Good point. 

And any configuration to make that process explicit (composer key etc) would break compatibility with existing packs.

Then I'm out of ideas here.

**Comment by nicolas-grekas** [comment]
Closing then :)
