### ISSUE TITLE
Prevent configuration to overwrite recipies of dependent bundle

### ISSUE THREAD

**Issue by gseidel** [symfony/flex#620]
In some situations, it might be useful to have control over other recipes.

For example:
* I want to add my own ``webpack.config.js`` instead of the one from ``WebpackEncoreBundle``.
* I don't want to have a ``assets/js/app.js`` file from the ``WebpackEncoreBundle``.

Of course, if the files are already there before i add my bundle, it shouldn't change it contents.

But if my bundle has a dependency to ``WebpackEncoreBundle`` and therefor it will be installed automatically if my bundle is added, then my own files should be installed instead.

I suggest a configuration in the ``manifest.json`` like:

```
"prevent": {
  "symfony/webpack-encore-bundle": {
    "files": ["webpack.config.js", "assets/js/app.js"]
  }
}
```

So this files will be not be installed if ``WebpackEncoreBundle`` recipe is executed. 

Additional valid checkers may check if the prevent bundle is a true dependency of my bundle.

Maybe there is some other ways to handle that, then please give me some hints. Thanks.

**Comment by aleksblendwerk** [comment]
This sounds like a feature I am looking for right now as well, just in a different context (I'd like to define a custom `phpcs.xml.dist` in a recipe for our own coding standards package instead of ending up with the one from the `squizlabs/php_codesniffer` recipe).

**Comment by aleksblendwerk** [comment]
My plan was to set something up that ensures a common base configuration for all our developers. I have given up on doing it the flex way now (as it is actually not very, ehm, flexible), using `composer create-project` with a customized version of `symfony/website-skeleton` instead which seems more suited to the task.

**Comment by nicolas-grekas** [comment]
> using composer create-project with a customized version of symfony/website-skeleton instead which seems more suited to the task

looks like the way to do it!
let's keep flex simple...
