### ISSUE TITLE
--no-suggest option is deprecated in Composer 2

### ISSUE THREAD

**Issue by emodric** [symfony/flex#634]
Flex sets the `--no-suggest` option to `true` in https://github.com/symfony/flex/blob/master/src/Command/UpdateCommand.php#L35.

However, this option is deprecated in Composer 2, resulting in `You are using the deprecated option "--no-suggest". It has no effect and will break in Composer 3.` notice being printed in the output.

**Comment by nicolas-grekas** [comment]
good catch, would you mind sending a PR to fix that? this check might do it:
`version_compare('2.0.0', PluginInterface::PLUGIN_API_VERSION, '>')`

**Comment by emodric** [comment]
Shouldn't it be `>=` ?

**Comment by emodric** [comment]
or rather '<', if we want to set the option to `true` only for 1.0?

**Comment by nicolas-grekas** [comment]
the one I pasted meand `2.0.0 > PluginInterface::PLUGIN_API_VERSION`, so it means composer 1

**Comment by emodric** [comment]
Ah, okay. Will PR soon!

**Comment by emodric** [comment]
@nicolas-grekas PR done!
