### ISSUE TITLE
No lockfile found. Unable to read locked packages

### ISSUE THREAD

**Issue by lpfrenette** [symfony/flex#660]
I have this error when running 

```bash
composer install --verbose --prefer-dist --no-progress --no-interaction --no-dev --no-suggest  --unpack
```

it was woking 30 minutes ago and stopped working without any changes to composer.json

Extracting archiveSymfony operations: 1 recipe (2486b6da020382c162774d5a53e29a25)
  - Configuring symfony/flex (>=1.0): From github.com/symfony/recipes:master
    Copying files from recipe

                                                     
  [LogicException]                                   
  No lockfile found. Unable to read locked packages

**Comment by nicolas-grekas** [comment]
Fixed in v1.9.1
