### ISSUE TITLE
Composer now unpacks by default ?

### ISSUE THREAD

**Issue by sarramegnag** [symfony/flex#665]
Hi everyone,

Not sure if this is an issue and where I should post it, but I noticed something weird (maybe I'm late or wrong).

When I add a pack with `composer req mypack`, the pack is automatically unpacked in my composer.json file. Is this normal ? I don't remember this was the default behaviour (as in http://fabien.potencier.org/symfony4-unpack-the-packs.html).
If I want to add a pack without unpacking it, I must specify --no-unpack option in composer command line.

**Step to reproduce :**
```bash
composer create-project symfony/skeleton project
cd project
composer req orm
```
Check that composer.json has 4 packages (composer/package-versions-deprecated, doctrine/doctrine-bundle, doctrine/doctrine-migrations-bundle, doctrine/orm) instead of 1 (symfony/orm-pack).

If I use this, it works as expected :
```bash
composer create-project symfony/skeleton project
cd project
composer req orm --no-unpack
```

Maybe I'm late and missed a post explaining this is now the default behaviour. Is unpacking now the expected behaviour ?

Guillaume

**Comment by BoShurik** [comment]
See https://github.com/symfony/flex/issues/645

**Comment by sarramegnag** [comment]
Thank you, I was sure I missed something 😅
