### ISSUE TITLE
Installing packs can lead to dependencies both in require and require-dev

### ISSUE THREAD

**Issue by dunglas** [symfony/flex#674]
I installed the api, orm, debug and profiler packs, and I ended with `twig-bundle` both in the `require` and `require-dev` sections.
If a package is already present in the `require` section, it shouldn't be added to `require-dev`.

**Comment by lyrixx** [comment]
Duplicate of https://github.com/symfony/flex/issues/654 ?

**Comment by weaverryan** [comment]
Actually, I think duplicate of #597, which nicely has a PR #673. But I also still want #654 :)
