### ISSUE TITLE
Composer version requirement

### ISSUE THREAD

**Issue by Pierstoval** [symfony/flex#68]
After testing, it seems that Flex is compatible with Composer 1.3.1+ (I had an error with 1.3.0 when installing symfony/stopwatch, not sure it comes from composer though, and installing any bundle with 1.2 didn't work).

How can we tell, when installing Flex, that the user needs to upgrade its composer version if it's not compatible?

**Comment by stof** [comment]
Which kind of error do you get with composer 1.2 ?

**Comment by Pierstoval** [comment]
It's an error related to the `--no-suggest` option 😕 

```bash
pierstoval@PIERSTOVAL /mnt/e/dev/www/flex_tests/cms (master) $ composer -V
Composer version 1.2.4 2016-12-06 22:00:51
pierstoval@PIERSTOVAL /mnt/e/dev/www/flex_tests/cms (master) $ composer req orbitale/cms-bundle -vvv
Reading ./composer.json
Loading config file ./composer.json
Checked CA file /etc/ssl/certs/ca-certificates.crt: valid
Executing command (/mnt/e/dev/www/flex_tests/cms): git branch --no-color --no-abbrev -v
Failed to initialize global composer: Composer could not find the config file: /home/pierstoval/.composer/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Reading /mnt/e/dev/www/flex_tests/cms/vendor/composer/installed.json
Loading plugin Symfony\Flex\Flex
Running 1.2.4 (2016-12-06 22:00:51) with PHP 7.1.4-1+deb.sury.org~xenial+1 on Linux / 3.4.0+


  [Symfony\Component\Console\Exception\InvalidArgumentException]
  The "no-suggest" option does not exist.


Exception trace:
 () at phar:///home/pierstoval/bin/composer/vendor/symfony/console/Input/Input.php:169
 Symfony\Component\Console\Input\Input->setOption() at /mnt/e/dev/www/flex_tests/cms/vendor/symfony/flex/src/Command/RequireCommand.php:33
 Symfony\Flex\Command\RequireCommand->execute() at phar:///home/pierstoval/bin/composer/vendor/symfony/console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at phar:///home/pierstoval/bin/composer/vendor/symfony/console/Application.php:847
 Symfony\Component\Console\Application->doRunCommand() at phar:///home/pierstoval/bin/composer/vendor/symfony/console/Application.php:192
 Symfony\Component\Console\Application->doRun() at phar:///home/pierstoval/bin/composer/src/Composer/Console/Application.php:231
 Composer\Console\Application->doRun() at phar:///home/pierstoval/bin/composer/vendor/symfony/console/Application.php:123
 Symfony\Component\Console\Application->run() at phar:///home/pierstoval/bin/composer/src/Composer/Console/Application.php:104
 Composer\Console\Application->run() at phar:///home/pierstoval/bin/composer/bin/composer:43
 require() at /home/pierstoval/bin/composer:24

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--] [<packages>]...
```

**Comment by stof** [comment]
ah, then we might detect it in flex (composer exposes its version AFAIK)

**Comment by Pierstoval** [comment]
It's hard to say if it comes from my environment, but maybe we could customize Flex's test suite and test it with different composer versions?

**Comment by javiereguiluz** [comment]
On the Symfony Slack we've just received another bug report about this:

```
And now I try to run:

$ composer req cli

but I got:

 [Symfony\Component\Console\Exception\InvalidArgumentException]
 The "no-suggest" option does not exist.
```

He was using this:

```
ubuntu@ubuntu-xenial:/vagrant/public/demo$ composer --version

You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
Composer version 1.2.4 2016-12-06 22:00:51
```

After upgrading to Composer 1.3, everything works again.

**Comment by Pierstoval** [comment]
Just to say, the man who had the error was using Composer `1.2.4`.
Maybe we could even try to fix this instead of making composer requirement higher, actually 😕

**Comment by sstok** [comment]
One should always to use the last stable version, unless the technical requirements of Composer 1.4.1 are way more different then those of 1.2.4?

**Comment by javiereguiluz** [comment]
I'm not asking that Flex works with old Composer versions. But if there's a simple way to detect that Composer is old and Flex is not going to work, we could display a better error message.

**Comment by francoispluchino** [comment]
@javiereguiluz This is possible during activation of theplugin in `Symfony\Flex\Flex::activate()`. We can check the version of composer with `Composer\Composer::VERSION`, and throw an exception from the beginning.

**Comment by stof** [comment]
but throwing an exception there may even prevent people from running `composer selfupdate` (as installed plugins are initialized before running commands, to allow registering commands)

**Comment by francoispluchino** [comment]
Of course, we throw the exception only for the commands `install`, `update`, `require`. So no problem for `selfupdate`.

**Comment by francoispluchino** [comment]
In this case, it's better to listen the `Composer\Plugin\PluginEvents::COMMAND` event, and get the command name with `Composer\Plugin\CommandEvent\CommandEvent::getCommandName()` before doing the check of the Composer version.

**Comment by francoispluchino** [comment]
However, it may be preferable to display a warning indicating that it is advisable to use a version of Composer instead of displaying an error message. No?

**Comment by fabpot** [comment]
A first step could be to support Composer 1.2. If the issue is just the `--no-suggest` flag, let's fix that.

**Comment by stof** [comment]
And that would be easy: do the composer version check in the overwritten UpdateCommand, to skip forcing the option when using Composer 1.2

**Comment by Pierstoval** [comment]
And here it is #79
