### ISSUE TITLE
"[ErrorException] Undefined index: extra" during project creation

### ISSUE THREAD

**Issue by Yoann-TYT** [symfony/flex#686]
When I try to create a new project on Symfony with this command 

```sh 
composer create-project symfony/skeleton hello -vvv
```

I get this error : 

```sh
                          
  [ErrorException]        
  Undefined index: extra  
                          

Exception trace:
 () at /XXXXX/.composer/vendor/symfony/flex/src/Cache.php:93
 Composer\Util\ErrorHandler::handle() at /XXXXX/.composer/vendor/symfony/flex/src/Cache.php:93

```

If I remove composer.lock and symfony.lock inside this new project, and try a "composer install", everything is going well.

PHP 7.4.3
Composer version 1.10.13

Thank you :)

**Comment by nicolas-grekas** [comment]
Likely the same as #683, check solution there.

**Comment by Yoann-TYT** [comment]
Thank you Nicolas !
