### ISSUE TITLE
Install Issue 

### ISSUE THREAD

**Issue by fvsadem** [symfony/flex#690]
Hi,

I have a symfony 4.3.11 project with flex.
When i would like to install dependency, it failed with flex installation.
``composer.phar install``

```  
  - Installing symfony/flex (v1.4.1): Downloading (100%)
Plugin installation failed (Invalid version string "5.x"), rolling back
  - Removing symfony/flex (v1.4.1)


  [UnexpectedValueException]
  Invalid version string "5.x"
```

I don't understand what's appended, two days ago it works great.

Could you help me ?

**Comment by nicolas-grekas** [comment]
Sure, check #683

**Comment by fvsadem** [comment]
@nicolas-grekas 

Thanks for the infos.

When i try to update flex i have the same result :

```
[UnexpectedValueException]
  Invalid version string "5.x"
```

**Comment by nicolas-grekas** [comment]
Did you try https://github.com/symfony/flex/issues/683#issuecomment-704233439?

**Comment by fvsadem** [comment]
Yes i try remove vendor/symfony and update flex

**Comment by nicolas-grekas** [comment]
maybe you have flex installed globally?
`composer global update --no-scripts` maybe?

**Comment by fvsadem** [comment]
@nicolas-grekas 
It's OK... i had to delete vendor/symfony twice !
Maybe some files did not been removed the first one...

Thanks for your help
