### ISSUE TITLE
Composer 2 compat issue

### ISSUE THREAD

**Issue by Seldaek** [symfony/flex#694]
I am not sure what is causing this, not familiar enough with flex internals, but I just tried creating a new symfony project, then adding twig with `composer require twig`, which added this mess of constraints to my composer.json:

```
        "symfony/twig-bundle": "[>= 5.1.0.0-dev < 5.2.0.0-dev]",
        "symfony/yaml": "5.1.*",
        "twig/extra-bundle": "[>= 2.12.0.0-dev < 4.0.0.0-dev]",
        "twig/twig": "[>= 2.12.0.0-dev < 4.0.0.0-dev]"
```

That's the __toString representation of MultiConstraints, but I don't know how they ended up there. Could be due to optimizations we are doing in Composer 2, due to that not all constraints have a pretty constraint attached to them.. Happy to help resolve this if you can identify where it's going wrong.

**Comment by nicolas-grekas** [comment]
See workaround in #695

Looks like we had a dream and it broke :)

We thought `Intervals::compactConstraint()` would resolve unions/intersections and generate back a semver contraint, e.g `^5.1` or `5.1.*` instead of `[>= 5.1.0.0-dev < 5.2.0.0-dev]`.

If it's possible to do this, that'd be super nice btw ;)

**Comment by Seldaek** [comment]
Ok I see, it probably worked with very simple constraints but then started breaking as soon as it compacted to a multiconstraint. Anyway I'll see if we can do something about this in semver, but I doubt this can really be solved 100%.

What you can for sure do though is to use Intervals::isSubsetOf to check if A is within B or B within A, and if so then you can discard the one that is a subset of the other, and know that you kept the broader constraint. For most cases this should already help a little. Alternatively you can concatenate all constraints with `implode(' || ', array_unique($link['constraints']))` but that would risk getting messy in the output, although correct.
