### ISSUE TITLE
PHP version not updated in symfony.lock after installing with Composer v2

### ISSUE THREAD

**Issue by lchrusciel** [symfony/flex#708]
With composer v1, when one was installing the current project, but symfony.lock was generated with a different PHP version, flex was able to update this value. After bumping composer to v2 this feature does not work anymore. This leads to surprising exceptions like: 
```
Fatal Error: composer.lock was created for PHP version 7.X or higher but the current PHP version is 7.Y
```
Where X > Y, but both are correct according to composer.json. 

### How to reproduce?

1. Have symfony.lock generated with a higher version of PHP that your current runtime
2. Have composer v2
3. Run composer install/update
4. Exception will be thrown with any Symfony command.

**Comment by lchrusciel** [comment]
After symfony.lock is originally generated with a higher PHP version, the composer will not change PHP version even during composer update and with `config.platform.php` defined. I have to downgrade to composer v1, or manually update symfony.lock to have the desired outcome(being able to run Symfony commands).

**Comment by lchrusciel** [comment]
Perhaps related to #609

**Comment by stlrnz** [comment]
Similar problem here.
After updating my project from PHP 7.3 to 7.4 the PHP version recorded in symfony.lock is still 7.3.

It seems like Flex is only updateting the platform version when running with Composer 1.
https://github.com/symfony/flex/blob/e472606b4b3173564f0edbca8f5d32b52fc4f2c9/src/Flex.php#L1015

While this does not prevent me from running my project using PHP 7.4, it does not protect me from running it with 7.3 (which is not compatible anymore) either.

**Comment by stof** [comment]
for composer 2, you can rely on the built-in composer feature to check the platform instead of making Flex check it.

**Comment by stlrnz** [comment]
Okay, so the PHP version recorded in my symfony.lock will forever be the last PHP version I used before upgrading to Composer 2?
That seems confusing to me.

**Comment by stof** [comment]
@nicolas-grekas should we remove the PHP version from the symfony.lock entirely when running on composer 2 ?

**Comment by GPHemsley-RELX** [comment]
@stof @nicolas-grekas Any update here? I too was confused by this.

**Comment by nicolas-grekas** [comment]
@stlrnz please do your homework. See #798

**Comment by stlrnz** [comment]
Don't be rude.
I was just wondering because you closed this after a long time without linking the solution.

**Comment by nicolas-grekas** [comment]
Assuming that I closed without a solution was also rude to me. Anyway, you're right, I should have linked to the PR while closing.

**Comment by stlrnz** [comment]
Sorry, it wasn't meant that way.
Anyway, thanks for the clarification and your efforts.
