### ISSUE TITLE
Opt In : strict type declaration in bundles.php

### ISSUE THREAD

**Issue by rrajkomar** [symfony/flex#710]
The generated bundles.php file does not use the `declare(strict_types=1);` instruction.
If added manually, the instruction is automatically removed upon new package installation (due to the file being regenerated).

Could you make it either permanent when added by the end user or provide an opt-in setting to include the instruction in the automated generation ?

**Comment by nicolas-grekas** [comment]
Hi, there is no point in making this file "strict" - there is no function call in it.
Adding an option to configure this would increase the complexity for no practical benefit.
Thanks for proposing.
