### ISSUE TITLE
Really difficult to update to a dev version

### ISSUE THREAD

**Issue by Jean85** [symfony/flex#712]
I have a Symfony 5.1 project with Composer 2, Flex and various components installed.

I would like to upgrade to the current `5.x` branch, because there's a PR that I need that is merged there but it's not included in the latest 5.2-BETA tag. Without Flex, I would `composer require symfony/symfony:dev-5.x`, but with multiple split components I imagined that it would be more complex...

I tried multiple aliases in `extra.symfony.require`, but it always said `Nothing to update`; to make it work, I had to set `"minimum-stability": "dev"` in my `composer.json`, and do a `composer update` listing ALL the installed components, transient dependencies included, because otherwise it would update all the other dependencies too to the latest `dev` version.
Using `--prefer-stable` would stop Symfony components from updating.

This is obviously a sub-optimal DX; am I missing something? Or is this something that could be improved?

**Comment by nicolas-grekas** [comment]
Do you have any suggestions? This looks like standard composer.json updates, isn't it?

**Comment by wouterj** [comment]
Instead of doing `composer update` with all Symfony packages, I recommend adding `"prefer-stable": true` and then setting `extra.symfony.require` to `5.2`.

**Comment by Seldaek** [comment]
@wouterj that would require you to upgrade all packages at once to 5.2-dev tho.. If you want to upgrade just one, why doesn't flex let you do it? IMO it's fairly simple, if flex sees the root package has a require/require-dev for symfony/foo in a version that does not intersect with the extra.symfony.require constraint, then it should not filter that package's versions.

Then you could leave the extra.symfony.require at 5.1, but if you explicitly require 5.x-dev for a given package it would let you install that.

**Comment by wouterj** [comment]
Oh, I definitely didn't want to say that there is nothing to improve here. I was just suggesting a better possible alternative of _"[...] and do a `composer update` listing ALL the installed components, transient dependencies included, because otherwise it would update all the other dependencies too to the latest `dev` version"_
(my knowledge of Composer and Flex internals is honestly way to low to have any useful opinion on the actual matter)

**Comment by Jean85** [comment]
> Instead of doing composer update listing all Symfony packages, I recommend adding "prefer-stable": true and then setting extra.symfony.require to 5.2. After this, you can run composer update without any extra arguments.

If that setting has the same efffect of `--prefer-stable`, it won't work. Prefer stable leaves the Symfony components without updates, since they are already stable, and the "suggested" contraint from `extra.symfony.require` is unstable.

> @wouterj that would require you to upgrade all packages at once to 5.2-dev tho..

That's my use case and what this issue is about though... Updating a single component should work in fact, and is no hassle, sure.

**Comment by Seldaek** [comment]
If you want to update them all then set extra.symfony.require to `5.2.*` if you want betas, or `5.*` if you want dev, then you'll have to adjust minimum-stability to dev or beta for it to work I suppose. I think that should work.

**Comment by nicolas-grekas** [comment]
Please all check https://github.com/symfony/flex/pull/713

**Comment by Jean85** [comment]
> If you want to update them all then set extra.symfony.require to 5.2.* if you want betas, or 5.* if you want dev, then you'll have to adjust minimum-stability to dev or beta for it to work I suppose. I think that should work.

That does work, but I still have to whitelist all Symfony components by hand, or ALL my dependencies get updated to dev/beta, and that's not what I want...

**Comment by Seldaek** [comment]
Yeah, that's where the prefer-stable:true suggestion from @wouterj comes into play. It keeps most things on stable then.
