### ISSUE TITLE
Unable to download recipes

### ISSUE THREAD

**Issue by mvaljento** [symfony/flex#718]
I'm trying to install symfony/messenger, but the recipes fail with the following error:

> Failed to download recipe: The "https://flex.symfony.com/p/symfony,redis-messenger,rv5.1.8,1603540917;symfony,messenger,rv5.1.8,1603540917;symfony,doctrine-messenger,rv5.1.8,1603540917;symfony,amqp-messenger,rv5.1.8,1603793473" file could not be downloaded (HTTP/2 500 )

The only difference I can see with my previous project where I installed the package succesfully was the version of Symfony Flex which was then 1.9.10 and is now 1.10.0. Symfony/messenger version is identical, so I suspect this to be a Flex issue.

**Comment by fabpot** [comment]
Oops, my bad, fixed now.
