### ISSUE TITLE
Integers in JSON

### ISSUE THREAD

**Issue by dkarlovi** [symfony/flex#72]
I had an issue in [contrib#15](https://github.com/symfony/recipes-contrib/pull/15/commits/d07c8d480e277ec467d988e7168ecdfe54c5f399) in which the validator says my JSON is invalid because it contains integers, but integers are valid in JSON.

Validation says only ["JSON files must be valid"](https://github.com/symfony/recipes#validation) so either documentation or validation needs to be fixed.

**Comment by fabpot** [comment]
The validator is right. An env variable value is always a string. So, that's not really a JSON restrictions, but more that the value must be a string.

**Comment by dkarlovi** [comment]
OK, so the docs should be fixed to reflect that.
