### ISSUE TITLE
Respect order when adding package to package.json

### ISSUE THREAD

**Issue by garak** [symfony/flex#726]
I installed a bundle using the recent feature of Symfony UX, and now I see a new package in `devDependencies` section of my package.json file.
It would be possible to get such new package added by respecting existing alphabetical order?

Example of what I get now:
```json
{
  "dependencies": {
    "bootstrap-sass": "^3.4.1",
    "jquery": "^3.5.1"
  },
  "devDependencies": {
    "@symfony/webpack-encore": "^0.33.0",
    "node-sass": "^4.14.1",
    "sass-loader": "^9.0.1",
    "@symfony/ux-chartjs": "file:vendor/symfony/ux-chartjs/Resources/assets"
  }
}
```

What I would like to get instead: 

```json
{
  "dependencies": {
    "bootstrap-sass": "^3.4.1",
    "jquery": "^3.5.1"
  },
  "devDependencies": {
    "@symfony/ux-chartjs": "file:vendor/symfony/ux-chartjs/Resources/assets",
    "@symfony/webpack-encore": "^0.33.0",
    "node-sass": "^4.14.1",
    "sass-loader": "^9.0.1"
  }
}
```

**Comment by stof** [comment]
given that both `yarn add` and `npm install --save` are using alphabetical order when modifying the package.json, I agree Flex should do it too.

**Comment by nicolas-grekas** [comment]
Makes sense to me. Would you be up for a PR @garak maybe?
