### ISSUE TITLE
Flex removes custom path packages in package.json

### ISSUE THREAD

**Issue by biomedia-thomas** [symfony/flex#727]
We have a symfony project that uses an npm dependency in this form:
` "@company/package": "file:vendor/company/package"`

Since feature #723 was merged flex will unconditionally remove this line from package.json (because removePackageJsonLinks deletes all such dependencies). It will not add it back because it was never designed to be used with symfony/ux.

**Comment by nicolas-grekas** [comment]
I suppose we're going to need some entries in `symfony.lock` to know which lines should be removed from `packages.json`? WDYT @tgalopin?
