### ISSUE TITLE
Support custom "main" controller key in package.json

### ISSUE THREAD

**Issue by core23** [symfony/flex#730]
The current `PackageJsonSynchronizer` supports different stimulus auto-updates (e.g. `enabled`, `autoimport`, ...) but does not support custom main controllers. This is needed if you create a bundle with multiple controllers.

```json
// /assets/package.json
{
    "name": "@acme/some-bundle",
    "symfony": {
        "controllers": {
            "foo": {
                "main": "dist/foo_controller.js",
                "webpackMode": "lazy",
                "enabled": true,
                "autoimport": []
            },
            "bar": {
                "main": "dist/bar_controller.js",
                "webpackMode": "lazy",
                "enabled": true,
                "autoimport": []
            }
        }
    }
}
```

**Comment by tgalopin** [comment]
Hum I'm not sure to understand, you can already use the key in a bundle (https://github.com/symfony/ux/blob/main/src/Chartjs/Resources/assets/package.json). What's your question?

**Comment by core23** [comment]
I thought the `main` entry needs to be copied to the `controllers.json` file to get this working. There was a config error in my project that started this confusion.
