### ISSUE TITLE
RecipesCommand fails if recipe is not installed

### ISSUE THREAD

**Issue by dontub** [symfony/flex#734]
Flex version: 1.11.0

Currently `composer recipes <package>` fails if the given package is not installed:
```
[ErrorException]                                     
Trying to access array offset on value of type null                                                       

Exception trace:
 () at [...]/vendor/symfony/flex/src/Command/RecipesCommand.php:186
 Composer\Util\ErrorHandler::handle() at [...]/vendor/symfony/flex/src/Command/RecipesCommand.php:186
 Symfony\Flex\Command\RecipesCommand->displayPackageInformation() at [...]/vendor/symfony/flex/src/Command/RecipesCommand.php:96
 Symfony\Flex\Command\RecipesCommand->execute() at phar:///usr/bin/composer/vendor/symfony/console/Command/Command.php:245
 [...]
 ```

This happens because `$recipeLock` is null in https://github.com/symfony/flex/blob/35bcd4d85f21de627524d4383779c4650d6317bf/src/Command/RecipesCommand.php#L186
If I change `$recipeLock['version']` to `($recipeLock['version'] ?? null)` in this line as well as in https://github.com/symfony/flex/blob/35bcd4d85f21de627524d4383779c4650d6317bf/src/Command/RecipesCommand.php#L195 the command runs with an output like this:
```
name             : <package>
version          : 
status           : recipe not installed
installed recipe : https:///tree//<package>/
latest recipe    : https://github.com/symfony/recipes/tree/master/<package>/<version>
recipe history   : https:///commits//<package>
```
It obviously makes no sense to print the lines starting with `installed recipe` and `recipe history` here. The `version` line might be hidden as well or show the latest recipe version.

I run into this problem after adding Flex to an existing project.

**Comment by maxhelias** [comment]
Flex handles cases where a package is not installed or the package does not have a recipe 🤔 
On the other hand, did you keep the symfony.lock file ? Or did you generate it the first time after you installed Flex?

**Comment by dontub** [comment]
symfony.lock was generated the first time when installing Flex and contained only this:
```
{
    "symfony/flex": {
        "version": "1.0",
        "recipe": {
            "repo": "github.com/symfony/recipes",
            "branch": "master",
            "version": "1.0",
            "ref": "c0eeb50665f0f77226616b6038a9b06c03752d8e"
        },
        "files": [
            ".env"
        ]
    }
}
```

**Comment by maxhelias** [comment]
Run : `composer recipes:install vendor/your_package --force -v` to intialize and update it ;)

**Comment by dontub** [comment]
I've already done that. Though I think the reported error shouldn't happen.
