### ISSUE TITLE
Upcoming Composer version (now in snapshot) gives errors at DotEnv dump

### ISSUE THREAD

**Issue by PhilETaylor** [symfony/flex#741]
After running `composer self-update --snapshot`  (which gives d3ba447b79e45d1130e5523224700b97541b16de) and then running `composer dump-env dev`  Im presented with

```
  [RuntimeException]
  Please run "composer require symfony/dotenv" to load the ".env" files configuring the application.
```

After downgrading to `composer self-update --stable` (which gives 2.0.9) it then works again.

Just a heads up that its going to stop working soon.

I debugged it to the point the autoloader.php, exists, but is not actually loaded so `if (!class_exists(Dotenv::class)) {` in `vendor/symfony/flex/src/Command/DumpEnvCommand.php:88` fails.

**Comment by Seldaek** [comment]
Without stack trace this isn't super helpful. Please run with `-v`.

I'll hold making a release for now until we can figure this out..

**Comment by PhilETaylor** [comment]
No worries - here you go. Im here all day if you have any more questions.

```
Exception trace:
 () at /var/www/current/vendor/symfony/flex/src/Command/DumpEnvCommand.php:88
 Symfony\Flex\Command\DumpEnvCommand->loadEnv() at /var/www/current/vendor/symfony/flex/src/Command/DumpEnvCommand.php:57
 Symfony\Flex\Command\DumpEnvCommand->execute() at phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php:245
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:835
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:185
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:310
 Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:122
 Composer\Console\Application->run() at phar:///usr/local/bin/composer/bin/composer:63
 require() at /usr/local/bin/composer:25
```

<img width="973" alt="Screenshot 2021-02-16 at 13 11 35" src="https://user-images.githubusercontent.com/400092/108067336-870ad880-7058-11eb-8c54-56971ff6ef4f.png">

**Comment by Seldaek** [comment]
This is the only change I can imagine would have an effect on a class_exists

@nicolas-grekas can you reproduce?

**Comment by nicolas-grekas** [comment]
https://github.com/composer/composer/commit/4c8149a33d9da7dd2bc3dbf90ebed2a2a8f68a8b

**Comment by Seldaek** [comment]
Yeah actually it makes sense.. if Flex is not requiring symfony/dotenv, then Composer will not autoload it for flex, as it doesn't seem required.

**Comment by nicolas-grekas** [comment]
Oh. Then how can a plugin know and use the dep of the app?

**Comment by Seldaek** [comment]
What is however not optimal is that we do not run the full autoloader of the project, I guess that might make sense when it is available. Not sure gotta think some more about this. Workaround here would be to check if `\Composer\InstalledVersions::hasPackage('symfony/dotenv') || class_exists(...)` I guess.

**Comment by nicolas-grekas** [comment]
The plugin instantiates the class normally, so that if `class_exists()` can't find the class, we cannot run the command.
I'm going to wait for your thoughts :)

**Comment by Seldaek** [comment]
Ah yes good point. Clearly I need to think more about this :D

**Comment by PhilETaylor** [comment]
Thanks both.
