### ISSUE TITLE
[ScriptExecutor] Ability to run Composer scripts

### ISSUE THREAD

**Issue by Wirone** [symfony/flex#743]
Currently it's not possible to call other scripts defined in `composer.json` from `auto-scripts` definition. `ScriptExecutor` supports only Symfony commands, PHP scripts or raw scripts. Consider something like this:

```json
{
     "scripts": {
        "auto-scripts": {
            "prepare-environment": "composer-script"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ],
        "prepare-environment": [
            "./bin/console cache:clear",
            // ... other scripts
        ],
    }
}
```

This would allow building better reusable scripts and automatic processes. Calling `composer prepare-environment` is much more clear than `composer auto-scripts` (with `"cache:clear": "symfony-cmd"` inside).

Alternative solution would be making `auto-scripts` configurable, so Flex would execute scripts from custom script like:

```json
{
     "scripts": {
        "prepare-environment": {
            "cache:clear": "symfony-cmd"
        },
        "post-install-cmd": [
            "@prepare-environment"
        ],
        "post-update-cmd": [
            "@prepare-environment"
        ],
    },
    "extra": {
        "symfony": {
            "auto-scripts-source": "prepare-environment"
        },
    }
}
```

**Comment by nicolas-grekas** [comment]
Would you like to work on a PR to implement this? Otherwise I'm afraid we might close.

**Comment by Wirone** [comment]
@nicolas-grekas I really would like to, but I don't see it happen in upcoming days/weeks since I've got newborn at home 🙂 If it does not bother you (issue is from February 😅) please leave it open for some time.

**Comment by nicolas-grekas** [comment]
For sure, congrats btw :)

**Comment by stof** [comment]
@Wirone if you want to be able to run `composer run prepare-environment` to run the Flex auto-scripts, there is a solution that already works:

```json
{
     "scripts": {
        "prepare-environment": [
            "@auto-scripts"
        ],
}
```

And if you need to call your own existing scripts after installs and updates, there is also a built-in Composer feature for that (which is how `auto-scripts` are triggered btw):

```json
{
     "scripts": {
        "auto-scripts": {},
        "post-install-cmd": [
            "@auto-scripts",
            "@prepare-environment"
        ],
        "post-update-cmd": [
            "@auto-scripts",
            "@prepare-environment"
        ],
        "prepare-environment": [
            "./bin/console cache:clear"
        ]
    }
}
```

**Comment by Wirone** [comment]
@stof I know :) But it's workaround ending with redundant definition (same scripts in `post-install-cmd` and `post-update-cmd`). Not a big deal, but can be slightly better 😉

**Comment by stof** [comment]
Well, I'd rather avoid making Flex abuse the `scripts` section of composer even more than today
