### ISSUE TITLE
The "symfony/flex" plugin was skipped because it is not compatible with Composer 2+

### ISSUE THREAD

**Issue by guillemba** [symfony/flex#744]
Full error: "The "symfony/flex" plugin was skipped because it is not compatible with Composer 2+. Make sure to update it to version 1.9.8 or greater."

I git cloned a Symfony5 project that used Composer 1.* to manage its dependencies. However, on my local computer I have Composer2+ installed. After cloning successfully, I ran "composer install" (it tried to install exact versions of composer.lock) and everything went well except for this message.

**Comment by nicolas-grekas** [comment]
you need to update flex - recent versions are compatible with composer 2
