### ISSUE TITLE
The symfony:dump-env does not take in account the testEnvs

### ISSUE THREAD

**Issue by cmodijk** [symfony/flex#747]
In this  https://github.com/symfony/symfony/pull/29129 PR the variabel `testEnvs` was introduced but the `symfony:dump-env` does not have a way to handle cases where the list of `testEnvs` is different.

**Comment by nicolas-grekas** [comment]
Starting with Symfony 5.3, when symfony/runtime is used the test envs can be defined in the `composer.json` file under the `extra.runtime.test_envs` entry.
That might be a good fit!
Still up for a PR?

**Comment by cmodijk** [comment]
Sure, will look into this soon.
