### ISSUE TITLE
Optionally show "auto-scripts" output

### ISSUE THREAD

**Issue by mbrodala** [symfony/flex#750]
Currently the output of `auto-scripts" commands is only displayed in case of an error.

However for some commands it would be useful if their output would be displayed always instead.

Example: a command which ensures a set of essential users exist in the database and outputs details about them if created. When used in `auto-scripts` the output is swallowed completely by Flex and requires developers to perform extra steps which where tried to be avoided in the first place using `auto-scripts`.

Moving the command from `auto-scripts` to `post-install-cmd` and an explicit `bin/console` before works fine but I wonder if it would make sense to have this supported natively by Flex.

**Comment by nicolas-grekas** [comment]
I'm closing as this didn't get much traction.

I would suggest to open an issue on composer instead if you think there should be a follow up: it could be interesting to allow silencing the output of an composer script unless an error happens.
