### ISSUE TITLE
Makefile configurator not triggering

### ISSUE THREAD

**Issue by dkarlovi** [symfony/flex#76]
In my [PR](https://github.com/symfony/recipes-contrib/pull/15), Makefile is not being added even though [it exists in the latest package version](https://github.com/dkarlovi/symfony-flex-docker/blob/473186eaa4400f0b48e0d474b6bcb133e10a1645/Makefile) (and also in `vendor/`).

I've tracked it down to [not being set in the Configurators array](https://github.com/symfony/flex/blob/master/src/Configurator.php#L49-L51), but couldn't figure out where it's supposed to come from, Flex server I guess? Maybe it's due to my package not being marked as a Symfony bundle in `composer.json`?

**Comment by sstok** [comment]
https://symfony.sh/r/main/60/m/lexik/jwt-authentication-bundle/2.3

```json
{
    "package": "lexik/jwt-authentication-bundle",
    "version": "2.3",
    "manifest": {
        "bundles": {
            "Lexik\\Bundle\\JWTAuthenticationBundle\\LexikJWTAuthenticationBundle": ["all"]
        },
        "copy-from-recipe": {
            "etc/": "%ETC_DIR%"
        },
        "env": {
            "JWT_PRIVATE_KEY_PATH": "%ETC_DIR%/jwt/private.pem",
            "JWT_PUBLIC_KEY_PATH": "%ETC_DIR%/jwt/public.pem",
            "JWT_PASSPHRASE": "%generate(secret)%"
        },
        "makefile": ["generate-jwt-keys:", "ifeq (, $(shell which openssl))", "$(error \"Unable to generate keys (needs OpenSSL)\")", "endif", "\tmkdir -p etc/jwt", "\topenssl genrsa -passout pass:${JWT_PASSPHRASE} -out ${JWT_PRIVATE_KEY_PATH} -aes256 4096", "\topenssl rsa -passin pass:${JWT_PASSPHRASE} -pubout -in ${JWT_PRIVATE_KEY_PATH} -out ${JWT_PUBLIC_KEY_PATH}", "\t@echo \"\\033[32mRSA key pair successfully generated\\033[39m\""],
        "post-install-output": ["\u003cbg=blue;fg=white\u003e Next for LexikJWTAuthenticationBundle \u003c/\u003e", "    Run \u003ccomment\u003emake generate-jwt-keys\u003c/\u003e to generate a key pair."]
    },
    "files": {
        "etc/packages/lexik_jwt_authentication.yaml": {
            "contents": "lexik_jwt_authentication:\n    private_key_path: '%env(JWT_PRIVATE_KEY_PATH)%'\n    public_key_path:  '%env(JWT_PUBLIC_KEY_PATH)%'\n    pass_phrase:      '%env(JWT_PASSPHRASE)%'\n",
            "executable": false
        }
    }
}
```

The Makefile does come from the Flex server 👍

**Comment by sstok** [comment]
Note the the Makefile needs be on Recipe or else it can't be found.

**Comment by fabpot** [comment]
@sstok is right. The Makefile must be part of the recipe (see https://github.com/symfony/recipes/blob/master/symfony/framework-bundle/3.3/Makefile for instance).
