### ISSUE TITLE
Disable package.json synchronization for one package

### ISSUE THREAD

**Issue by Magiczne** [symfony/flex#762]
Let's suppose i have monorepo with 
- composer-package-a
  - npm-package
    - ...
    - package.json
  - ...
  - composer.json
- symfony-flex-app
  - ...
  - composer.json
  - package.json

`symfony-flex-app` composer.json requires `composer-package-a` which causes npm package from `npm-package` directory to sync with `package.json` in the `symfony-flex-app`.

I want to disable that behavior, cause I don't want this package to be synchronized.
Is there an official way to do so?

**Comment by weaverryan** [comment]
Can you explain your use-case more? If you don’t want the packages.json to be synchronized, could you just remove the symfony related config from the package.json  file of the composer-package-a?

cheers!

**Comment by Magiczne** [comment]
Updated structure in the original post.

The `symfony-flex-app-2` have `composer-package-a` in `composer.json` too.
Furthermore, both flex apps already have included `npm-package` in respective `package.json` files like so:
```js
{
  "dependencies": {
    // ...
    "some-name-i-want": "file:../composer-package-a/npm-package"
  }
}
```

It means that each time I run `composer install` it will try to synchronize `composer-package-a` packages into `devDependencies` under different name that I have already provided - which causes duplication of packages and furthermore completely disables possibility to develop frontend without having backend properly installed which sometimes is helpful.

> could you just remove the symfony related config from the package.json file of the composer-package-a?

There is no `package.json` file in the root directory of `composer-package-a`. And furthermore there is no symfony related configuration in the `package.json` placed in `composer-package-a/npm-package/package.json`. There is only package version, name and dependencies.

**Comment by nicolas-grekas** [comment]
The way to do this is to require packages to have the `symfony-ux` tag in their composer.json file, aka making the UX magic opt-in.
This has been discussed a few times already, eg in #737, and is pending an implementation.
/cc @tgalopin maybe you'd be able to give this a try?

**Comment by garak** [comment]
I second this issue. I like the effortless including of frontend packages, but users should be able to opt-in.
I've got a couple of use cases:
* I want to offer in my bundle different frontend implementations (e.g. jquery vs vanilla) and I'd like user can choose which one to get
* Some users have deploy pipelines that don't include backend vendor at every step, so they get an error. See for example https://github.com/PUGX/PUGXAutoCompleterBundle/issues/72
