### ISSUE TITLE
[Bug] v1.13.0: composer package-type "metapackage" conflicts with PackageJsonSynchronizer

### ISSUE THREAD

**Issue by possi** [symfony/flex#768]
Steps to reproduce:
* `composer global require "symfony/flex"`
* `echo '{}' > package.json`
* `composer require "gaufrette/ftp-adapter"`

Output:
```
  [ErrorException]
  file_get_contents(/home/starke/flex-test/vendor/gaufrette/ftp-adapter/composer.json): failed to open stream: No such file or directory
```

Composer version 2.0.13 2021-04-27 13:11:08
symfony/flex v1.13.0

This does not occur with v1.12.2

Assumed Explanation:
The [package-type](https://getcomposer.org/doc/04-schema.md#type) doesn't "write anything to the filesystem". Therefore the composer.json can not be read, as it isn't present.

**Comment by stof** [comment]
There is some discussion about it on the commit itself (though this issue is a better place): https://github.com/symfony/flex/commit/87980248212a049dbd188061ccdb4ea82fa155e8#r50964641

**Comment by possi** [comment]
@stof I second using installed.json/api
There may be other plugins for different package types (typo3, magento, etc.) which move the package installation directory or changes its directory structure.

**Comment by stephanvierkant** [comment]
Same issue with minishlink/web-push-bundle (type: symfony-bundle)
