### ISSUE TITLE
Flex version 1.13.1 is broken

### ISSUE THREAD

**Issue by abzolv** [symfony/flex#770]
After upgrading from 1.13.0 to 1.13.1, `composer update` produces an error:

PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Symfony\Flex\PackageJsonSynchronizer::addPackageJsonLink() must be of the type string, array given, called in /project-folder/vendor/symfony/flex/src/PackageJsonSynchronizer.php on line 46

My project composer.json has:

``
    "extra": {
        "symfony": {
            "allow-contrib": false,
            "require": "4.4.*"
        }
    },
``

The same error happens in two separate projects, which both worked with 1.13.0.

**Comment by nicolas-grekas** [comment]
Maybe you have a global installation of flex? Please let me know how that's possible. By looking at the code, I can't figure out.

**Comment by abzolv** [comment]
A second run of `composer update` works as expected (doesn't crash).
