### ISSUE TITLE
dump-env writes to error successful message

### ISSUE THREAD

**Issue by akalineskou** [symfony/flex#773]
Is there a reason the dump-env command outputs to stderr?
https://github.com/symfony/flex/blob/main/src/Command/DumpEnvCommand.php#L76
It could use `write` instead.

I've noticed it in the logs being marked as errors when it clearly isn't.
I can open a PR to change it, but wanted to see if it's using it by design before I do so.

**Comment by nicolas-grekas** [comment]
stderr is not only for errors, it's for any diagnostic messages.

**Comment by akalineskou** [comment]
Okay, but why not change it to write since it isn't an error?

Like I said I'm more than happy to submit a PR for this.

**Comment by nicolas-grekas** [comment]
I wouldn't be correct to me: that message is a diagnostic message.

**Comment by andrew-demb** [comment]
@nicolas-grekas does it mean, that messages like this https://github.com/symfony/flex/blob/b298435b9df8d7c7d7d5473d4b9f850a7844d7ea/src/Configurator/CopyFromPackageConfigurator.php#L24 should be also written to `stderr` as a diagnosis?
