### ISSUE TITLE
Update recipe when using php config?

### ISSUE THREAD

**Issue by stephanvierkant** [symfony/flex#791]
I'm using PHP config files and running `composer recipes:install [package] --force` recreates a `yaml` file instead of updating my PHP config file.

I can imagine that updating PHP config files is more complex, but for me this updating process is completely useless.

If updating PHP files is impossible, there should be another way of finding out the difference. Is there an easy way to have a diff between the old and the new recipe, so I can update my PHP config files manually?

**Comment by stof** [comment]
Well, flex recipes are not using the PHP config but the YAML one. So if you re-apply the recipe, it is logical that you get the YAML file.
Flex doesn't know about the content of the file belonging to recipes (and not all of them are DI config files btw).

**Comment by stephanvierkant** [comment]
I understand why this happens, but since PHP files are the prefered way of configuring Symfony, I think there should be a easier/better way to keep up with the latest recipes when using PHP config files.

**Comment by fabpot** [comment]
We are now using PHP files for configuring Symfony internal services, but YAML is still the default for end-user apps. Closing as there is nothing to do for now.
