### ISSUE TITLE
Wrong package upgrades in symfony 4.4 after flex V1.14.2

### ISSUE THREAD

**Issue by uvigo-atic** [symfony/flex#792]
The behaviour is not consistent when executing composer update twice. Package versions change without a reason. This creates a big impact as it updates monolog/monolog from v1.26.1 to v2.3.2 and breaks the application. 

It also bumps symfony v4 packages into v5 versions unexpectedly:
`"Upgrading symfony/filesystem (v4.4.27 => v5.3.4)".`

Steps to reproduce:

1.  Create a symfony project from scratch, as stated in https://symfony.com/doc/4.4/setup.html#creating-symfony-applications :
`composer create-project symfony/website-skeleton:"^4.4" my_project_name`
The output results as follows:
```...
  - Locking monolog/monolog (1.26.1)
...
  - Installing monolog/monolog (1.26.1): Extracting archive
```

2. Delete the vendor directory of this recently created project and execute `composer update`. This should install the same dependencies as in step 1 but instead, the following upgrades occur:
```
  - Upgrading monolog/monolog (1.26.1 => 2.3.2)
  - Upgrading symfony/cache (v4.4.30 => v5.3.7)
  - Upgrading symfony/config (v4.4.30 => v5.3.4)
  - Upgrading symfony/dependency-injection (v4.4.27 => v5.3.7)
  - Upgrading symfony/dom-crawler (v4.4.30 => v5.3.7)
  - Upgrading symfony/filesystem (v4.4.27 => v5.3.4)
  - Upgrading symfony/finder (v4.4.30 => v5.3.7)
  - Upgrading symfony/http-foundation (v4.4.30 => v5.3.7)
  - Upgrading symfony/inflector (v4.4.27 => v5.3.4)
  - Upgrading symfony/mime (v4.4.27 => v5.3.7)
  - Upgrading symfony/monolog-bridge (v4.4.27 => v5.2.12)
  - Upgrading symfony/options-resolver (v4.4.30 => v5.3.7)
  - Locking symfony/polyfill-intl-grapheme (v1.23.1)
  - Upgrading symfony/routing (v4.4.30 => v5.3.7)
  - Upgrading symfony/security-csrf (v4.4.27 => v5.3.4)
  - Locking symfony/string (v5.3.7)
  - Upgrading symfony/var-dumper (v4.4.30 => v5.3.7)
  - Upgrading symfony/var-exporter (v4.4.30 => v5.3.7)
...
  - Installing monolog/monolog (2.3.2): Extracting archive
```
3. Now, without deleting the `vendor/` directory, execute a  `composer update` again in your project. We should expect no changes, but the following behaviour is obtained:
```
  - Removing symfony/polyfill-intl-grapheme (v1.23.1)
  - Removing symfony/string (v5.3.7)
  - Downgrading monolog/monolog (2.3.2 => 1.26.1)
  - Downgrading symfony/cache (v5.3.7 => v4.4.30)
  - Downgrading symfony/config (v5.3.4 => v4.4.30)
  - Downgrading symfony/dependency-injection (v5.3.7 => v4.4.27)
  - Downgrading symfony/dom-crawler (v5.3.7 => v4.4.30)
  - Downgrading symfony/filesystem (v5.3.4 => v4.4.27)
  - Downgrading symfony/finder (v5.3.7 => v4.4.30)
  - Downgrading symfony/http-foundation (v5.3.7 => v4.4.30)
  - Downgrading symfony/inflector (v5.3.4 => v4.4.27)
  - Downgrading symfony/mime (v5.3.7 => v4.4.27)
  - Downgrading symfony/monolog-bridge (v5.2.12 => v4.4.27)
  - Downgrading symfony/options-resolver (v5.3.7 => v4.4.30)
  - Downgrading symfony/routing (v5.3.7 => v4.4.30)
  - Downgrading symfony/security-csrf (v5.3.4 => v4.4.27)
  - Downgrading symfony/var-dumper (v5.3.7 => v4.4.30)
  - Downgrading symfony/var-exporter (v5.3.7 => v4.4.30)
...
  - Removing symfony/string (v5.3.7)
  - Removing symfony/polyfill-intl-grapheme (v1.23.1)
  - Downgrading symfony/routing (v5.3.7 => v4.4.30): Extracting archive
  - Downgrading symfony/mime (v5.3.7 => v4.4.27): Extracting archive
  - Downgrading symfony/http-foundation (v5.3.7 => v4.4.30): Extracting archive
  - Downgrading symfony/var-dumper (v5.3.7 => v4.4.30): Extracting archive
  - Downgrading symfony/finder (v5.3.7 => v4.4.30): Extracting archive
  - Downgrading symfony/filesystem (v5.3.4 => v4.4.27): Extracting archive
  - Downgrading symfony/dependency-injection (v5.3.7 => v4.4.27): Extracting archive
  - Downgrading symfony/config (v5.3.4 => v4.4.30): Extracting archive
  - Downgrading symfony/var-exporter (v5.3.7 => v4.4.30): Extracting archive
  - Downgrading symfony/cache (v5.3.7 => v4.4.30): Extracting archive
  - Downgrading symfony/dom-crawler (v5.3.7 => v4.4.30): Extracting archive
  - Downgrading symfony/inflector (v5.3.4 => v4.4.27): Extracting archive
  - Downgrading symfony/options-resolver (v5.3.7 => v4.4.30): Extracting archive
  - Downgrading monolog/monolog (2.3.2 => 1.26.1): Extracting archive
  - Downgrading symfony/monolog-bridge (v5.2.12 => v4.4.27): Extracting archive
  - Downgrading symfony/security-csrf (v5.3.4 => v4.4.27): Extracting archive 
```

Version 1.14.1 is not affected by this behaviour.

Thanks in advance

**Comment by stof** [comment]
if you delete the vendor directory and you don't have symfony/flex installed globally, the `composer update` you run after that runs without Flex (as the plugin is not installed) and so won't respect the `extra.symfony.require` constraint that is handled by the plugin.

**Comment by uvigo-atic** [comment]
Thanks for the quick response. Something must have changed in `symfony/flex >= 1.14.2` that makes the builds break if you build the project by cloning without `vendor/` directory  and then executing `composer update`

The `vendor/`directory is usually ignored in `.gitignore`:

https://symfony.com/doc/current/the-fast-track/en/4-methodology.html#implementing-a-git-strategy

If `symfony/flex` needs to be installed globally for this kind of approach to work, maybe I'd be worth noting it in the documentation. 

Pipelines designed to build projects without `vendor/` in the repository are bound to fail with the current version of `symfony/flex` if it is not installed globaly. It worked before `symfony/flex <= 1.14.1` .

**Comment by stof** [comment]
@uvigo-atic pipelines should generally be running a `composer install` anyway, not a `composer update`. And so they won't suffer from running an update without the plugin.

**Comment by stof** [comment]
Also, I don't see any change in Flex that might have make it break after 1.14.1. for me, this case continues to behave the same, i.e. it was already behaving like that with older Flex versions.

**Comment by nicolas-grekas** [comment]
I'm sure that what you experience is real, but what you describe here is not enough for us to understand what's going on @uvigo-atic 

As @stof explained, this reproducer doesn't help discriminate your issue between 1.14.1 and 1.14.2.

I'm therefor closing. We'll reopen if you can provide a more specific description and reproducer. Thanks for your understanding.
