### ISSUE TITLE
package.json not recognized when in /src/Resources/assets

### ISSUE THREAD

**Issue by MichaelBrauner** [symfony/flex#793]
When I tried to install [my published bundle](https://github.com/Braunstetter/ControlPanelBundle) - I [was wondering](https://github.com/symfony/symfony/discussions/42681) why symfony-flex did not update my projects `controllers.json` or `package.json`. 

After I removed the `src` folder this worked perfectly. 

I pretty much like the `src` folder alongside `tests` folder and I guess it is best practice. 

So the question is - should the support for the `src` folder be added or should ux-stuff be separated into its own bundle with its own file structure (what imo is an unnecessary step and complicates things without reason).

What do you think about that issue?

Cheers!

**Comment by nicolas-grekas** [comment]
In `src/PackageJsonSynchronizer.php` you'll see that flex looks at the `/assets` and `/Resources/assets` folders. PR welcome if you think that we should add `src/Resources/assets` to that list. I don't know about others, but to me that should be OK.

**Comment by nicolas-grekas** [comment]
I submitted #808

**Comment by MichaelBrauner** [comment]
I was actually about to do that, but I wondered how to test it properly. I guess for that no extra test is needed. 
Thank you Nicolas!
