### ISSUE TITLE
Vendor's directory separator is not trimmed on Windows

### ISSUE THREAD

**Issue by skmedix** [symfony/flex#796]
Affected line:
https://github.com/symfony/flex/blob/main/src/Flex.php#L534

Relative path to the vendor is outputed as `vendor/`, and should be trimmed from `/` but `DIRECTORY_SEPARATOR` on Windows is defined as `\`. 

So when `package.json` is synchronized, resulted dependency path has duplicated slash like:
`file:vendor//symfony/ux-turbo/Resources/assets`

**Comment by nicolas-grekas** [comment]
please send a PR :)
