### ISSUE TITLE
Smarter auto-enabling of bundles without recipes

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/flex#80]
If you execute this and the bundle doesn't have a recipe:

```
$ composer require vendor-name/package-name
```

Flex autodetects that this is a Symfony Bundle (if composer.json type is symfony-bundle) and it enables for all environments:

```php
return [
  // ...
  'VendorName\Bundle\PackageNameBundle\VendorNamePackageNameBundle' => ['all' => true],
];
```

However, if you execute this:

```
$ composer require --dev vendor-name/package-name
```

The result is the same. Shouldn't we detect the `--dev` option and then enable the bundle only for dev and test?

```php
return [
  // ...
  'VendorName\Bundle\PackageNameBundle\VendorNamePackageNameBundle' => ['dev' => true, 'test' => true],
];
```

**Comment by chalasr** [comment]
Makes sense to me :+1:

**Comment by stof** [comment]
this is much harder than it seems, because during the composer installation process, you don't know whether the solver selected because of a normal requirement or a dev requirement (and checking the root package is not enough, as the bundle might not be a root dependency but a transitive one)

**Comment by Pierstoval** [comment]
@stof Isn't there a place in the plugin where the `Input` object could be used to make this check?

**Comment by stof** [comment]
@Pierstoval composer itself does not have this info, as the solver outputs a single list of packages.

To split packages in the composer.lock, what composer does is that it performs a *second* run of the solver with only non-dev requirement, and using the repository of installed packages as only source of packages. Any package marked as selected by this second resolution goes in the non-dev section.
But such approach works only after all packages are installed. Flex is running during the installation of each package (to configure it when needed), and so cannot use this approach (it would not work)

**Comment by sstok** [comment]
@stof Flex is to my knowledge only triggered when the package is newly installed, running install when the package is already installed (or in the lock?) will not trigger Flex again 🤔 I don't know the complete internals of Composer, so I could be wrong 😛

**Comment by francoispluchino** [comment]
@javiereguiluz Using the value of the input option (`--dev`) and the dev dependencies list of the root Composer package don't provide a complete list of all dependencies in `dev` (sub dependencies), but only the list of first-level of the dependencies.

@sstok By the time Flex configure/reconfigure/unconfigure the packages, Composer and therefore also the plugin are not able to know if the packages are required by `require` or` require-dev`.

Regarding the proposal of @Stof in the case of using the Lock file:

> But such approach works only after all packages are installed. Flex is running during the installation of each package (to configure it when needed), and so cannot use this approach (it would not work)

It is therefore possible to move the configuration/reconfiguration/unconfiguration of each package at the end of the install/update (`ScriptEvents::POST_INSTALL_CMD` and `ScriptEvents::POST_UPDATE_CMD`) but to create the lists with  `PackageEvents::POST_PACKAGE_INSTALL`, `PackageEvents::POST_PACKAGE_UPDATE` and `PackageEvents::POST_PACKAGE_UNINSTALL`.

The disadvantage of this solution is that if Composer stops during the installation (download error, etc...), the packages will not be configured/reconfigured/unconfigured at the next execution of Composer. Solution: Save this todo list to a temporary file, and verify the presence of this file before executing the configuration/reconfiguration/unconfiguration of the packages.

With this approach, it is therefore possible to build the proposal of @javiereguiluz.
