### ISSUE TITLE
Add artifact and path hosting options to new server-less recipe hosting

### ISSUE THREAD

**Issue by gnito-org** [symfony/flex#809]
[Replacing flex-server by hosting recipes on GitHub](https://github.com/symfony/flex/pull/803) is an awesome improvement.

As far as I can determine, custom flex endpoint overlays currently have to be hosted somewhere on a public web server (given the code in Download.php).

It would be really helpful if flex recipes could be hosted on the same hosting options [available for Composer packages](https://getcomposer.org/doc/05-repositories.md#hosting-your-own), specifically: public web server, **artifact**, and **path**.

That will cover recipes for private bundles that cannot be hosted on public web servers.

**Comment by nicolas-grekas** [comment]
Hello, I'm not sure what you mean exactly, but the good news is that now everything is open source and open to contributions. I'd be happy to review a more detailed proposal.

About storing in a local directory, the file:// protocol might allow it already. One thing that might be improved is resolution of links in the index.json: they have to be absolute, while it might help allowing them to be relative to said index.json.

PR welcome.

**Comment by gnito-org** [comment]
Where can one read about using the file:// protocol in flex?

**Comment by nicolas-grekas** [comment]
src/Downloader.php is the file that interacts with the API endpoint. That's the start. Then errors-n-trials might be the way to iterate. This reuses code that found in composer so it might be worth following the rabbit down there. For now you could just give it a start a see where it blocks or if it works out of the box by configuring the extra.symfony.endpoint entry in your composer.json

**Comment by gnito-org** [comment]
Hosting private bundle recipes in a private GitHub repository works just fine, and it covers my use case.

**Comment by nicolas-grekas** [comment]
Relative URLs implemented in #872
