### ISSUE TITLE
Issue with the PR link in the Symfony Server report page

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/flex#81]
Consider this page: https://symfony.sh/r/main/62

If you clink on the *"Symfony Recipes Pull Request #62"* link, it goes to: https://api.github.com/repos/symfony/recipes/pulls/62 instead of https://github.com/symfony/recipes/pull/62 as before.

**Comment by stof** [comment]
Yeah, the server should use `html_url` in the github API response rather than `url` (which is the URL of the resource in the API)

**Comment by fabpot** [comment]
Indeed, good catch. That's a regression from my yesterday big refactoring. Fixed now.
