### ISSUE TITLE
Questions about serverless Flex

### ISSUE THREAD

**Issue by gnito-org** [symfony/flex#813]
**Q1:**

In Downloader.php the code suggests that one must add "flex://defaults" to your endpoints in composer.json to access the default Symfony recipe repositories, like so:

```
    "extra": {
        "symfony": {
            "endpoint": [
                "https://api.github.com/repos/gnito-org/recipe-repo/contents/index.json",
                "flex://defaults"
            ]
        }
    },
```
Yet, when I do that and issue the command `FLEX_SERVERLESS=1 composer recipes`, composer freaks out with:

```
  [Composer\Downloader\TransportException]                                                                                                      
  The "flex://defaults" file could not be downloaded: Unable to find the wrapper "flex" - did you forget to enable it when you configured PHP?  
  Failed to open stream: No such file or directory                                                                                              
```
When I have:
```
    "extra": {
        "symfony": {
            "endpoint": [
                "https://api.github.com/repos/gnito-org/recipe-repo/contents/index.json"
            ]
        }
    },
```
everthing works fine. With `composer recipes` I get a combined list of Symfony recipes and private recipes.

Am I missing something here?

**Q2:**

The `FLEX_SERVERLESS=1` flag seems to be doing nothing, meaning, `composer recipes` and `FLEX_SERVERLESS=1 composer recipes` give me exactly the same combined list of Symfony recipes and private recipes.

**Footnote**

`composer clearcache` makes no difference to above.

Pinging @nicolas-grekas

**Comment by nicolas-grekas** [comment]
Hello, thanks for giving this a try!

I submitted #814 to fix the error.

About Q2: if the endpoint contains `.json`, `FLEX_SERVELESS` is ignored since we don't need it to know that you opt-in for the new format.

**Comment by nicolas-grekas** [comment]
I can't tell because I don't know what's in your private endpoint. If you can make it public somehow I might have a look.
About tests, they're missing right now. PR welcome if you have time to add some!

**Comment by gnito-org** [comment]
I don't understand. 

How can the differences in the two lists have anything to do with my private recipe repository?

The only recipe in my private repository is `my-org/private-bundle`, which has a `(recipe not installed)` label in both lists.

The rest of the list consist of recipes supplied by Symfony and Symfony contributors (your two `DEFAULT_ENDPOINTS`).

**Comment by nicolas-grekas** [comment]
I don't understand the issue either, that's why looking for an exact reproducer.
Alternatively, can you maybe try to debug the behavior and figure out what's going on?

**Comment by gnito-org** [comment]
https://github.com/gnito-org/recipes-demo

This public repo basically replicates what is in my private repository, without exposing any private info.

**Comment by nicolas-grekas** [comment]
Looks like #815 might fix at least part of the remaining.

**Comment by nicolas-grekas** [comment]
Thanks for the details. The A vs B is expected.
