### ISSUE TITLE
Sync behaviour of extra.symfony.endpoint with SYMFONY_ENDPOINT env var

### ISSUE THREAD

**Issue by emodric** [symfony/flex#816]
PR #803 says the following:

    The default endpoints can be changed by setting the `extra.symfony.endpoint` entry in the root
    composer.json file. The special `flex://defaults` endpoint can be used in that list to reference
    the default endpoints.

    On top of that, the `SYMFONY_ENDPOINT` env var can be defined to a single endpoint. This endpoint
    will be used on top of (with higher priority than) the default endpoints of the app.

It would be nice if the `extra.symfony.endpoint` config would behave the same as the env var when using a string endpoint. Specifically, it would be nice if config like this:

```
"extra": {
    "symfony": {
        "endpoint": "https://api.github.com/...",
        "allow-contrib": true,
        "require": "5.3.*"
    }
}
```

would automatically use `flex://defaults` as the fallback endpoint.

This would help eliminate potential unintended disabling of the default Flex endpoint if one would configure Flex like this.

In that case, specifying the `endpoint` config as an array would be used to disable usage of the default endpoint if needed.

**Comment by nicolas-grekas** [comment]
Works for me, would you like to send a PR doing that

**Comment by emodric** [comment]
Sure, I'll try to get it in today :+1:
