### ISSUE TITLE
flex serverless not updating existing config/packages/security.yaml

### ISSUE THREAD

**Issue by jemiaymen** [symfony/flex#828]
I try to use a private Serverless recipes [github link](https://github.com/JEMIX-LTD/recipes).
The recipe jemix.security.dev-main.json created files correctly, except config/packages/security.yaml which was not updated.

I don't find the solution on line, and I don't know how can I fix it .
![Screenshot 2021-11-17 234222](https://user-images.githubusercontent.com/4699547/142294265-d56c8514-2520-45dc-a476-e5996cded18d.png)

**Comment by nicolas-grekas** [comment]
Flex never overrides existing files, maybe that's the issue?

**Comment by jemiaymen** [comment]
yep I figure out thanks

**Comment by stof** [comment]
to be exact, there is one case which overrides existing files: `composer recipes:install --force` (that's what the `--force` flag is about)

**Comment by jemiaymen** [comment]
> to be exact, there is one case which overrides existing files: `composer recipes:install --force` (that's what the `--force` flag is about)

Thanks that work for me
