### ISSUE TITLE
Call to undefined method Symfony\Flex\Recipe::getFormattedOrigin()

### ISSUE THREAD

**Issue by keyboardman** [symfony/flex#837]
composer install failed
here is the error message below

Generating optimized autoload files
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
117 packages you are using are looking for funding.
Use the `composer fund` command to find out more!

Symfony operations: 20 recipes (7add8c42e72977ba6905c2a07a97223b)
PHP Fatal error:  Uncaught Error: Call to undefined method Symfony\Flex\Recipe::getFormattedOrigin() in phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(221) : eval()'d code:476
Stack trace:
#0 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(221) : eval()'d code(353): Symfony\Flex\Flex_composer_tmp0->install(Object(Composer\Script\Event))
#1 [internal function]: Symfony\Flex\Flex_composer_tmp0->update(Object(Composer\Script\Event))
#2 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(191): call_user_func(Array, Object(Composer\Script\Event))
#3 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(118): Composer\EventDispatcher\EventDispatcher->doDispatch(Object(Composer\Script\Event))
#4 phar:///usr/local/bin/composer/src/Composer/Installer.php(364): Composer\EventDispatcher\EventDispatcher->dispatchScript('post-update-cmd', true)
#5 /Users/lucmoisan/.composer/vendor/symfony/flex/src/Flex.php(993): Composer\Installer->run()
#6 /Us in phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(221) : eval()'d code on line 476

Fatal error: Uncaught Error: Call to undefined method Symfony\Flex\Recipe::getFormattedOrigin() in phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(221) : eval()'d code:476
Stack trace:
#0 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(221) : eval()'d code(353): Symfony\Flex\Flex_composer_tmp0->install(Object(Composer\Script\Event))
#1 [internal function]: Symfony\Flex\Flex_composer_tmp0->update(Object(Composer\Script\Event))
#2 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(191): call_user_func(Array, Object(Composer\Script\Event))
#3 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(118): Composer\EventDispatcher\EventDispatcher->doDispatch(Object(Composer\Script\Event))
#4 phar:///usr/local/bin/composer/src/Composer/Installer.php(364): Composer\EventDispatcher\EventDispatcher->dispatchScript('post-update-cmd', true)
#5 /Users/lucmoisan/.composer/vendor/symfony/flex/src/Flex.php(993): Composer\Installer->run()
#6 /Us in phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(221) : eval()'d code on line 476

**Comment by stof** [comment]
I suspect that this might be caused by an upgrade of Flex itself from an old installed version. Try first updating only `symfony/flex` with plugins disabled, so that you have an uptodate version of Flex installed, and then running your update again.

**Comment by keyboardman** [comment]
I have this error doing this 
 - symfony new --full test2 
 
 environment:
- PHP 7.3.3
- Symfony CLI version v4.26.9
- Composer - Dependency Manager for PHP - version 2.1.12

**Comment by keyboardman** [comment]
problem solved. 
I deleted this directory:  ~/.composer
