### ISSUE TITLE
Duplicate package.json dependencies

### ISSUE THREAD

**Issue by codedmonkey** [symfony/flex#840]
👋

I've been experimenting with creating my own Symfony UX-like bundle ([this one](https://github.com/onlinq/form-collection-bundle)). Although the Flex documentation is limited it's working great.

One problem I've been encountering is that on every update of Composer, Flex tries to add my bundle's autoimport libraries to the `devDependencies` section of the package.json. Awesome, of course, but in this case I already added it to the `dependencies` section myself.

My request is that Flex checks if the library is already defined under the `dependencies` section before it adds it to the `devDependencies` section. I can make a PR myself if it helps!

**Comment by stof** [comment]
this makes sense IMO. Contributions are welcome to fix this.
