### ISSUE TITLE
json schema for manifest.json for autocomplete

### ISSUE THREAD

**Issue by shyim** [symfony/flex#844]
I could not find any documentation where all allowed properties are shown for the manifest.json.

Maybe it would be nice to provide a json schema, so IDEs like PhpStorm can autocomplete and maybe a doc page about the manifest.json :sweat_smile:

**Comment by 94noni** [comment]
maybe https://github.com/symfony/recipes/blob/master/README.rst ?
Or I may have missed your issue :)

**Comment by shyim** [comment]
For the first part yes. But still a json schema would be better to have autocomplete and a way to validate the files

**Comment by nicolas-grekas** [comment]
PR welcome I suppose. Closing meanwhile.
