### ISSUE TITLE
Search bar not working on website (flex.symfony.com)

### ISSUE THREAD

**Issue by jdevinemt** [symfony/flex#849]
The search bar hasn't been working on the symfony flex website for a few days. I've refreshed my cache, so I have the most recent js files.

**Comment by fabpot** [comment]
This website is not maintained anymore and the service behind it will be shut down at some point.

See https://symfony.com/blog/upgrade-flex-on-your-symfony-projects and https://symfony.com/blog/upgrade-flex-on-your-symfony-projects

**Comment by andrew-demb** [comment]
@fabpot you provided the same link twice. Please show the second one.

Question: why the website will be dropped? It is more conveniently to search available (official or not) recipes via website UI, instead of discovering on repositories JSON files

**Comment by fabpot** [comment]
Oops, here you go: https://symfony.com/blog/symfony-flex-is-going-serverless

From analytics stats, the conclusion is that the website is used very marginally. It makes sense as you don't need to discover recipes, you add a dependency that you need and it happens to be automatically configured.

**Comment by stof** [comment]
@fabpot I suggest adding a banner on the website then (or removing the search field), because this has been reported again on slack

**Comment by fabpot** [comment]
Done
