### ISSUE TITLE
Flex ignored on first update/install

### ISSUE THREAD

**Issue by Aerendir** [symfony/flex#850]
I'm using Flex to test my packages against various versions of Symfony.

To do this, I've configured my GitHub Actions to:
1. `composer require symfony/flex --no-update
2. `composer config extra.symfony.require "${{ matrix.symfony }}"`

where `${{ matrix.symfony }} is obviously the desired version of Symfony to test against.

However, when I run `composer update` the first time the constraint of Flex is simply ignored.

For example, if I allow to install SF^6.0 and in `extra.symfony.require` I require SF^4.4, the installed version of SF packages is anyway the 6.0.

But, if I run again `composer update`, then the constraint of Flex are taken into account and Symfony's packages are downgraded to the desired constrained version.

**Is there a way to not run `composer update` two times?**

**Comment by grossmannmartin** [comment]
We just run into this issue. Is even possible to solve this somehow?

_we run composer update twice as a hotfix_

**Comment by nicolas-grekas** [comment]
There is no other fix to this issue, see eg https://github.com/composer/composer/issues/10338

**Comment by Aerendir** [comment]
Just for reference, this is what's happening and why it is not an issue

https://github.com/composer/composer/issues/10338#issuecomment-988697300
