### ISSUE TITLE
[Bug] Fatal Error when installing symfony

### ISSUE THREAD

**Issue by Romaixn** [symfony/flex#853]
Hello ! When launch `symfony new test`, I have a fatal error when installing symfony/flex : 

`PHP Fatal error:  Uncaught TypeError: Symfony\Flex\Command\RecipesCommand::__construct(): Argument #3 ($downloader) must be of type Symfony\Flex\Command\HttpDownloader, Composer\Util\HttpDownloader given, called in /home/romain/test/vendor/symfony/flex/src/Flex.php on line 180 and defined in /home/romain/test/vendor/symfony/flex/src/Command/RecipesCommand.php:36`

I'm running PHP 8.0.14 and composer 2.2.4.

**Comment by nicolas-grekas** [comment]
Fixed,, please upgrade.
