### ISSUE TITLE
recipes:update command does not work for private flex recipe repositories

### ISSUE THREAD

**Issue by gnito-org** [symfony/flex#857]
The ``composer recipes:update <package>`` command consistently responds with ``This recipe for <package> is already at the latest version`` regardless of what is changed in the recipe.

If you change only the ``ref``, no luck. If you change the ``ref`` and some content so that there will be a diff, still no luck.

After running the command, the ``ref`` in ``symfony.lock`` is still at the old outdated value, and the ``composer recipes`` command still displays the ``update available`` comment next to the package name.

Running the ``composer recipes:install <package> --force`` command updates the recipe to the latest version and removes the ``update available`` comment.

**Comment by weaverryan** [comment]
Hey @gnito-org!

Does your private flex repository implement the new "archived" directory stuff - e.g. https://github.com/symfony/recipes/tree/flex/main

If not, it needs to (and I can tell you some details of how). But, even if that's the case, error message needs work - it's not clar.

If your API *does* already implement this, then we definitely have a problem. I didn't have a private flex repository to test against, but "in theory" as long as it implements the same API as the main flex API, it should work (though the CHANGELOG won't work).

Cheers!

**Comment by gnito-org** [comment]
Hi @weaverryan,

No, I don't have the archived directory stuff. Had no idea it even existed. Could you please provide more info?

Can the process and rules for creating Flex recipes perhaps be more fully documented, seeing that more and more people are probably going to employ private repositories? 

I've written [this documentation](https://symfony.com/doc/current/setup/flex_private_recipes.html), but that's as deep as my knowledge goes.

**Comment by gnito-org** [comment]
It will also be very useful to know what is the minimum file content (index keys) that one needs in the ``index.json`` and ``bundle-recipe-version.json`` files for the recipe to be successfully installed.

Furthermore, there will probably have to be a non-BC breaking promise on the structure of the json recipe files going forward.

I can see that maintaining the archived versions is going to be way more effort than the potential benefit it will give me. My recipes rarely change, and when they do, it's a small change. I'm quite happy to continue using ``composer recipes:install --force`` and just sorting out the diffs in the git client myself. So, if I can continue with the basic structure that I [documented](https://symfony.com/doc/current/setup/flex_private_recipes.html), that's the route I will be following.

**Comment by aivus** [comment]
@gnito-org you can look on this commands which are generating index for flex recipes:
https://github.com/symfony-tools/recipes-checker/blob/main/src/GenerateFlexEndpointCommand.php
https://github.com/symfony-tools/recipes-checker/blob/main/src/GenerateArchivedRecipesCommand.php

btw, as far as I can see you are generating flex index by yourself as it's described by you in [docs](https://symfony.com/doc/current/setup/flex_private_recipes.html). Maybe it's better just to switch to https://github.com/symfony-tools/recipes-checker ?

**Comment by nicolas-grekas** [comment]
Closing as nothing inherently prevents it from working. Indeed symfony-tools/recipes-checker and/or callable actions in the recipe repo have to be used to generate proper jsons with the archives needed for the command.

Please submit a doc PR if possible!
