### ISSUE TITLE
[ReflectionException] Method Symfony\Flex\PackageJsonSynchronizer::addPackageJsonLink() does not exist  

### ISSUE THREAD

**Issue by StevenVAIDIE** [symfony/flex#859]
Since the following PR have been merged https://github.com/symfony/flex/pull/841/files, flex does not work after an composer install.

We have the following error message: 
```  
  [ReflectionException]                                                             
  Method Symfony\Flex\PackageJsonSynchronizer::addPackageJsonLink() does not exist  
```

Indeed here https://github.com/symfony/flex/blob/1.x/src/Flex.php#L534 we continue to call addPackageJsonLink whereas this function have been removed.

**Comment by nicolas-grekas** [comment]
Already fixed :)

**Comment by StevenVAIDIE** [comment]
Perfect thank you nicolas
