### ISSUE TITLE
docker configuration failed

### ISSUE THREAD

**Issue by hulvat** [symfony/flex#861]
### Symfony version(s) affected

v4.4.37

### Description

Composer instalation process ended with

[ErrorException]
 Undefined offset: -1

when is confirmed  including Docker configuration from recipes

```
 Configuring symfony/mailer (>=4.3): From github.com/symfony/recipes:master
  -  WARNING  symfony/mailer (>=4.3): From github.com/symfony/recipes:master
    The recipe for this package contains some Docker configuration.

    This may create/update docker-compose.yml or update Dockerfile (if it exists).

    Do you want to include Docker configuration from recipes?
    [y] Yes
    [n] No
    [p] Yes permanently, never ask again for this project
    [x] No permanently, never ask again for this project
    (defaults to y):


  [ErrorException]
  Undefined offset: -1
```

### How to reproduce

Add "symfony/mailer": "4.4.*" to composer.json and run composer install

**Comment by wouterj** [comment]
Hi! I've transferred this issue to the symfony/flex repository, as that's the Composer plugin that installs the recipes (including docker config).

I'm having an issue reproducing this error, here are the commands I ran:

```bash
symfony new --version=4.4 issue-45245
cd issue-45245
composer req 'symfony/mailer:4.4.*'
```

This did not result in any error, and the recipe including Docker configuration is installed correctly.

Can you try to create a set of commands or a reproducer application that allows us to get this error on our machines? And can you please run the command using `-vvv` so you get a full stack trace of this error?

**Comment by hulvat** [comment]
Hi.
It seems that the problem was in my docker-compose.override.yml, after delete him everything ran ok
