### ISSUE TITLE
Create workflow for git-less environments

### ISSUE THREAD

**Issue by kaznovac** [symfony/flex#862]
for development in `docker` environment it's not uncommon to not have the `git` installed in the development container - this case makes impossible to work with flex recipes.

suggested options:
- print warning `git` is not installed
- create a cli argument (i.e. `--without-git`) to disable `git` integration

**Comment by nicolas-grekas** [comment]
When is git required? Looking at the source code, only when running `recipes:update` or `recipes:install`.
For those commands, `git` is required, adding `--without-git` wouldn't make sense.

**Comment by kaznovac** [comment]
Here's the scenario
- i have `git` in the host environment
- in the docker's php container with composer i have source directory binded
- without installing `git` and its dependencies i have no means to run `composer recipes:update` in the docker container (to enable pushing from the container would be hard as it would require forwarding ssh agent authentication - yet another dependency not available on the official php image...)

in the nutshell i'm proposing to the new flag to enable overwriting of the recipe files when git is not available in current env, and let the developer handle the changes in the host environment

**Comment by nicolas-grekas** [comment]
The recipes:install --force command should be used in your case I think.
