### ISSUE TITLE
Flex changing bundles.php environments

### ISSUE THREAD

**Issue by alexander-schranz** [symfony/flex#879]
We have a special bundles.php. Since some changes now flex seems to overwrite our `bundles.php` configurations which ends up in a none working version of @sulu as example we requires fixtures bundle be enabled in all environments and has other envs configured:

<img width="721" alt="Bildschirmfoto 2022-03-03 um 14 10 54" src="https://user-images.githubusercontent.com/1698337/156571530-b05680c1-59db-43ec-9553-822f47a1be2c.png">

I'm not sure which change in flex did this change. But it seems flex is ignoring exist entries in the `bundles.php` and there configuration and just overwrites them now. Which was not the case in the past.

**Comment by nicolas-grekas** [comment]
Indeed, flex should preserve existing entries. What's the sequence of command to run to run into this behavior? Would you mind looking for a fix?

**Comment by alexander-schranz** [comment]
Currently I can reproduce it this way:

```
composer create-project sulu/skeleton
composer update
# questions about docker .. are asked
# now bundles.php is modified
```

I think in future it will directly appear after create-project because we enabling symfony/flex allow plugins in the next release.

Do you have any hint which could cause this change?

**Comment by alexander-schranz** [comment]
Looks like this is cause by this change in the update recipe command:

https://github.com/symfony/flex/commit/3ee7719acb1af3a329696db345f363305ec61e0b#diff-d9851ebac8a462c55afde96f2287e93ba81c609b9110b3bced335ba6c016e4a5R72-R78

/cc @weaverryan is this really necessary to change the `envs` here? 

I think adding `envs` maybe make sense in an update but removing them seems to be strange.
