### ISSUE TITLE
Flex Server SSL_ERROR_BAD_CERT_DOMAIN

### ISSUE THREAD

**Issue by mareckigit** [symfony/flex#882]
There is a problem with the CERT on symfony.sh  - SSL_ERROR_BAD_CERT_DOMAIN. 

curl: (60) SSL: no alternative certificate subject name matches target host name 'symfony.sh'

**Comment by floviolleau** [comment]
Hi,

I've got the same issue

**Comment by nicolas-grekas** [comment]
symfony.sh was used by an outdated version of flex, you need to upgrade it.
