### ISSUE TITLE
Upgrade orm-pack replace by latest version of doctrine

### ISSUE THREAD

**Issue by TheGarious** [symfony/flex#884]
### Description

Before update, into my composer.json 

```

    "require" : {
        ...
        "symfony/orm-pack": "^1.0" // version installed 1.2.0
        ...
    }
```

When i run this command below : 

```
composer update 
```

I have this modification into my composer json : 

```
-        "symfony/orm-pack": "^1.0",

+        "doctrine/doctrine-bundle": "^2.5",
+        "doctrine/doctrine-migrations-bundle": "^3.2",
+        "doctrine/orm": "^2.11",
```

But into the last version of orm-pack, 1.12.0 we have :  

```
+        "doctrine/common": "^2",
+        "doctrine/doctrine-bundle": "^2",
+        "doctrine/doctrine-migrations-bundle": "^2",
+        "doctrine/orm": "^2",
```

The problem is when orm-pack is replaced by directly composant, composer install the latest version without regarding a version of orm-pack.

**Comment by nicolas-grekas** [comment]
I think this is expected: composer update first gets the latest version of the pack, then unpacks it, isn't it?
If the change doesn't work for you, you can always stick to the versions that you need.
Closing as I think there is nothing to do here.

**Comment by alexislefebvre** [comment]
I have the same issue while upgrading a (legacy) project from Symfony `4.2.*` to `4.4.*`.

Once `symfony/orm-pack` is removed, I end up with this error:

> The DoctrineBundle is not registered in your application. Try running "composer require symfony/orm-pack".

Why does it remove the package then complain that's it's missing?

`symfony/flex` is version 1.19.5

Removing the cache entirely doesn't fix the issue.

**Comment by stof** [comment]
If you remove the symfony/orm-pack from your dependencies instead of unpacking it in your dependencies, this will also remove the transitive dependencies (and so DoctrineBundle will be gone).

**Comment by alexislefebvre** [comment]
Actually when I install it it is removed:

```shell
$ composer require symfony/orm-pack:^2.3
[…]
./composer.json has been updated
Running composer update symfony/orm-pack
Loading composer repositories with package information
Updating dependencies
Lock file operations: 1 install, 0 updates, 0 removals
  - Locking symfony/orm-pack (v2.3.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing symfony/orm-pack (v2.3.0): Extracting archive
[…]
Generating autoload files
117 packages you are using are looking for funding.
Use the `composer fund` command to find out more!

Run composer recipes at any time to see the status of your Symfony recipes.

Unpacking Symfony packs
  - Unpacked symfony/orm-pack
Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 0 updates, 1 removal
  - Removing symfony/orm-pack (v2.3.0)
```

**Comment by alexislefebvre** [comment]
The issue didn't come from Symfony, it was due to the fact the project used `doctrine/doctrine-bundle:^1.11`. Upgrading to `^2` fixed the issue. :heavy_check_mark: 

I found this through another issue:

- https://github.com/symfony/orm-pack/issues/21#issuecomment-638130211
