### ISSUE TITLE
composer update symfony/flex is not available

### ISSUE THREAD

**Issue by GSpecDrum** [symfony/flex#888]
vendor | version
-- | --
PHP | 7.4.14
Symfony/Symfony | 5.2.14
symfony/flex | 1.15.4

My project couldn't deployed, because `composer install` falls with error
```
  [ErrorException]
  Undefined index: splits
```
on line vendor/symfony/flex/src/PackageFilter.php:126 because https://flex.symfony.com/versions.json returns empty object.

`composer update symfony/flex` falls with same error, I can't update symfony flex like shown in https://symfony.com/blog/upgrade-flex-on-your-symfony-projects.

I can't deploy my project to production.
Please, help.

**Comment by nicolas-grekas** [comment]
Please upgrade to flex 1.18, v1.15 is outdated.

**Comment by GSpecDrum** [comment]
@nicolas-grekas  Did you read my post? I can't upgrade symfony/flex

**Comment by nicolas-grekas** [comment]
`composer update symfony/flex --no-plugins --no-scripts` should do it

**Comment by GSpecDrum** [comment]
Thanks!

**Comment by GSpecDrum** [comment]
Maybe there is need to correct blog post https://symfony.com/blog/upgrade-flex-on-your-symfony-projects to help others to upgrade to new versions of symfony flex?

**Comment by nicolas-grekas** [comment]
Good idea, I just did so!

**Comment by vcastro45** [comment]
Same problem today, but when I run `composer update symfony/flex --no-plugins`, an error is displayed:

```
> symfony-cmd
sh: 1: symfony-cmd: not found
Script symfony-cmd handling the auto-scripts event returned with error code 127
Script @auto-scripts was called via post-update-cmd
```

**Comment by GinoPane** [comment]
Guys, does it mean that update is required? Flex before 1.18 does not work anymore?

**Comment by nicolas-grekas** [comment]
Try `composer update symfony/flex --no-plugins --no-scripts` @vcastro45

**Comment by vcastro45** [comment]
@nicolas-grekas Yep, it works ! thank you
