### ISSUE TITLE
Undefined array key "splits" 

### ISSUE THREAD

**Issue by pavbis** [symfony/flex#889]
I am not able to install composer packages atm and I am getting this message 
![Bildschirmfoto 2022-04-04 um 13 33 40](https://user-images.githubusercontent.com/2733235/161535312-99c6cf1b-8fa9-49ac-a971-a0ef92a18055.png)
Also this url https://flex.symfony.com/versions.json which is used as a default endpoint returns an empty array atm.

**Comment by nicolas-grekas** [comment]
Duplicate of #888, you need to run `composer update symfony/flex --no-plugins --no-scripts`

**Comment by pavbis** [comment]
@nicolas-grekas mercí will try it.

**Comment by pscibor93** [comment]
Have u  experienced such error after running the flex update. 

[Composer\Downloader\TransportException]                                                                                 
  The "https://raw.githubusercontent.com/symfony/recipes/flex/main/index.json" file could not be downloaded (HTTP/2 404 )

weird to get 404 there as there is a content under the given url ?

**Comment by nicolas-grekas** [comment]
@pscibor93 strange. I've never seen that. Let us know if you figure out why you get this.

**Comment by pavbis** [comment]
@nicolas-grekas thx!  After executing `composer update symfony/flex --no-plugins --no-scripts` I was able to install composer packages. Closing this one ;)
