### ISSUE TITLE
Allow expanding of additional Composer values in env and copy-from-*

### ISSUE THREAD

**Issue by dkarlovi** [symfony/flex#89]
It would be useful to expand certain variables from composer.json in `env` and `copy-from-*`, the most useful that comes to mind is `name` (I'd like to use it for naming [auto-naming images](https://github.com/symfony/recipes-contrib/pull/15/files/03342c2a49cd1f0f547c128280c73727bf80af21#r116414523) in my Docker recipe).

For example, if your project is named `company/myproject.com`, the recipe can use that value to auto-generate proper Docker image names and have the pull/push (deploy to production) functionality work out of the box in many cases.

**Comment by dkarlovi** [comment]
Even existing variables might be expanded when copying, for example:
https://github.com/symfony/recipes-contrib/pull/15/files#diff-3ba0ef2bb059b669a5fc5b2032e64a29R42

**Comment by nicolas-grekas** [comment]
One year after it's been created, I don't understand what this is about.
Maybe it's the same as https://github.com/symfony/flex/issues/243
Maybe not. Closing as "too cryptic" :)

**Comment by nicolas-grekas** [comment]
Maybe :)
Anyway, keeping a one year issue open is not useful: nobody else chimed in - we maintainers have enough work - please submit a PR if you really care to have this happen anytime soone.
Thanks for you understanding.

**Comment by dkarlovi** [comment]
That's a much better answer. :+1: 

> We don't care. Closing.

Saying it's too cryptic sounds like you need some sort of additional feedback or clarifications, wasting everybody's time.
