### ISSUE TITLE
composer update: Undefined index: splits

### ISSUE THREAD

**Issue by wouterj** [symfony/flex#890]
This error is caused by a very outdated Symfony Flex version. Please update it using this command:

```
composer update symfony/flex --no-plugins --no-scripts
```

Make sure it installs *at least* 1.17 (or higher). See https://symfony.com/blog/upgrade-flex-on-your-symfony-projects (from November 2021) for more information.

If you have installed Flex globally, run the command as `composer global update` instead of `composer update` to apply to the global plugin.

If you're using eZ Publish / Ibexa DXP
---

See [this comment by @webhdx](https://github.com/symfony/flex/issues/890#issuecomment-1088527388):

> Upgrading to the latest Ibexa DXP release will fix the issue. Just remember to apply changes from [ibexa/website-skeleton](https://github.com/ibexa/website-skeleton/blob/main/composer.json#L98) because we recently switched to serverless Flex approach.

If you're using Bolt CMS 4
---

See [this comment by @bobdenotter](https://github.com/symfony/flex/issues/890#issuecomment-1088671595):

> I've tagged Bolt `4.2.6`, which shouldn't block Flex 1.18 (or 2.x) anymore. 
>
> https://github.com/bolt/core/releases/tag/4.2.6

If you can't install Flex 1.17
---

Try seeing which dependency or constraint blocks you (and try submitting a fix in their repository), using:

```
composer why-not symfony/flex 1.18.0
```

**Comment by lol768** [comment]
Can I ask why you thought it was acceptable to just break the old endpoint without clearly announcing a migration date? The blog posts I've read (and indeed read at the end of last year) just state an aspiration to move over at some point in the future.

> We have not decided yet when we will shut down the current Flex server, but please upgrade at your earlier convenience to help us move forward faster.

All my CI jobs started failing today due to this, further exacerbated by the upgrade process being painful for those of us who've updated to PHP 8.1 in the meantime (not supported by `laminas/laminas-code`).

**Comment by stof** [comment]
The need for updating to Flex 1.17+ was announced both in September 2021 and in November 2021 on the Symfony blog. and this was asked again multiple times on Twitter in the meantime.

**Comment by lol768** [comment]
Yes, vague warnings were posted on the blog and social media. Without any sort of "sunset date", deprecation timeline or actionable plan that communicated when the change needed to be made.

Come on, you absolutely can do better than that. All the Symfony core releases have a proper release lifecycle with documented, well-communicated EOL dates. When functionality is deprecated, the version number where it is deprecated and the version number for its scheduled removed is explicitly documented in your blog posts too.

**Comment by evertharmeling** [comment]
https://symfony.com/blog/upgrade-flex-on-your-symfony-projects advised to update **ASAP**. 

> We have not decided yet when we will shut down the current Flex server, but please upgrade at your earlier convenience to help us move forward faster. 

That was 4 months ago, by just updating (running the mentioned command) you should be good.

**Comment by lol768** [comment]
"earliest convenience" and "we have not decided yet when we will shut down the current Flex server" != "ASAP" in my mind, at all.

> by just updating (running the mentioned command) you should be good

As I mentioned, it's not quite that simple, I had to pin `"laminas/laminas-code": "4.5.1"` to get the updated Flex to install.

**Comment by Athov** [comment]
We are on version 1.9.10 and it's getting the same error, the given solution is not working.

**Comment by evertharmeling** [comment]
> We are on version 1.9.10 and it's getting the same error, the given solution is not working.

Try running `composer why-not symfony/flex ^1.18`

**Comment by Athov** [comment]
> > We are on version 1.9.10 and it's getting the same error, the given solution is not working.
> 
> Try running `composer why-not symfony/flex ^1.18`

![image](https://user-images.githubusercontent.com/8526043/161582209-bc3e6942-7198-42aa-8f75-dd3beb829f29.png)

**Comment by evertharmeling** [comment]
> composer update symfony/flex --no-plugins --no-scripts

There is your problem, you've pinned the version to `"symfony/flex": "1.9.*"`, try changing it to at least `"symfony/flex": "^1.9.0"` (added the `^` in front of the version). And run the mentioned command again.

**Comment by attilajakab** [comment]
Is there a newsletter or some kind of channel where we can subscribe to for such critical / breaking updates? Please let me know.

**Comment by Athov** [comment]
> > composer update symfony/flex --no-plugins --no-scripts
> 
> There is your problem, you've pinned the version to `"symfony/flex": "1.9.*"`, try changing it to at least `"symfony/flex": "^1.9.0"` (added the `^` in front of the version). And run the mentioned command again.

Thank you this helped

**Comment by K4T** [comment]
Unfortunately none of advice from that issue worked for me. 

I simply did `composer require symfony/flex` and symfony/flex ^1.18 has been added to composer.json file. Now, when I execute `composer install` I am receiving Undefined index: splits error.

I am stuck, any ideas, please?

**Comment by nicolas-grekas** [comment]
@K4T You might have a global installation of flex.
Try running `composer global update symfony/flex --no-plugins --no-scripts`

**Comment by ishyevandro** [comment]
@wouterj thanks for creating an issue (i was lost debuging my vendor :joy: ) and showing the solution :pray:

**Comment by ghost** [comment]
@nicolas-grekas 
Something goes wrong with this endpoint `https://flex.symfony.com/versions.json` fetched by symfony/flex on composer install.
It takes more than 10 seconds to get the response with empty json. Therefore "splits" key does not exist in json response.
My application uses symfony/flex v1.15.1.

Upgrading to symfony/flex v1.18.5 fixes this issue for me => https://symfony.com/blog/upgrade-flex-on-your-symfony-projects

**Comment by stof** [comment]
@sfi-fgarnier this is totally expected. The endpoint used by old Flex versions is being shutdown, as announced 6 months ago. That's why this pinned issue links to the blog post.

**Comment by MetalArend** [comment]
Why is `symfony/flex` calling out to a Flex endpoint during a `composer install`? The lock file (which in our case is restricting all packages to a nexus server) should be the SSOT, what is Flex even doing failing over some endpoint not being around on the internet?

**Comment by fabpot** [comment]
@MetalArend That's an issue that was fixed in the newest versions of Flex. So upgrading is the solution here.

**Comment by MetalArend** [comment]
@fabpot Aha, good to know. We've just updated. Thanks!

For some others coming here for the solution, make sure to run `composer update symfony/flex --no-plugins --no-scripts` with the extra flags, to not get stuck not being able to update because of the error that you're trying to solve. Not sure if this holds true for every later version of flex as well, but for us it did.

**Comment by smatyas** [comment]
I guess another problem for many projects will be that they still use php < 8.0, so they won't be able to upgrade for flex 2.x yet :/

**Comment by stof** [comment]
@smatyas to solve the issue, upgrading to Flex 1.18+ is enough.

**Comment by smatyas** [comment]
@stof that will indeed solve the error message issue, but it makes silently install 5.x symfony/* deps for a 4.4 symfony project, which is even worse. We ended up setting those packages one-by-one with 4.4.* in the required block of the composer.json to mitigate the problem. That's what the extra.symfony.require - 4.4.* solved before, until the version.json was working, if I get it right.

I'm not saying it's a bad thing, this situation will make us upgrade those remaining projects finally :)

**Comment by stof** [comment]
@smatyas if you run a full `composer update` with plugins disabled in a project that was relying on Flex to restrict Symfony to 4.4, this will indeed happen. But the instructions given in this issue and in the blog post are asking to do a **partial** update, upgrading *only* symfony/flex.

**Comment by emodric** [comment]
My `symfony/flex` package is on v2.1.6 and I still get this error on one of our projects.

`composer update symfony/flex --no-plugins --no-scripts` does not help since 2.1.6 is the latest version.

![image](https://user-images.githubusercontent.com/362286/161720053-9c9fd984-9111-4a44-bfbb-f46a8edf84f6.png)

Any ideas? Should I just add `flex://defaults`?

My `extra` config is currently:

```
    "extra": {
        "symfony": {
            "allow-contrib": true,
            "endpoint": "https://flex.ibexa.co",
            "require": "5.4.*",
            "docker": false
        }
    }   
```

EDIT:

Adding `flex://defaults` didn't help, and it results in the following error:

![image](https://user-images.githubusercontent.com/362286/161721116-b1cea2db-1bfc-4cfd-917c-d98e77137301.png)

**Comment by xserrat** [comment]
If it helps, I had the following error running `composer update symfony/flex` (I was in the version `v1.14.4 `)
![image](https://user-images.githubusercontent.com/5933658/161723293-bb7da6e2-2bfc-4f49-bf7f-1d6748cf7d5b.png)

And after running what @nicolas-grekas commented it worked well:
![image](https://user-images.githubusercontent.com/5933658/161723561-17bb0ccb-f509-4c1a-a497-0cc542f3a732.png)

**Comment by webhdx** [comment]
@emodric In your case, upgrading to the latest Ibexa DXP release will fix the issue. Just remember to apply changes from [ibexa/website-skeleton](https://github.com/ibexa/website-skeleton/blob/main/composer.json#L98) because we recently switched to serverless Flex approach.

**Comment by Lexus123** [comment]
I updated my symfony/flex to v1.13.4 since that's the highest I can upgrade to.

I keep getting this error even though I ran all the commands stated in this issue. When I run `composer update symfony/flex --no-plugins --no-scripts` my output says there is "nothing to install, update or remove" and that there's "nothing to modify in lock file".

Any guesses why the error keeps popping up?

**Comment by emodric** [comment]
@webhdx Thanks! Will try it ASAP!

**Comment by evertharmeling** [comment]
> I updated my symfony/flex to v1.13.4 since that's the highest I can upgrade to.
> 
> I keep getting this error even though I ran all the commands stated in this issue. When I run `composer update symfony/flex --no-plugins --no-scripts` my output says there is "nothing to install, update or remove" and that there's "nothing to modify in lock file".
> 
> Any guesses why the error keeps popping up?

As stated in the blogpost, you have to minimally update `symfony/flex` to `1.17`, so that's the main reason why you're getting the error. 

Try running `composer why-not symfony/flex ^1.18` to find out what is blocking the update / reason you cannot go higher than v1.13.4.

**Comment by Lexus123** [comment]
> As stated in the blogpost, you have to minimally update `symfony/flex` to `1.17`, so that's the main reason why you're getting the error.
> 
> Try running `composer why-not symfony/flex ^1.18` to find out what is blocking the update / reason you cannot go higher than v1.13.4.

Thanks, good to know I need to update to 1.17.

I know why I can't go higher than v1.13.4, it's because of the Bolt CMS I'm using. bolt/core is blocking.

**Comment by evertharmeling** [comment]
Ah ok, seems like there's an issue for it already :) https://github.com/bolt/core/pull/3160

**Comment by miladghofrani** [comment]
Thanks a lot everyone, my problem solved too after update symfony/flex to 1.18.5

**Comment by amine-betari** [comment]
Hi @nicolas-grekas 

I have made : composer update symfony/flex --no-plugins --no-scripts

```
www-data@bcacb93d6cc3:~/html/project/ezplatform$ composer update symfony/flex --no-plugins --no-scripts
Loading composer repositories with package information
Updating dependencies
Lock file operations: 0 installs, 1 update, 0 removals
   - Upgrading symfony/flex (v1.17.5 => v1.18.5)

```

On the other hand when I did a composer install

```
In PackageFilter.php line 126:
                                                                                                                                                    
   [LogicException]
   The Flex index is missing a "splits" entry. Did you forget to add "flex://defaults" in the "extra.symfony.endpoint" array of your composer.json?
```

**Comment by stof** [comment]
@amine-betari I see that your folder is named ezplatform. Please look at the comment of @webhdx: https://github.com/symfony/flex/issues/890#issuecomment-1088527388 (Ibexa DXP is the new name of ezplatform)

**Comment by wouterj** [comment]
Thanks for all the extra information - I've included some specialized troubleshooting info in the main description :)

**Comment by bobdenotter** [comment]
@Lexus123 I've tagged Bolt `4.2.6`, which shouldn't block Flex 1.18 (or 2.x) anymore. 

https://github.com/bolt/core/releases/tag/4.2.6

**Comment by NeilMasters** [comment]
Some people might need to wipe out their local flex dir before being able to update.

```rm -rf vendor/symfony/flex && composer update symfony/flex```

**Comment by Pyposs** [comment]
> @amine-betari I see that your folder is named ezplatform. Please look at the comment of @webhdx: [#890 (comment)](https://github.com/symfony/flex/issues/890#issuecomment-1088527388) (Ibexa DXP is the new name of ezplatform)

Is there an easier way to fix the problem? ?

**Comment by Pyposs** [comment]
> This error is caused by a very outdated Symfony Flex version. Please update it using this command:
> 
> ```
> composer update symfony/flex --no-plugins --no-scripts
> ```
> 
> Make sure it installs _at least_ 1.17 (or higher). See https://symfony.com/blog/upgrade-flex-on-your-symfony-projects (from November 2021) for more information.
> 
> If you have installed Flex globally, run the command as `composer global update` instead of `composer update` to apply to the global plugin.
> 
> ## If you're using eZ Publish / Ibexa DXP
> See [this comment by @webhdx](https://github.com/symfony/flex/issues/890#issuecomment-1088527388):
> 
> > Upgrading to the latest Ibexa DXP release will fix the issue. Just remember to apply changes from [ibexa/website-skeleton](https://github.com/ibexa/website-skeleton/blob/main/composer.json#L98) because we recently switched to serverless Flex approach.
> 
> ## If you're using Bolt CMS 4
> See [this comment by @bobdenotter](https://github.com/symfony/flex/issues/890#issuecomment-1088671595):
> 
> > I've tagged Bolt `4.2.6`, which shouldn't block Flex 1.18 (or 2.x) anymore.
> > https://github.com/bolt/core/releases/tag/4.2.6
> 
> ## If you can't install Flex 1.17
> Try seeing which dependency or constraint blocks you (and try submitting a fix in their repository), using:
> 
> ```
> composer why-not symfony/flex 1.18.0
> ```

Is there an easier way to fix the problem? ?

**Comment by cirovargas** [comment]
composer update symfony/flex not worked for me

```
#9 [build-deps 3/8] RUN APP_ENV=prod composer install --no-dev
#9 0.771 composer/package-versions-deprecated contains a Composer plugin which is blocked by your allow-plugins config. You may add it to the list if you consider it safe. See https://getcomposer.org/allow-plugins
#9 0.771 You can run "composer config --no-plugins allow-plugins.composer/package-versions-deprecated [true|false]" to enable it (true) or keep it disabled and suppress this warning (false)
#9 0.796 Installing dependencies from lock file
#9 0.810 Verifying lock file contents can be installed on current platform.
#9 11.11 
#9 11.11                            
#9 11.11   [ErrorException]         
#9 11.11   Undefined index: splits  
#9 11.11                            
#9 11.11 
#9 11.11 install [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--dry-run] [--dev] [--no-suggest] [--no-dev] [--no-autoloader] [--no-progress] [--no-install] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--] [<packages>]...
#9 11.11 
#9 ERROR: executor failed running [/bin/sh -c APP_ENV=prod composer install --no-dev]: runc did not terminate sucessfully
```
Trying downgrade to flex 1.17, 

Using symfony 6, PHP 7.4

**Comment by stof** [comment]
> composer update symfony/flex not worked for me

`composer update symfony/flex` is **not** the command you need to run to fix the issue. Please read again the description of this github issue for the full command to run. Options passed to it are important.

**Comment by cirovargas** [comment]
> composer update symfony/flex --no-plugins --no-scripts

Tried with options too, not solve

**Comment by stof** [comment]
@cirovargas btw, your previous comment was showing an error happening during `composer install`, not during `composer update`.

**Comment by cirovargas** [comment]
@stof this is a prod env deploy, i run update on local (updated composer.lock) and submit to deploy

**Comment by cirovargas** [comment]
> composer show symfony/flex
```name     : symfony/flex
descrip. : Composer plugin for Symfony
keywords : 
versions : * v1.18.5
type     : composer-plugin
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
homepage : 
source   : [git] https://github.com/symfony/flex.git 10e438f53a972439675dc720706f0cd5c0ed94f1
dist     : [zip] https://api.github.com/repos/symfony/flex/zipball/10e438f53a972439675dc720706f0cd5c0ed94f1 10e438f53a972439675dc720706f0cd5c0ed94f1
path     : /var/www/html/vendor/symfony/flex
names    : symfony/flex

support
issues : https://github.com/symfony/flex/issues
source : https://github.com/symfony/flex/tree/v1.18.5

autoload
psr-4
Symfony\Flex\ => src

requires
composer-plugin-api ^1.0|^2.0
php >=7.1

requires (dev)
composer/composer ^1.0.2|^2.0
symfony/dotenv ^4.4|^5.0|^6.0
symfony/filesystem ^4.4|^5.0|^6.0
symfony/phpunit-bridge ^4.4.12|^5.0|^6.0
symfony/process ^4.4|^5.0|^6.0
```

**Comment by K4T** [comment]
> Some people might need to wipe out their local flex dir before being able to update.
> 
> `rm -rf vendor/symfony/flex && composer update symfony/flex`

And that was the last missing piece of the puzzle on my side... removing vendors.

**Comment by cirovargas** [comment]
> > Some people might need to wipe out their local flex dir before being able to update.
> > `rm -rf vendor/symfony/flex && composer update symfony/flex`
> 
> And that was the last missing piece of the puzzle on my side... removing vendors.

On my prod deploy i do a fresh install, 
It seems that the problem only happens on composer install, not update

**Comment by nathansalter** [comment]
> The need for updating to Flex 1.17+ was announced both in September 2021 and in November 2021 on the Symfony blog. and this was asked again multiple times on Twitter in the meantime.

I think a better migration path would have been to keep the existing server for a slightly longer period of time but make all the required files 404 so the error was actually at the correct location, maybe even with a static page at the 404 location linking to the blog post. This would have given a simple, easy to find solution. I don't think many people's first port of call is to check the Symfony blog when they get composer errors.

**Comment by fabpot** [comment]
We've been displaying error messages for the last couple of months whenever you run `composer update`. Unfortunately, returning 404 would not help as Composer would just ignore the recipes and you would not have anything useful.
We've also made the server really slow at the same time (the 10 seconds delay) to try to get more feedback. As nobody complained, we thought that the traffic was mainly about bots and misconfigured CIs.
I have also posted tweets over and over again to alert people.
Unfortunately, there is nothing more I would have done (at least, we didn't find anything else we could do).

**Comment by wouterj** [comment]
Apart from all the announcements and warnings that have been put in place, please note that 6 months have passed since the release of Symfony Flex 1.17. It is **always** a good idea to update your tooling more often than once a year (and as it's not production code, it's much more safe to do so).

**Comment by Anzurna** [comment]
We had this issue even after updating symfony/flex.

In our case the problem was in gitlab runner configuration. 
Cached "vendor" directory (with old version of symfony/flex) was preventing package from updating.
````
  cache:
    paths:
      - vendor/

**Comment by fearpro13** [comment]
We have issued same problem today, spent around 2 hours to get rid of this. The reason was very obvious, but found very late. We use gitlab ci-cd and configuration for it(.gitlab-ci.yml) had cache parameter that forced docker-container to use symfony/flex 1.12. Removing this parameter and changing required symfony/flex to ^1.18.5 in composer.json  solved issues.

P.s read comment above

**Comment by colinodell** [comment]
To help with searchability, some affected users may see this error instead:

    [ErrorException] Undefined index: manifests

**Comment by armageddon-cat** [comment]
while trying to fix this issue, i've updated flex version. to 1.17 and to 1.18.5. both gives me new error:
```
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!  Could not open input file: [./bin/console](https://bitbucket.org/../bin/console)
!!  
Script @auto-scripts was called via post-install-cmd
```

any ideas?

**Comment by SantinoPetrovic** [comment]
Updating flex version solved my issue with splits error. Thank you!

**Comment by ericmorand** [comment]
So, Symfony maintainers achieved the unprecedented feat of introducing a breaking change _outside_ of a new release.

Their previous top achievement was when they introduced a breaking change in a patch release, but the sky is the limit.

Congratulations guys.

**Comment by fabpot** [comment]
@ericmorand What do you mean? There is no breaking change here. Read the full story.

**Comment by kubk** [comment]
I think the issue can be closed or limited to maintainers only. It is clear why it happened and what to do in order to fix it.

**Comment by ericmorand** [comment]
@fabpot , a version of flex that was functioning perfectly yesterday doesn't work anymore today, without a single change at all. I don't know, maybe this is not a breaking change, just a "it was working before but not anymore" change.
