### ISSUE TITLE
[Composer\Downloader\TransportException]  The "https://raw.githubusercontent.com/symfony/recipes/flex/main/index.json" file could not be downloaded (HTTP/2 404 )  

### ISSUE THREAD

**Issue by pscibor93** [symfony/flex#891]
Hi, 
I'm  running `composer i --no-cache -vvv` and I'm constantly getting some 404 errors even tho there are contents under the given urls. It's `symfony/flex v1.18.5`
![obraz](https://user-images.githubusercontent.com/18349474/161542418-25ed9684-85f0-4734-8a45-c3fd3c461ad7.png)

**Comment by ok-up** [comment]
I have the same problem 
<img width="1212" alt="Screenshot 2022-04-04 at 15 29 07" src="https://user-images.githubusercontent.com/64357264/161543934-0fca5710-c5bd-48c2-bc6c-f55cdea76661.png">

**Comment by nicolas-grekas** [comment]
All those URLs exists. Can you get them when using curl on the command line?
https://raw.githubusercontent.com/symfony/recipes/flex/main/index.json

**Comment by Oskmoz** [comment]
> All those URLs exists. Can you get them when using curl on the command line? https://raw.githubusercontent.com/symfony/recipes/flex/main/index.json

Same bug here since this morning. But curl with this url is working correctly

**Comment by nicolas-grekas** [comment]
It'd be great if one of you could run the command again, with a composer patched like this:
```diff
--- a/src/Composer/Util/Http/CurlDownloader.php
+++ b/src/Composer/Util/Http/CurlDownloader.php
@@ -195,6 +195,7 @@ private function initDownload(callable $resolve, callable $reject, string $origi
             $bodyHandle = @fopen('php://temp/maxmemory:524288', 'w+b');
         }
 
+        curl_setopt($curlHandle, CURLOPT_VERBOSE, true);
         curl_setopt($curlHandle, CURLOPT_URL, $url);
```

Then running the download again using the curl command line, but with `-v` flag, and compare the debug logs.

**Comment by Oskmoz** [comment]
After a complete cleaning and a rebuild of my local env, this error is solved for me, thx @nicolas-grekas 
I just faced another issue already referenced and fixed : #889 

So everything is fine now thank you !

**Comment by pscibor93** [comment]
For me  the  problem was  in  the  auth.json of  composer i updateg github  token and it worked. Closing

**Comment by soufian-ze** [comment]
try `composer config --global --unset github-oauth.github.com`

I found it in this answer, it was helpful 
https://stackoverflow.com/a/74761372/12127700
