### ISSUE TITLE
Flex breaks composer 

### ISSUE THREAD

**Issue by kamreo** [symfony/flex#892]
Hi guys! I have an issue when running composer install command:

![image (2)](https://user-images.githubusercontent.com/46651594/161553163-6b4b6ed5-1a38-43cc-b970-4c6feafe51d3.png)

Then I when i check https://flex.symfony.com/versions.json it returns empty array! 

![image_480](https://user-images.githubusercontent.com/46651594/161553367-6e96d855-19bf-4a35-b022-19d164513c66.png)

Is there any fix coming or any ideas how to bypass it?

**Comment by steffenbrand** [comment]
+1

**Comment by turtulino** [comment]
See #890

**Comment by wouterj** [comment]
Closing as a duplicate of #890
