### ISSUE TITLE
Issue with Symfony profiler depending on the Twig service

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/flex#90]
This works:

```
composer create-project symfony/skeleton:3.3.x-dev demo && \
cd demo && \
composer req twig && \
composer req profiler
```

But this fails:

```
composer create-project symfony/skeleton:3.3.x-dev demo && \
cd demo && \
composer req profiler
```

![profiler-twig-error](https://cloud.githubusercontent.com/assets/73419/26352429/0a1eb61e-3fbc-11e7-88b8-a8418961bb6a.png)

I'm not sure where/how to solve this.

**Comment by fabpot** [comment]
There is another issue about this. The Symfony web profiler does not depend on the Twig bundle. When doing `req twig`, you install the Twig bundle. But not with the second example.

**Comment by stof** [comment]
Not depending on TwigBundle but only on Twig was what made it possible to use WebProfilerBundle in Silex (which uses the bundle templates and controllers, but not the DI layer)

**Comment by Pierstoval** [comment]
It seems there's a need for a specific composer pack for the web profiler that would require twig bundle too instead of relying just on `symfony/web-profiler-bundle` 😕

**Comment by xabbuh** [comment]
Quick thought: What about a WebProfilerBridge that contains all the code needed for Symfony and Silex? The bundle would then only be responsible for the DI part and could depend on TwigBundle?

**Comment by fabpot** [comment]
For now (and to make it work on 3.3), I've created a profiler-pack. See symfony/recipes#77
