### ISSUE TITLE
Manifest Recipe rule for package.json custom location?

### ISSUE THREAD

**Issue by Spomky** [symfony/flex#902]
Hi,

I read in #764 that Flex is able to copy the content of a bundle `package.json` into the application root one.
From my understanding, this is automatically done by the auto-generated recipe when the `package.json` file is located in `Resources/assets` or `/assets`.

But what if the `package.json` file is not stored in one of these folders?
Is there any rule to be set in the `manifest.json` file to tell Flex where the `package.json` is located?

My use case is the following one:

I would lile to add those lines in the root `package.json` + the content of the  `peerDependencies` section:

        "@web-auth/ux-webauthn": "file:vendor/web-auth/webauthn-framework/src/stimulus/Resources/assets",
        "@hotwired/stimulus": "^3.0.0",
        "@simplewebauthn/browser": "^5.0.0",
        "@simplewebauthn/typescript-types": "^5.0.0"

*Note that `web-auth/webauthn-framework` is a many-repo I split using gitsplit. The is the reason for having such project structure*
The current Flex recipe is located here: https://github.com/Spomky-Labs/recipes/tree/tree/web-auth/webauthn-framework/3.0

Any idea?
Many thanks for your help.
Regards.

**Comment by nicolas-grekas** [comment]
Shouldn't you require the individual split instead of the many-repo?
But to answer your question: the paths look hardcoded in `src/PackageJsonSynchronizer.php`.
Please submit a PR if you think some more flexibility could be desired (note that I personally would prefer everybody could stick to the existing conventions as that makes things easier to discover.)

**Comment by Spomky** [comment]
Hi @nicolas-grekas,

> Shouldn't you require the individual split instead of the many-repo?

Indeed the individual split is the way to go and it works fine.
I understand that conventions improves the DX. I close this issue for now and will take time to find a way to address it.

Regards.
