### ISSUE TITLE
https://flex.symfony.com: connection timeout , connection refused

### ISSUE THREAD

**Issue by kcaporaso** [symfony/flex#912]
During a composer require or composer update I'm encountering a connection timeout or connection refused from the flex.symfony.com URL.  Not sure if this is intermittent or if there is an updated required on my end.  Clearly, I'm trying to update, but flex is having issues.
-----
 $ composer require abc/abc-site-bundle:dev-master#xxxxx
                                                                                                                
  [Composer\Downloader\TransportException]                                                                      
  curl error 28 while downloading https://flex.symfony.com/aliases.json: Connection timed out after 10002 milliseconds                                                                                                      
                            
-----
$ composer update
Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
                                                                                                                
  [Composer\Downloader\TransportException]                                                                      
  curl error 7 while downloading https://flex.symfony.com/versions.json: Failed to connect to flex.symfony.com  
   port 443: Connection refused

**Comment by stof** [comment]
See https://symfony.com/blog/the-old-flex-infrastructure-is-shutting-down
