### ISSUE TITLE
Flex not updating bundles.php with a Symfony 6.1 simplfied configuration 

### ISSUE THREAD

**Issue by tacman** [symfony/flex#914]
I'm running into the same thing, using a bundle with the new, simplified configuration that's available in Symfony 6.1.  I can't figure out why flex isn't updating bundles.php.

```json
{
    "name": "survos/barcode-bundle",
    "description": "Integrates picqer/php-barcode-generator in a Symfony application",
    "type": "symfony-bundle",
    "keywords": ["barcode", "symfony"],
    "require": {
        "php": "^8.1",
        "picqer/php-barcode-generator": "^2.2",
        "symfony/config": "^6.1@RC",
        "symfony/dependency-injection": "^6.1@RC",
        "symfony/http-kernel": "^6.1@RC",
        "twig/twig": "^3.4"
    },
    "license": "MIT",
    "autoload": {
        "psr-4": {
            "Survos\\BarcodeBundle\\": "src/"
        }
    },
    "authors": [
        {
            "name": "Tac Tacelosky",
            "email": "tacman@gmail.com"
        }
    ],
    "minimum-stability": "beta",
    "require-dev": {
        "phpstan/phpstan": "^1.7"
    },
    "extra": {
        "symfony": {
            "allow-contrib": "true",
            "id": "barcode-bundle.survos.com"
        }
    }

}
```

On packagist: https://packagist.org/packages/survos/barcode-bundle
On github: https://github.com/survos/BarcodeBundle

It's a super-simple bundle, I'd like to write a tutorial about how easy it is to share twig extensions with Symfony 6.1, but I'm stuck on this part.  Thanks.

This is very similar to https://github.com/symfony/flex/issues/601.  I've tried renaming a few things, but I'm just hacking now.

**Comment by tacman** [comment]
I've spent many hours on this now, and I got it to work, but my solution seems a bit magic.  And probably wrong, but it's somewhat repeatable.

In my primary bundle file, this works:

```php
<?php
// src/SurvosBarcodeBundle.php

namespace Survos\BarcodeBundle;

use Survos\BarcodeBundle\Twig\BarcodeTwigExtension;
use Symfony\Component\Config\Definition\Configurator\DefinitionConfigurator;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;
use Symfony\Component\HttpKernel\Bundle\AbstractBundle;
use Symfony\Component\HttpKernel\Bundle\Bundle; // phpStorm shows as dim.

class SurvosBarcodeBundle extends AbstractBundle
{

```

If I remove the "use Symfony\Component\HttpKernel\Bundle\Bundle;", then bundle works fine BUT flex does not install it (that it, it doesn't update bundles.php).

Perhaps I'm doing something wrong, but figured I'd report this.

**Comment by stof** [comment]
https://github.com/symfony/flex/blob/e74319d17ed4edc5f27b9d24757e172930a7ebc4/src/SymfonyBundle.php#L110 needs to be updated to check for the AbstractBundle class name too.

anyone wanting to do a PR ?

**Comment by tacman** [comment]
Oh, I'll do it, just for the chance to be a Symfony contributor!

On a related note, I'm getting ready to publish this, feedback welcome:
***@***.***/easily-share-your-twig-extensions-with-symfony-6-1-ff633bf7d9db

**Comment by tacman** [comment]
On a related note, composer remove my/simplified-bundle is not removing the bundle from bundles.php.  What does flex check for when deciding to do that?  Where in the code does that happen?
