### ISSUE TITLE
Symfony 6.1 bundles remain registered after composer remove

### ISSUE THREAD

**Issue by tacman** [symfony/flex#920]
Removing a bundle with the new Symfony 6.1 simplified configuration does not remove line in bundles.php

```bash
symfony new bundle_bug && cd bundle_bug
composer req survos/barcode-bundle
composer remove survos/barcode-bundle
git diff config
```

The bundle is added correctly, but not removed. 

```bash
 return [
     Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
+    Survos\BarcodeBundle\SurvosBarcodeBundle::class => ['all' => true],
 ];
```

@stof , you found the related installation problem https://github.com/symfony/flex/issues/914, might this be similar?

**Comment by stof** [comment]
@tacman was this added automatically or manually ?

**Comment by tacman** [comment]
Automatically.  If you cut and paste these 4 lines into a terminal, you should be able to see the error:

```bash
symfony new bundle_bug && cd bundle_bug
composer req survos/barcode-bundle
composer remove survos/barcode-bundle
git diff config
```

**Comment by tacman** [comment]
Adding 

    composer config extra.symfony.allow-contrib true

didn't help.

**Comment by nicolas-grekas** [comment]
Will be fixed by https://github.com/symfony/flex/pull/929, thanks for reporting.
