### ISSUE TITLE
Support Alpha and Beta semantic versioning 

### ISSUE THREAD

**Issue by Ferror** [symfony/flex#921]
Hi!

I have a self-hosted/serverless Symfony Recipes server with recipe versions `1.0` and `1.0.0-ALPHA.7`. They are valid under semantic versioning https://semver.org/#spec-item-9 Then I try to install my package with version `1.0.0-ALPHA.7` and Symfony Flex chooses the `1.0` recipe version, wherein my opinion it should choose `1.0.0-ALPHA.7`.

The code responsible for that is located in: https://github.com/symfony/flex/blob/1.x/src/Downloader.php#L206-L208

Don't have the idea how to handle all of the situations, but I think it would be a nice touch for Symfony Flex to prioritize the same package version as the recipe version.

**Comment by nicolas-grekas** [comment]
I don't get why this would be needed. This number is not exactly the version of the recipe. It's the minimum version of the target package that the recipe should apply to.

**Comment by Ferror** [comment]
> I don't get why this would be needed. This number is not exactly the version of the recipe. It's the minimum version of the target package that the recipe should apply to.

Exacly, the 1.0 minimum version shouldn't be used with `1.0.0-ALPHA.7` package version, as it is pre 1.0 release

**Comment by nicolas-grekas** [comment]
Can you please explain what this would allow that cannot be done today?

**Comment by Ferror** [comment]
Sure. I have a code base with fairly stable alpha and beta versions. I would like to speed up configuration, that's why Symfony recipes are cool 😄 but I can't/don't know how to describe the minimal recipe version to meet my requirements precisely. The configuration may radically change in the future therefore it would be nice to define the recipe version for `1.0.0-ALPHA.7`, and then different for  ex`1.0.0-ALPHA.8`. The thing is as far as I know we can't achieve that, as the recipe minimum version defined as `1.0.0-ALPHA.7` won't actually be recognized by `1.0.0-ALPHA.7` package version.

**Comment by fabpot** [comment]
If your code base is stable, then it's not alpha or beta.
I don't think this is something we need to support as the use case seems really specific.

**Comment by Ferror** [comment]
Well in the best scenario I would create `1.0.0-ALPHA.7` recipe and `1.0.0-ALPHA.7` tagged bundle would use it :(
