### ISSUE TITLE
composer require annotations : Could not find package annotations

### ISSUE THREAD

**Issue by stloc** [symfony/flex#935]
composer.json :
```
{
    "require": {
        "symfony/flex": "^1.19"
    }
}
```

```
 [InvalidArgumentException]
  Could not find package annotations.

  Did you mean one of these?
      zeptech/annotations
      doctrine/annotations
      ray/di
      jms/metadata
      doctrine/common
```

**same for new project :** 

`symfony new my_project_directory --version="5.4.*" --webapp`

```
[InvalidArgumentException]
  Could not find package webapp.

  Did you mean one of these?
      peej/tonic
      leafs/leaf
      symfony/webapp-meta
      symfony/webapp-pack
      hiqdev/hidev-webapp
```

**Comment by stof** [comment]
Do you already have Flex installed locally ? If not, that's expected, as the plugin won't be activated if it is not installed yet.

And did you configure Composer to forbid running the Flex plugin ? That could be another reason why it is not activated.

**Comment by stloc** [comment]
![image](https://user-images.githubusercontent.com/4832070/176448094-e3d08b5d-dfde-4dd7-9d1c-ff60d8c8a789.png)

**Comment by stloc** [comment]
I updated composer (WSL) and reinstall symfony binary
