### ISSUE TITLE
ContainerConfigurator does not support xml

### ISSUE THREAD

**Issue by shyim** [symfony/flex#949]
When your project completely bases on XML files for [services.xml](https://github.com/shopware/production/blob/6.4/config/services.xml) (or PHP), and you run now a flex script which tries to add something to the `services.yaml` it explodes with an exception

![image](https://user-images.githubusercontent.com/6224096/192264804-5957f58d-3968-4c2e-ad9f-87c2b624c292.png)

**Comment by wouterj** [comment]
Hi! 

The error says it cannot find the file at the specified location, nothing is said about supporting xml/yaml.

Please use [one of the support channels](https://symfony.com/support) to ask for community support, this issue tracker is meant for bug reports and feature requests.

**Comment by shyim** [comment]
I know it cannot fine that file. As Symfony allow so many file formats, the ContainerConfigurator should also support these all

**Comment by xabbuh** [comment]
If this was meant as a bug report, I think you need to provide more details (especially how to reproduce and how not supported XML is related to a YAML file that could not be found).

**Comment by shyim** [comment]
Updated the description above
