### ISSUE TITLE
[Bug] Load resource with glob patterns in Kernel

### ISSUE THREAD

**Issue by alOneh** [symfony/flex#95]
I play with Flex today with a fresh install, after installing `twig`without problems it created a `routing/dev/twig.yaml` file in `etc/` folder. After refreshing my browser I got the following error :

<img width="1060" alt="capture d ecran 2017-06-02 a 00 24 03" src="https://cloud.githubusercontent.com/assets/758625/26703491/3e345db2-472a-11e7-849c-1bb0af5b78d3.png">

**Comment by fabpot** [comment]
ping @nicolas-grekas Apparently, you broke something :)

**Comment by alOneh** [comment]
after debugging, reverting this [fix](https://github.com/symfony/symfony/pull/21736) seems to make all things good. 
To reproduce, no need to install any deps, simply add an empty `routing` dir in the `etc` folder

**Comment by nicolas-grekas** [comment]
Not my fault :)
Maybe not a bug also :P

**Comment by nicolas-grekas** [comment]
@alOneh can you post the stack trace when symfony/config is upgraded to `3.3@dev` please?

**Comment by fabpot** [comment]
Problem solved in 3.3.1.
