### ISSUE TITLE
Stale cache is used

### ISSUE THREAD

**Issue by teohhanhui** [symfony/flex#96]
In a new project, running `composer update` with `-vvv` flag:
```
Reading /root/.composer/cache/repo/https---symfony.sh/m-lexik-jwt-authentication-bundle-v2.4.0 from cache
Downloading https://symfony.sh/m/lexik/jwt-authentication-bundle/v2.4.0
    Detected auto-configuration settings for "lexik/jwt-authentication-bundle"
    Enabling the package as a Symfony bundle
    Setting configuration and copying files
    Adding environment variable defaults
    Adding Makefile entries
```

I can verify that the changes from symfony/recipes#85 are not present.

There doesn't seem to be any proper cache validation mechanism, or it's non-functional...

**Comment by teohhanhui** [comment]
Okay, it looks like it's a problem on the server side.

**Comment by fabpot** [comment]
This has been fixed now. Can you confirm?
