### ISSUE TITLE
Next release ?

### ISSUE THREAD

**Issue by smnandre** [symfony/flex#969]
Hi all, is there a release scheduled ?

This one (#965) solved a big trouble for me at work.. and i could use a custom requirement to use it.
But it would be much easier if it was released :)

If there is something blocking, may i help on something ?

cc @weaverryan @nicolas-grekas

**Comment by fabpot** [comment]
I've just released new versions for the 1.x and 2.x branches.

**Comment by smnandre** [comment]
Thank you very much !
