### ISSUE TITLE
Not reporting auto-configuration is ignored for contrib recipe

### ISSUE THREAD

**Issue by sstok** [symfony/flex#97]
When I run composer install, Flex reports an auto-configuration is detected, however when the recipe is part of contrib it doesn't report the recipe itself ignored.

I thought this was bug, but I forgot to set the allow-contrib to true :)
Maybe it's a good idea to inform there is a (contrib) recipe but it was ignored?

```
- Installing pomm-project/pomm-bundle (2.3.1): Loading from cache
    Detected auto-configuration settings for "pomm-project/pomm-bundle" (contrib-recipes disabled)
    Enabling the package as a Symfony bundle
```

**Comment by fabpot** [comment]
Sounds like a good idea. Can you submit a pull request?
