### ISSUE TITLE
Certificate error https://flex.symfony.com

### ISSUE THREAD

**Issue by Detract** [symfony/flex#991]
Hi, 

we get a certificate error when opening https://flex.symfony.com/

Certificate is only valid until 23. July 2023 11:28:48

Dirk

**Comment by nicolas-grekas** [comment]
This domain name is discontinued, please update to the latest version of symfony/flex.

**Comment by wouterj** [comment]
See https://symfony.com/blog/the-old-flex-infrastructure-is-shutting-down

**Comment by Detract** [comment]
Thank you for your quick reply.
