### ISSUE TITLE
Suggest adding management of the compose.yml file in addition to docker-compose.yml

### ISSUE THREAD

**Issue by roukmoute** [symfony/flex#992]
Hello !

Following my use of Symfony Flex and its wonderful ability to manage Docker configurations via recipes, I noticed that the manifest supports the docker-compose.yml file.

However, consulting the official Docker documentation, it seems that the use of the docker-compose.yml file may be gradually deprecated or, at least, that there is an alternative under the name compose.yml. Details can be found on this page: https://docs.docker.com/compose/multiple-compose-files/merge/

Proposal:

- Add support for compose.yml to the Symfony Flex manifest.
- Check whether a docker-compose.yml already exists and use it, otherwise create a compose.yml.

This will ensure better compatibility with future versions of Docker Compose and offer greater flexibility to developers using Symfony Flex.

I'd love to hear your thoughts on this and whether this is something you'd consider adding to Symfony Flex.

Thank you for your time and consideration!

**Comment by dunglas** [comment]
Definitely something we need. I also plan to switch Symfony Docker and the API Platform distro to `compose.yaml`.
